### ISSUE TITLE
Q1 - DABS Compliance Updates and Maintenance

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#1]
[Compliance App](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=a0e8ef3ea26e4c29b1714e993896bed8)
[DABS Commission App](https://experience.arcgis.com/experience/0c3aa87b41d04274a5d6858d06d5f3f6)
[Update Sheet](https://docs.google.com/spreadsheets/d/1VQu6vMrYhlRB_ku4CCZ4E7rGjfMTM2SdnkmX_eVqj1Y/)
**For FY24:** Where are there points of improvement to minimize Erik's time for support and maintenance of the tasks below?

## Benefit Hypothesis
The web applications benefit both the DABS compliance staff to plan licensee visits and answer other spatial questions about licensees; and better enables the DABS commission to make decisions about license applications during their review meetings.

## Acceptance Criteria
- Provide monthly [license updates](https://docs.google.com/spreadsheets/d/1VQu6vMrYhlRB_ku4CCZ4E7rGjfMTM2SdnkmX_eVqj1Y/edit#gid=1304966721) to the interactive [Compliance app](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=a0e8ef3ea26e4c29b1714e993896bed8). 
- Support for DABS' use of OpenGov software, including the mostly manual ETL of a master address table (MAT) to work with the OpenGov system

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] New MAT by August 9
  - new name if it includes any new fields
  -  put municipality name in City field OR if no municipality put county name (+ 'County') in City field
- [ ] June and July license and app updates

**Comment by nathankota** [comment]
### Sprint 4 Tasks:
- [ ] how to deal with address points that aren't in the MAT?

**Comment by nathankota** [comment]
@rkelson Can some of the sprint 4 tasks be checked off, and is there anything for sprint 5?

**Comment by nathankota** [comment]
@rkelson like this?

### Sprint 5 Tasks
- [ ] how to deal with address points that aren't in the MAT?
- [ ] Finish code to use OGs
- [ ] Complete second half July and August license updates

**Comment by rkelson** [comment]
sure but shouldn't the Active Sprint category also be changed? I'm still trying to figure this out

**Comment by nathankota** [comment]
> sure but shouldn't the Active Sprint category also be changed? I'm still trying to figure this out

yes, good catch, I just changed it. You should be able to as well, so if you can't please let me know.

**Comment by rkelson** [comment]
working on an answer to 'how to deal with address points that aren't in the MAT?'. Zach and I talked about a process of getting the new records added to the address points but I need to validate the addresses provided in the "MAT address issues' spreadsheet DABS provided

**Comment by rkelson** [comment]
code updated to use OGs new Rec_Number that replaced Lic_Number
quarter updates completed.
