### ISSUE TITLE
data.mapserv.utah.gov fix for Print Proxy

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#105]
Ref:
- [INC1811991](https://utah.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D0d5de24f47c2299402dfd08c346d43da%26sysparm_stack%3D%26sysparm_view%3D)

**Comment by nathankota** [comment]
@stdavis are there other INC's worth referencing here for firewalls and such?

**Comment by stdavis** [comment]
This has been completed.
