### ISSUE TITLE
LIR Parcel updates - Annual

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#111]
## Acceptance Criteria

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] Continue obtaining info/data from State Auditor's Office
  - Check in with Auditor about iterating back and forth with counties to request the latest data

**Comment by rkelson** [comment]
8/22/2023 - Spoke with Alex in State Auditors office about discrepancies with the data he provided and what Davis County has on their website. Waiting to hear back from Davis Co.

In https://github.com/agrc/planning-queue/issues/131#issuecomment-1680839152 Matt told me to move forward with what the State Auditor (Alex) can provide.

- [ ] Find out what Davis Co says about the discrepancies 
- [ ] Get latest data from Alex
- [ ] Find out if the HB433 attribute should be in the LIR parcels or Basic parcels or both
- [ ] Develop new code to use the data from Alex
- [ ] Update LIR datasets

**Comment by rkelson** [comment]
Working on new code but finding issues such as parcel IDs that got altered during the processing to create the St. Auditor's table

**Comment by rkelson** [comment]
18 counties completed with a few more to come
https://github.com/agrc/gis.utah.gov/pull/2369

**Comment by nathankota** [comment]
@rkelson Please enter some closing comments and close this Q1 task down. Do you want to track the continuation of this with a new Q2 task?

**Comment by rkelson** [comment]
waiting for the remaining counties to become available. This task needs to continue into Q2

**Comment by nathankota** [comment]
> ...This task needs to continue into Q2

@rkelson when you're ready, please use the [planning-queue new feature template](https://github.com/agrc/planning-queue/issues/new?assignees=&labels=&projects=agrc%2F6&template=feature.yml) to create a Q2 task for this

**Comment by rkelson** [comment]
I am actually thinking to keep this closed and not create A Q2 task. Not sure when the other counties, if at all, will become available
