### ISSUE TITLE
PLSS - Updates (Local & BLM)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#118]

**Comment by steveoh** [comment]
@nathankota @seanfernandez is this the project we were discussing last week?

**Comment by nathankota** [comment]
> @nathankota @seanfernandez is this the project we were discussing last week?

Probably, but this is another relic from the early days of PI planning and trying to create a backlog of possible tasks. I don't think it  needs to persist, and I will work with Sean to create a new PLSS data and app task as we discuss and plan next steps.
