### ISSUE TITLE
UGRC Windows Servers 2012 Upgrades

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#129]
## Benefit Hypothesis
UGRC Windows Servers need to be upgraded from 2012 to 2022 to meet DTS standards and requirements. 
Security.

## Acceptance Criteria
The following machines will be rebuilt within Windows Server 2022:
- **itwapigp:** in active development; will continue to reside in GCVE
- **itwgisweb1gp:** in active development; will continue to reside in GCVE

**Comment by nathankota** [comment]
[REQ0173468](https://utah.service-now.com/sc_request.do?sys_id=4a78ce48470c7d14184a874c346d43ec&sysparm_record_target=sc_request&sysparm_record_row=2&sysparm_record_rows=110&sysparm_record_list=opened_by%3Djavascript%3Ags.getUserID%28%29%5EORDERBYDESCsys_created_on): itwapigp replacement server

[REQ0173470](https://utah.service-now.com/sc_request.do?sys_id=9f994ec8470c7d14184a874c346d43cf&sysparm_record_target=sc_request&sysparm_record_row=1&sysparm_record_rows=110&sysparm_record_list=opened_by%3Djavascript%3Ags.getUserID%28%29%5EORDERBYDESCsys_created_on): itwgisweb1gp replacement server

**Comment by nathankota** [comment]
### Sprint 2 Tasks:

- [ ] Follow-up on INC1860880
- [ ] Install software on machines
- [ ] Configure software
- [ ] Testing

**Comment by steveoh** [comment]
This is currently blocked by firewall access to the machines. I am coordinating with ops to gain access.

**Comment by nathankota** [comment]
### Sprint # Tasks:

- [ ] validate INC1860880
- [ ] (see notes above for more)

**Comment by steveoh** [comment]
### Sprint 3 updates

8/8 12:45

- dns to ip data has been corrected (INC1868734)
- RITM0248275 implemented
- RITM0248144 implemented
- No public access to the load balancers still (RITM0247752)

**Comment by nathankota** [comment]
### Sprint 4 Notes
#### August 25
- Old web server (itwgisweb1gp, 10.208.48.1) decommission request [RITM0250755](https://utah.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3D830866b647fcb150184a874c346d4312%26sysparm_record_target%3Dsc_req_item%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Drequest%253D0f0866b647fcb150184a874c346d4311%255EORDERBYDESCsys_created_on). Check on it.

**Comment by steveoh** [comment]
### Sprint 5 Notes (Steve)

**Sept 11 5:32PM**

- SNAT broke IP based api keys for ~5 hours
   - Mike took down the api for a few minutes 
   - After we disabled SNAT, GCVE servers cannot round trip to the api. Forklift etc won't be able to geocode until this is fixed.
   - Core cloud is looking into this as we solved it with the last load balancer but no one remembers how and it's not obvious
- We're going to eat this for a little while and move forward with the migration since we know a solution is available

**Comment by nathankota** [comment]
SNAT issue resolved and carried-over server and load balancer removal tasks to Q2
