### ISSUE TITLE
Q1: Migrate AGOL Minimalist Instant Apps

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#132]
### Statement of Need
Esri AGOL Minimalist Instant app template is being deprecated. Need to migrate all production apps in the UGRC AGOL that use that template to a different one.

## Benefit Hypothesis
Get ahead of the Minimalist app retirement.

## PI Acceptance Criteria
These are the apps that need to be migrated or deprecated. Check the ones that could be dealt with in FY24 Q1 PI.

- [x] [Utah Lidar Coverage](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=35d08d7d23ca4293b657d570f1005822), [Porter #236](https://github.com/agrc/porter/issues/236) - Rick
- [ ] [DTS EIN Locations](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=d4aad4b19fea448da757385588ab620f) - Jake
- [ ] [Masquerade Demo](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=d9287c84bb754de78c834517205d7a62) - UtahAGRC, Scott?
- [ ] [PLSS Monument Preservation Tie Sheet](http://utah.maps.arcgis.com/apps/Minimalist/index.html?appid=16b3f737cc024606a3fb0de815bd08fb), UtahAGRC, ? Not Rick
   - Dec. 5, 2023: asked Sean if he still needs this app, or if it can be deprecated 
- [ ] [Qualifying Tracts](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=2a4985939d9f45dc89e9041e7715f452) - Jake
- [x] [TURN and Nevada GPS Stations](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=95e0d153d1ce4ba39556c9f94284c68c), [Porter #237](https://github.com/agrc/porter/issues/237), Rick
- [ ] [UORG 2016 Unfunded Projects](http://utah.maps.arcgis.com/apps/Minimalist/index.html?appid=f2b60db703954e41a8020e271fdc412d) - UtahAGRC, Zach?
- [ ] [Utah DABC Licenses](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=231799f7d43b42849552b0de85e63247) - Zach

**Comment by steveoh** [comment]
What do you think about adding DNS to these so the underlying url can migrate in the future without requiring a deprecation?

**Comment by rkelson** [comment]
I only lay claim to the Lidar & Turn apps. I am not familiar with the PLSS Monument app.

**Comment by rkelson** [comment]
@steveoh are you saying we could create _lidarcoverage.utah.gov_ & _turn.utah.gov_ for the apps?

**Comment by steveoh** [comment]
Pretty much

**Comment by rkelson** [comment]
_Utah Lidar Coverage_ and _TURN and Nevada GPS Station_ have been migrated. I would check the boxes but I don't seem to have edit capabilities

**Comment by steveoh** [comment]
> I would check the boxes but I don't seem to have edit capabilities

I updated the permissions so you should be able to do that now.

**Comment by nathankota** [comment]
transferring notes and closing in favor of #223
