### ISSUE TITLE
GPS Server Migration grwgps4

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#153]
## Acceptance Criteria

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] Research/requirements for bill pay

**Comment by nathankota** [comment]
### Future Sprint Tasks:
- [ ] Notify current users about server swap date (from grwgps4 to grwgps01gp)

**Comment by nathankota** [comment]
### Sprint 3 Notes
- Dbase is going to copy/update dev-to-prod TURN accounting database 3 times/week (M,W,F) by EOB through September 18th, and will bill to a UGRC ELCID for their time

**Comment by steveoh** [comment]
The notification was sent last thursday.

<img width="974" alt="image" src="https://github.com/agrc/planning-queue/assets/325813/19abec8c-daca-4ff2-ac82-aca81fa843ea">

**Comment by nathankota** [comment]
### Sprint 5 Tasks:
- [x] Connect grwgps5 (Nevada GPS) to itdb002gp

**Comment by nathankota** [comment]
### Sprint 6 Tasks
- [ ] Swap bill pay to grwgps01gp

**Comment by nathankota** [comment]
@seanfernandez Please enter some final notes and close this task.

**Comment by seanfernandez** [comment]
We have completed the migration and just need to confirm that we have all the configuration files needed for the bill pay system before we fully disable grwgps4.
I will work on getting everything copied off tomorrow, and we plan on decommissioning the server either Wednesday or Thursday.

**Comment by nathankota** [comment]
@seanfernandez please use #233 for the last pieces of this. Closing.
