### ISSUE TITLE
PSAP support

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#154]

**Comment by gregbunce** [comment]
taking over for Erik while we get the new person onboarded.

**Comment by nathankota** [comment]
@gregbunce should we assign a sprint or due date, and define acceptance criteria (list of PSAPs supported in the quarter?), etc. for this?

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] Weber
- [ ] Davis
- [ ] Beaver

**Comment by nathankota** [comment]
### Sprint 3 Tasks
- [ ] Weber
- [ ] Davis
- [ ] ...

**Comment by nathankota** [comment]
### Sprint 4 Tasks
- [ ] Davis
- [ ] ...

**Comment by gregbunce** [comment]
note: i will transitioning these tasks to Hank Chou over the next few weeks.

**Comment by nathankota** [comment]
### Sprint 4 Notes
#### September 5
- Jeff still working on getting the Morgan data to us so the ROAM subdivision can be added to the Weber Area dispatch 911 data ASAP

**Comment by gregbunce** [comment]
note: I have been working with Hank on PSAP updates, as he will eventually be taking over this task.

Currently, we are working on:

**Comment by nathankota** [comment]
@gregbunce, @mhchou please check off the PSAPs you completed in the Sprint 5 task list, and provide a closing comment, and close the issue/task.

**Comment by mhchou** [comment]
Layton had a complete update. Weber had a small update. The complete update is in progress. I had met with St. George but no updates yet.
