### ISSUE TITLE
Address point editor enhancements

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#160]
Auto populate FullAddress field.
Auto populate UtAddPtID field.
Auto populate county, editor, and address source based on user credentials.
Portal branched versioning

Input validation:
- Prefix direction != Suffix direction
- If street name is numeric prefix and suffix directions are required
- If street name is alpha a street type is required
- Other required fields?

**Comment by steveoh** [comment]
@ZachBeck should this be closed and replaced by #409?

**Comment by ZachBeck** [comment]
Yep, this has been replaced by #409
