### ISSUE TITLE
DHHS - Newborn Safe Haven Map/app

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#165]
### Benefit
Intuitive map and user interface for locating newborn safe haven hospitals.

### Acceptance Criteria
- Hospital data corrected and standardized for geocoding, map display, filtering, etc.
- AGOL web map and app creation
- Embed app in safe haven website

**Comment by nathankota** [comment]
### Sprint X Tasks
- [ ] Obtain hospital data
- [ ] Create a doc outlining
  - Definitions
  - Key Assumptions
  - Open Questions
  - Process

**Comment by nathankota** [comment]
### Sprint 3 Notes
## August 16
- Geocoded [hospital data](https://docs.google.com/spreadsheets/d/1BfMAUod-69zUCA5AnqSwXPP7b6pfEkBQbwYEZktUl7ohttps://docs.google.com/spreadsheets/d/1BfMAUod-69zUCA5AnqSwXPP7b6pfEkBQbwYEZktUl7o)
- Sent an email explaining what I did and next steps

> Thank you for sending the address data Josie. I spent some time this morning reviewing the sheet, altering it a bit, and sending the data through the UGRC geocoder to obtain location data (x,y coordinates) and associated accuracy scores. These x,y coordinates will be the basis for mapping the facility locations. The results are in this sheet: 
> https://docs.google.com/spreadsheets/d/1BfMAUod-69zUCA5AnqSwXPP7b6pfEkBQbwYEZktUl7o
> 
> Here is a summary of my actions:
> Broke the address data you provided within a single data field into four separate fields (address, city, state, zip), so it could be geocoded.
> This resulted in two 'city' fields, since there was a City column on the sheet before addresses were added, and the address information also included city.
> I renamed the original City column as "City1", and called the other one (from the provided address information) "City".
> There were some inconsistencies between these two city fields, which are noted on the sheet.
> Inserted some missing zip codes, made some address changes that were immediately obvious, and noted some other things that might need to be investigated and changed. All of this is in the Notes column.
> Ran the sheet through the UGRC geocoding [API client](https://github.com/agrc/api-client/releases), which added some new columns to the sheet (highlighted blue)
> Where the score value was less than 100, I quickly compared the match_address from the geocoding process with the Address you provided.
> Added a column for Corrections to indicate what I think could be done to make the address data better to result in a higher geocoding score. The goal is to get as close to 100 as possible.
> Next steps:
> Your team reviews the Notes and Corrections columns, and asks any questions you may have about them.
> Your team makes corrections to your hospital source data. 
> Provide us with a new data set with the corrections.
> We run the data through the geocoder again, review the scores, and see if we need to make more corrections to the data.
> After another round of data cleaning and validation, we can get it into our schedule to map the hospital address locations. Then we'll ask for another round of review by your team to ensure the locations match what you expect.
> 
> After the meeting last week we consulted about our expected effort to build the data set, map resources, and a final interactive map to embed within or link from your website. Our estimate for that is 50 hours, which equates to between $5,000 and $6,000. This is always the most difficult part of our job to explain that we are not a fully funded agency and, therefore, require billable project time to fulfill our revenue needs. I also understand that this may be an unexpected cost for your program budget, which can be difficult as well. I am available for a conversation about th

is, and to further discuss how you would like to proceed.

**Comment by nathankota** [comment]
### Sprint 1 Notes
#### October 12
- The SBA is completed, approved, and added to the service now task.

**Comment by nathankota** [comment]
### Sprint 5
Do it!

**Comment by jacobdadams** [comment]
### Sprint 6

- [ ] Meet with DHHS, discuss feedback and next steps

**Comment by nathankota** [comment]
Continued via #277
