### ISSUE TITLE
ArcGIS Server Upgrade on Mapserv

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#166]
**steve**
  [From Slack thread](https://agrc.slack.com/archives/C010XCU0LKG/p1690383601756319)
It might be time to update arcgis server on mapserv… https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/
ArcGIS BlogArcGIS Blog
[ArcGIS Server Security 2023 Update 1 Patch available!](https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/)
ArcGIS Server Security 2023 patch is now available (77 kB)
https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/

**23 replies**

**Scott**
Probably a good idea. Are you thinking brand new machines or upgrading in place?

**steve**
i’m leaning toward in place but am curious about what version of windows we are running

**steve**
i think if we’re on 2019 we just go with in place

**Scott**
I’ll check once my laptop finishes this update…

**steve**
no rush really, i think we just jam in on the board cc 
[@Nathan](https://agrc.slack.com/team/UB9QKLUJZ)
:+1::skin-tone-3:
1

**Scott**
:disappointed:
image.png
 
image.png

**steve**
do you remember how excited you were to upgrade to 10.3 once upon a time?

**steve**
all these years have you jaded?

**Scott**
Haha. Esri doesn’t have anything exciting anymore.

**Scott**
I don’t mind running upgrades. Rebuilding machines is just no fun.

**steve**
we could try in place windows upgrade

**steve**
it’s an option

**Scott**
With a snapshot, I think that it’s worth a try. Not much happens on mapserv these days. I can’t imagine there’s that much cruft.

**steve**
agreed

**steve**
we’re pretty close to not needing it

**Scott**
Another year or two and we may be able to kill it.

**steve**
i wonder how we could replace feature service editing (address point thing) and GP tools (is printing the only thing left?)

**Scott**
I’m not sure about the gp tools. Maybe feature service editing could be moved to portal?

**steve**
oh you stop it

**steve**
time for you to go home

**Scott**
Portal alone is better than AGS + Portal

**steve**
is there a squinty eye emoji

**Comment by steveoh** [comment]
This slack chat will expire so you might want to copy it

**Comment by nathankota** [comment]
steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690383601756319)
It might be time to update arcgis server on mapserv… https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/
ArcGIS BlogArcGIS Blog
[ArcGIS Server Security 2023 Update 1 Patch available!](https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/)
ArcGIS Server Security 2023 patch is now available (77 kB)
https://www.esri.com/arcgis-blog/products/trust-arcgis/announcements/arcgis-server-security-2023-update-1-patch-available/

23 replies


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690400115821989?thread_ts=1690383601.756319&cid=C010XCU0LKG)
Probably a good idea. Are you thinking brand new machines or upgrading in place?


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690400219684939?thread_ts=1690383601.756319&cid=C010XCU0LKG)
i’m leaning toward in place but am curious about what version of windows we are running


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690400254768189?thread_ts=1690383601.756319&cid=C010XCU0LKG)
i think if we’re on 2019 we just go with in place


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690400434211209?thread_ts=1690383601.756319&cid=C010XCU0LKG)
I’ll check once my laptop finishes this update…


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690400456229579?thread_ts=1690383601.756319&cid=C010XCU0LKG)
no rush really, i think we just jam in on the board cc 
[@Nathan](https://agrc.slack.com/team/UB9QKLUJZ)
:+1::skin-tone-3:
1



Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406200109789?thread_ts=1690383601.756319&cid=C010XCU0LKG)
:disappointed:
image.png
 
image.png


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406257683439?thread_ts=1690383601.756319&cid=C010XCU0LKG)
do you remember how excited you were to upgrade to 10.3 once upon a time?


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406279657069?thread_ts=1690383601.756319&cid=C010XCU0LKG)
all these years have you jaded?


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406311591809?thread_ts=1690383601.756319&cid=C010XCU0LKG)
Haha. Esri doesn’t have anything exciting anymore.


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406334998559?thread_ts=1690383601.756319&cid=C010XCU0LKG)
I don’t mind running upgrades. Rebuilding machines is just no fun.


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406351878869?thread_ts=1690383601.756319&cid=C010XCU0LKG)
we could try in place windows upgrade


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406366230299?thread_ts=1690383601.756319&cid=C010XCU0LKG)
it’s an option


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406386996699?thread_ts=1690383601.756319&cid=C010XCU0LKG)
With a snapshot, I think that it’s worth a try. Not much happens on mapserv these days. I can’t imagine there’s that much cruft.


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406402998309?thread_ts=1690383601.756319&cid=C010XCU0LKG)
agreed


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406416759209?thread_ts=1690383601.756319&cid=C010XCU0LKG)
we’re pretty close to not needing it


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406462281559?thread_ts=1690383601.756319&cid=C010XCU0LKG)
Another year or two and we may be able to kill it.


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690406555050579?thread_ts=1690383601.756319&cid=C010XCU0LKG)
i wonder how we could replace feature service editing (address point thing) and GP tools (is printing the only thing left?)


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690407336918779?thread_ts=1690383601.756319&cid=C010XCU0LKG)
I’m not sure about the gp tools. Maybe feature service editing could be moved to portal?


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690407351089409?thread_ts=1690383601.756319&cid=C010XCU0LKG)
oh you stop it


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690407359127839?thread_ts=1690383601.756319&cid=C010XCU0LKG)
time for you to go home


Scott
:no_entry:  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690407376332709?thread_ts=1690383601.756319&cid=C010XCU0LKG)
Portal alone is better than AGS + Portal


steve
  [15 days ago](https://agrc.slack.com/archives/C010XCU0LKG/p1690407403475399?thread_ts=1690383601.756319&cid=C010XCU0LKG)
is there a squinty eye emoji

**Comment by nathankota** [comment]
Instead, Mapserv is being deprecated:
- https://github.com/agrc/porter/issues/276

**Comment by steveoh** [comment]
Only half of mapserv is being deprecated. Upgrading is still a priority.

**Comment by steveoh** [comment]
I'm thinking we should ignore this and focus on migrating any remaining services to portal.

**Comment by stdavis** [comment]
@steveoh Are you OK to close this issue?

**Comment by steveoh** [comment]
Yep, let's close it
