### ISSUE TITLE
Roadkill Expo upgrade and app enhancements

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#168]
Current app is at v47. If we don't upgrade

> we won't be able to submit new updates to the app unless (it is) upgraded it to Expo 48, which targets the correct Android API version. The app is currently at v47. Upgrading expo versions is not a small thing but should be part of any new update that (is done) anyways.

![Image](https://github.com/agrc/planning-queue/assets/15659642/d58f4746-b8f9-4663-b7b4-a289d7531400)

## Benefit Hypothesis

Upgrade app so that future deployments are not delayed by a major expo SDK upgrade.

## Success

Deployed app at v48+

**Comment by stdavis** [comment]
### Sprint 1 Tasks
- [ ] https://github.com/agrc/roadkill-mobile/issues/246

**Comment by stdavis** [comment]
### Sprint 3 Tasks
- [ ] Final post-upgrade testing
- [ ] https://github.com/agrc/roadkill-mobile/issues/286
- [ ] https://github.com/agrc/roadkill-mobile/issues/287
- [ ] https://github.com/agrc/roadkill-mobile/issues/288

**Comment by nathankota** [comment]
### Sprint Next
- [ ] Production build and release to app stores

**Comment by nathankota** [comment]
closing, in favor of #287
