### ISSUE TITLE
Migrate AP&P Field Map to ForgeRock

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#169]
### Benefit

Have identity managed by a SaaS rather than DTS

### Acceptance Criteria

The application can function that same using the forgerock cloud solution

### Notes

> The group planning the pilot for migrating three UDC applications to the FORGEROCK IDENTITY CLOUD, have identified with us to do the AP&P Fieldmap as one of those apps. Shancie Nance will be reaching out to you to discuss this idea with you to verify and, if agreed, to include this in that list. Obviously, that will involve your group in that effort, and our group with anything needed with the interface with O-TRACK.

> _IMPLEMENTATION of the FORGEROCK IDENTITY CLOUD  Phase I completion date is December 15, 2023. During Phase I 6 pilot applications will be migrated to the internal and external test and production tenants using at least these different integration types (OIDC, SAML, Web Agent)._
>
>_During Phase I, the contractor (TriVir) will assist the IAM team in moving from an on-premise ForgeRock Access Management, ForgeRock IDM, and NetIQ Identity Manager solution to ForgeRock Identity Cloud._
>_Here is the list of apps that we are considering for pilot:
Visiting (UDC) OIDC
Power DMS (UtahDOC) SAML
Adult Parole and Probation (UDC) OIDC_

**Comment by steveoh** [comment]
Since we are already using OIDC, this change would primarily consist of a URL change. With apadmin being a custom application, I would expect the hardest parts would be accessing the claims we use and the authorization system for providing access.

**Comment by steveoh** [comment]
### Sprint X Notes

Since we use app profile we are no longer a candidate for the pilot. Probably time to close this or backlog it.

**Comment by nathankota** [comment]
backlogged

**Comment by nathankota** [comment]
closing until this surfaces again from DTS or UDC
