### ISSUE TITLE
Washington County USPS Address Point Update

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#170]
### Benefit
Update USPS data

### Acceptance
Washington Co addresses submitted to the USPS system

**Comment by jacobdadams** [comment]
### Benefit

Update USPS data

### Acceptance

Washington Co addresses submitted to the USPS system

**Comment by mhchou** [comment]
This morning when I checked the County Project's link, it shows that the service is currently unavailable. I am not sure if it's a temporary service downtime, the tool is no longer available, or if there is a new tool somewhere else. Just leaving my observation here for your information.

**Comment by ZachBeck** [comment]
@mhchou I submitted points for Washington last week. What link were you checking out?

**Comment by mhchou** [comment]
Sorry, Zach. I was talking with Greg on the USPS's County Project. https://postalpro.usps.com/address-quality/county-project
And it seems to work now! Disregard my previous comment.

**Comment by ZachBeck** [comment]
No worries @mhchou, I'm new to the USPS stuff and wasn't sure if I was missing something. We'll see what the USPS has to say.

**Comment by ZachBeck** [comment]
Waiting for response from USPS

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Triage feedback and contact person in Tennessee

**Comment by ZachBeck** [comment]
Dinged USPS, now waiting for a response.

**Comment by ZachBeck** [comment]
USPS is updating their addresses.
