### ISSUE TITLE
DPU - Public Utilities map and data rebuild

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#173]
### Benefit
- Critically needed data updates for several layers
- Migrate from AGOL Web AppBuilder app, which will no longer be supported by Esri after July 1, 2024

### Acceptance Criteria
- Updated data sets for 
  - Rural telecom
  - Natural gas service areas (approximate)
  - Electric service areas
- Instant App, ExB or similar to replace the features and functionality of the [Utah Public Utilities app](https://utah.maps.arcgis.com/apps/Viewer/index.html?appid=573dfdb6220d4fada6d833def633b866)

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] Meet with DPU to discuss data update coordination with utility providers
- [ ] Reacquaint with existing data and app and start considering new app alternatives

**Comment by nathankota** [comment]
### Sprint 2
- [ ] Compare [URTA data from Feb. 2022](https://drive.google.com/drive/folders/1OiRNeBp7PuYzcVd_-FRBBp_Q7pnVYA8c) with the current [URTA web map](https://urta.org/urta-map/), and the [UGRC Rural Telecom Boundaries](https://opendata.gis.utah.gov/datasets/utah-rural-telecom-boundaries/explore) 
- [ ] Continue to work on obtaining electrical and natural gas service areas

**Comment by nathankota** [comment]
### Sprint 2 Notes
- Sent PacifiCorp GIS data request on October 17 (cc'd Jana Saba)

**Comment by ZachBeck** [comment]
Started aggregating electric service providers from G:

**Comment by nathankota** [comment]
### Sprint 3
- [ ] Use [URTA data](https://drive.google.com/drive/folders/1OiRNeBp7PuYzcVd_-FRBBp_Q7pnVYA8c) and [FCC study area boundaries](https://www.fcc.gov/reports-research/maps/study-area-boundaries/) to build a new Utah Telecom Boundaries data set to replace [Rural Telecom Boundaries](https://opendata.gis.utah.gov/datasets/utah-rural-telecom-boundaries/explore)
- [ ] Continue aggregating electrical co-op service provider boundaries
- [ ] Continue to work on obtaining electrical and natural gas service areas
  -  [UMPA & UAMPS](https://www.notion.so/Service-Provider-Contacts-11badc406b2e44bfb3266c72a56d6f02)

**Comment by nathankota** [comment]
### Sprint 3 Notes
The natural gas municipal system managers were harder to get in touch with. Zach reached out to the UMPA group. Still waiting for a response from Mike Squires about the UAMPS members.

**Comment by nathankota** [comment]
### Sprint 4
- [ ] Finish rural telecom data set
  - [ ] Porter issues to deprecate rural telecom and introduce Utah telecom
- [ ] Follow-up on natural gas areas, and other pending electrical contacts

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Finish telecom data set
  - [ ] Porter issues to deprecate rural telecom and introduce Utah telecom
  - [ ] Create calendar reminder to check on FCC data in one year
- [ ] Natural gas: final follow-up with Hildale, Nephi  
- [ ] Electrical: final follow-up on pending contacts
- [ ] Finish up map/app and send to Ron and Chris at DPU

#### NOTE:
- Nathan will be in contact with Mike Squires from UAMPS during this sprint

**Comment by nathankota** [comment]
### Q3 Sprint 1 Tasks

**Comment by nathankota** [comment]
### Q3 Sprint 1 Notes
- **2024/01/08** - Sent [new app](https://experience.arcgis.com/template/b41f747c543e4a2abbfe013074e666b5/) to Chris and Ron for testing and feedback

**Comment by ZachBeck** [comment]
### Q3 Sprint 3 Notes

- Waiting for a response to the feedback doc.
- Still trying to figure out a way to link to websites from county/municipality utility lists.

**Comment by ZachBeck** [comment]
New url without 'template'
https://experience.arcgis.com/experience/e9c56c0135084f47920317704b0d3d2c

**Comment by ZachBeck** [comment]
Considered done unless issues found by DPU

**Comment by ZachBeck** [comment]
### Q3 Sprint 4
- [ ]  Decommission old DPU app
