### ISSUE TITLE
DEQ - Spills app SF integration

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#174]
### Benefit
- Rebuild using new [ArcGIS Maps SDK for JS](https://developers.arcgis.com/javascript/latest/), which is replacing [ArcGIS API for JS 3.x](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/)
- SalesForce integration

### Acceptance Criteria
- Spills app rebuilt according to specs and requirements of DEQ
- Mapping app is integrated into DEQ Spills SalesForce

### Notes
- [deq-spills repository](https://github.com/agrc/deq-spills)
- [Some notes](https://docs.google.com/document/d/1twwQIfenv-i4MsCJYrVhd-Nk0F-uW-mNoJ5pIKaA29k/edit) (includes spills widget v2 wishlist items from DEQ)

### Issue Reference
refs:

**Comment by nathankota** [comment]
### DEQ Wishlist
1. Incorporate a couple Enviro layers:
  - Public Water System Facilities
    - Calculate distance to buffered point
    - Return some attribute
  - Ground Water Protection Zone
    - Return some attributed of the spatial data if there’s an intersection with a GWPZ
2. Ability to see the highway mile markers better on the base map, and a wish for railroad mile markers (though the railroads are usually pretty good about giving us coordinates instead of their milepost)

**Comment by stdavis** [comment]
This was completed last week. Barry got back to me this morning and verified that production is working.

**Comment by stdavis** [comment]
We worked with Barry last week to get the current (3.x) app pushed to production and the production salesforce instance pointed at it. I'm not sure if this issue should be closed or if it should stay open to track the rebuild for esri js 4.x, etc.

**Comment by nathankota** [comment]
> We worked with Barry last week to get the current (3.x) app pushed to production and the production salesforce instance pointed at it. I'm not sure if this issue should be closed or if it should stay open to track the rebuild for esri js 4.x, etc.

Let's close this, as I have a Q4 task to sort out a plan for either a 4x rebuild, or a more enterprise SF map integration that could replace the existing map widget
