### ISSUE TITLE
Voting Districts app rebuild

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#175]
### Benefit
- Migrate from AGOL Web AppBuilder app, which will no longer be supported by Esri after July 1, 2024

### Acceptance Criteria
- Instant App, ExB or similar to replace the features and functionality of the [Utah Voting Districts 2022-2032](https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=2ea0582adb374e8b86420b222ccd5f7a)

**Comment by DenisePeterson** [comment]
- [ ] Develop plan for creating voting districts app
- [ ] Create draft voting districts app
- [ ] Review/ edit phase
- [ ] Upon approval, publish

**Comment by DenisePeterson** [comment]
Closed and opened new issue in FY24 - Q4.
