### ISSUE TITLE
Q2 - DABS Compliance updates and support

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#177]
[Compliance App](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=a0e8ef3ea26e4c29b1714e993896bed8)
[DABS Commission App](https://experience.arcgis.com/experience/0c3aa87b41d04274a5d6858d06d5f3f6)
[Update Sheet](https://docs.google.com/spreadsheets/d/1VQu6vMrYhlRB_ku4CCZ4E7rGjfMTM2SdnkmX_eVqj1Y/)

## Benefit
The web applications benefit both the DABS compliance staff to plan licensee visits and answer other spatial questions about licensees; and better enables the DABS commission to make decisions about license applications during their review meetings.

## Acceptance
- Provide monthly [license updates](https://docs.google.com/spreadsheets/d/1VQu6vMrYhlRB_ku4CCZ4E7rGjfMTM2SdnkmX_eVqj1Y/edit#gid=1304966721) to the interactive [Compliance app](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=a0e8ef3ea26e4c29b1714e993896bed8). 
- Support for DABS' use of OpenGov software, including the mostly manual ETL of a master address table (MAT) to work with the OpenGov system

**Comment by rkelson** [comment]
- [ ] Get MAT problem addresses added to the address points
- [ ] Generate new MAT

- [ ] 9/2023 updates complete
- [ ] 10/2023 updates complete
- [ ] 11/2023 updates complete

**Comment by nathankota** [comment]
### Sprint 2 Tasks
- [ ] 9/2023 updates complete

**Comment by nathankota** [comment]
### Sprint 4 Tasks
- [ ] 10/2023 updates complete

**Comment by nathankota** [comment]
### Sprint 6 Tasks
- [ ] 11/2023 updates complete

**Comment by rkelson** [comment]
### Sprint 6 Tasks
- [ ] 11/23 updates complete

**Comment by rkelson** [comment]
Not finding any problems with location updates after the migration from Lic_Number to Rec_Number a few months back
Addresses for addition to our address point layer have been provided to Zach and are getting loaded into SDE
new MAT tables are being provided to DABS after the new address points are added to SDE
New locations are being moved to the new correct address point location when a 'physical address' was used to correlate to the MAT
Updates are complete through November
