### ISSUE TITLE
DEQ - UIC Inventory approval and data sync

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#178]
ref: https://github.com/agrc/planning-queue/issues/42

### Benefit

Get the UIC app closer to production.

### Acceptance Criteria

- Approval workflow finalized and implemented in the app
- Data sync from app to UIC database 
  - API to communicate b/t app and database
  - AR considerations
  - DB version and sync considerations

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] Backlog grooming and new tasks for development towards an MVP (@nathankota)  
- [ ] @nathankota and @steveoh discuss the next steps

**Comment by nathankota** [comment]
### Sprint 2 Tasks
#### [UIC project board on-deck issues](https://github.com/orgs/uic-utah/projects/1/views/2)

- [ ] https://github.com/uic-utah/uic-inventory/issues/270
- [ ] https://github.com/uic-utah/uic-inventory/issues/259
- [ ] https://github.com/uic-utah/uic-inventory/issues/199
- [ ] https://github.com/uic-utah/uic-inventory/issues/266
- [ ] https://github.com/uic-utah/uic-inventory/issues/267
- [ ] https://github.com/uic-utah/uic-inventory/issues/269
- [ ] https://github.com/uic-utah/uic-inventory/issues/262
- [ ] https://github.com/uic-utah/uic-inventory/issues/273

**Comment by steveoh** [comment]
### Sprint 3 Notes

All assigned issues were completed that were ready to be completed.

**Comment by nathankota** [comment]
### Sprint 4
- [ ] https://github.com/uic-utah/uic-inventory/issues/199 (profile deletion feature did not work)
- [ ] https://github.com/uic-utah/uic-inventory/issues/273

**Comment by nathankota** [comment]
### Sprint X

- [ ] https://github.com/uic-utah/uic-inventory/issues/280
- [ ] https://github.com/uic-utah/uic-inventory/issues/274
- [ ] https://github.com/uic-utah/uic-inventory/issues/279
- [ ] https://github.com/uic-utah/uic-inventory/issues/278
- [ ] https://github.com/uic-utah/uic-inventory/issues/277

**Comment by nathankota** [comment]
### Sprint 5
- [ ] https://github.com/uic-utah/uic-inventory/issues/273

**Comment by nathankota** [comment]
### Sprint 6

- [ ] https://github.com/uic-utah/uic-inventory/issues/283
- [x] https://github.com/uic-utah/uic-inventory/issues/199
- [ ] https://github.com/uic-utah/uic-inventory/issues/273
- [ ] https://github.com/uic-utah/uic-inventory/issues/282
- [ ] https://github.com/uic-utah/uic-inventory/issues/275
- [ ] https://github.com/uic-utah/uic-inventory/issues/276
- [x] Schedule archer package with Trevor Keller https://github.com/uic-utah/uic-inventory/issues/286

**Comment by nathankota** [comment]
### Sprint Next
- [ ] Finalize https://github.com/uic-utah/uic-inventory/issues/273
- [ ] https://github.com/uic-utah/uic-inventory/issues/282
- [ ] https://github.com/uic-utah/uic-inventory/issues/275
- [ ] https://github.com/uic-utah/uic-inventory/issues/276

**Comment by steveoh** [comment]
## Sprint 6 Notes

12/14 - 5:15 

- The inventory download report is complete. Awaiting feedback.

**Comment by nathankota** [comment]
moving forward in Q3 with #306 , #307 , #308
