### ISSUE TITLE
DHHS Health Care Facilities data updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#181]
## Benefit Hypothesis
Up to date health care facilities with an update schedule and process in place.

## Acceptance Criteria
Regularly updated health care facilities available in the SGID.

Ref:
  - https://github.com/agrc/porter/issues/256
  - https://github.com/agrc/porter/issues/257

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] **October 11:** Follow-up with DHHS Licensing and Background Checks about Health Facilities data

**Comment by nathankota** [comment]
### Sprint 1 Notes
#### October 11th
- email sent to Chris Turner and Nichole Mosteller

**Comment by nathankota** [comment]
### Sprint 4 
- [ ] Check in with Chris Turner again

**Comment by nathankota** [comment]
closing, in favor of #305

**Comment by nathankota** [comment]
### Q3 Sprint 5 Notes
Heard back from Chris Turner that they completed the migration for licensed facilities for both Health and Human Services. There is a [google sheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vT8pLW5yVrV9EY811pE3leFw9u65FtXkMaADaYYdBi0zpjAhrIhaGDQpdQA-jPn8D07DxStjKcWXUcF/pubhtml?gid=2081239427&single=true) available that updates regularly, and is accessible from the [Licensing and Background Checks website](https://dlbc.utah.gov/home/office-of-licensing/).
![image](https://github.com/agrc/planning-queue/assets/15659642/3402fa25-37e4-4fdf-aff2-afc7dd7b0f37)

**Comment by ZachBeck** [comment]
Facilities have been geocoded and bad addresses returned to Health for review.

**Comment by ZachBeck** [comment]
Loaded feature class into sde, need to follow up with the remaining porter stuff. Will be ongoing in FY25 Q1.

**Comment by nathankota** [comment]
FY25 Q1, ref: #426
