### ISSUE TITLE
Q2 WFRC app enhancements and support

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#182]
### Benefit
Support and enhance the apps UGRC has built for WFRC, including:
- [Wasatch Choice](https://github.com/agrc/wfrc-wasatch-choice)
- [RTP Projects](https://github.com/agrc/wfrc-rtp-projects)
- [WAB Widgets](https://github.com/agrc/wfrc-wab-widgets)

### Acceptance
Balance specific enhancement and support request with necessary app maintenance, and among all the other PI objectives.

**Comment by nathankota** [comment]
### Task 
- [ ] https://github.com/agrc/wfrc-wasatch-choice/issues/256

**Comment by stdavis** [comment]
@nathankota What do you think about pushing this up to Q1 sprint 6 uncommitted? I wonder if I should plan on hitting this if the spills bandaid finishes up.

**Comment by nathankota** [comment]
@stdavis I put this in #36 and reopened it. If you don't get to it we'll need to remember to bring it into the Q2 objective.
>What do you think about pushing this up to Q1 sprint 6 uncommitted? I wonder if I should plan on hitting this if the spills bandaid finishes up.
