### ISSUE TITLE
PSAP 911 data standardization

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#184]
## Benefit Hypothesis

- UGRC will lead an effort to standardize the data that is used in the PSAPs across the state. 

## Acceptance Criteria

- UGRC will establish a working committee within GISAC with key players to begin the conversations of what standardized 911 PSAP data will look like. 
- The establishment of quarlty meetings.

### Issue Reference

refs #224

**Comment by gregbunce** [comment]
- [ ] gather key players' names and emails
- [ ] set up quarterly meetings
- [ ] establish committee charter and goals

**Comment by gregbunce** [comment]
Sprint 1

- [ ] Join the APCO committee working on data standardization for PSAP data.
- [ ] Set up quarterly meetings under the GISAC umbrella to better understand the existing landscape of PSAP data and schemas.

**Comment by gregbunce** [comment]
hank joined apco and is set up in the work group.

**Comment by mhchou** [comment]
Set up a date in Q3 to discuss a plan with @gregbunce and @mhchou

**Comment by mhchou** [comment]
### Sprint 2 Notes

Started recruiting potential GISAC candidates. Currently, we have interests from Davis County and Layton City.

**Comment by gregbunce** [comment]
see [related feature](https://github.com/agrc/planning-queue/issues/224)

**Comment by gregbunce** [comment]
Hank attended the G5 conference and made some connections.

**Comment by gregbunce** [comment]
- [ ] Set up quarterly meetings under the GISAC umbrella to better understand the existing landscape of PSAP data and schemas.

**Comment by gregbunce** [comment]
@mhchou do you think there is value in us setting up a quarterly meeting with some of the psaps to collaborate on a standardized schema? Are we there yet or are we getting out in front of ourselves?

**Comment by gregbunce** [comment]
@hank let's make this a feature for you in Q3, to set up a quarterly meeting with the willing psaps. i'll work with you on this one.
