### ISSUE TITLE
UDOT - ALRS migration to ArcGIS Pro Services

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#185]
> The UDOT ALRS services are being updated in the next month or so from arcmap to arcpro services. I don't understand the changes that will come from that migration but Corey mentioned there will be a dev instance for us to test against. (We need to) make some time to plan for any required changes. The milepost endpoints proxy to their ALRS, so any required migrations for those two endpoints.

**Comment by steveoh** [comment]
I have updated the cloud api and kelli bacon is going to test. the arcmap services will be shut down in a few weeks.

**Comment by nathankota** [comment]
https://github.com/agrc/api.mapserv.utah.gov/pull/242
