### ISSUE TITLE
Housing Unit Inventory - Washington County/St. George

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#19]
As described by @jacobdadams...

### Statement of Need/Objective
The housing unit inventory project will create a dataset that enables state and local leaders to evaluate the type (broad categories), unit count, density, size, year built, and assessed value of housing for analyzed areas. The base geographic unit is either individual parcels or, for condos or other developments with commonly-owned areas, the aggregation of all the participating parcels.

## Benefit Hypothesis
The first PI will be focused on Washington County, with hopes that the script will be modularized to enable somewhat easier re-use for other counties' parcel and address point datasets.

## Acceptance Criteria
A dataset with the same schema as the existing, WFRC-created [Housing Unit Inventory](https://opendata.gis.utah.gov/datasets/utah-housing-unit-inventory/) dataset in the SGID, which will then be appended into the SGID dataset. This dataset should account for all the housing in Washington County.

**Comment by jacobdadams** [comment]
Doesn't look like I can edit the issue, so here's my take on these items.

**PI Benefit Hypothesis**
The housing unit inventory project will create a dataset that enables state and local leaders to evaluate the type (broad categories), unit count, density, size, year built, and assessed value of housing for analyzed areas. The base geographic unit is either individual parcels or, for condos or other developments with commonly-owned areas, the aggregation of all the participating parcels.

The first PI will be focused on Washington County, with hopes that the script will be modularized to enable somewhat easier re-use for other counties' parcel and address point datasets.

**Acceptance Criteria**
A dataset with the same schema as the existing, WFRC-created [Housing Unit Inventory](https://opendata.gis.utah.gov/datasets/utah-housing-unit-inventory/) dataset in the SGID, which will then be appended into the SGID dataset. This dataset should account for all the housing in Washington County.

**Comment by jacobdadams** [comment]
### Q3 Sprint 1

- [ ] Finalize OUGs
- [ ] Scriptify prep notebook

**Comment by nathankota** [comment]
### Q3 Sprint 2
- [ ] Complete: Copy and modify davis county script to analyze WashCo

**Comment by jacobdadams** [comment]
Finito Bandito
