### ISSUE TITLE
FFSL - FBS Integration (deprecation)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#196]
ref: #63 and [FBS Integration repo](https://github.com/agrc/fire-business)

### Benefit
Upgraded/rebuilt map integration with the FFSL FBS system before the ArcGIS 3x API is retired. No downtime or lack of service from the map integration.

### Acceptance Criteria
- Rebuild using new [ArcGIS Maps SDK for JS](https://developers.arcgis.com/javascript/latest/), which is replacing [ArcGIS API for JS 3.x](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/)
- Integrate with Fire Business System

**Comment by nathankota** [comment]
### Sprint 1 Task
- [ ] Meet with FFSL to see how they use the integration and if there are any new use cases they have for a rebuild
- [ ] Come up with an estimate and provide it to FFSL
- [ ] Draft SBA

**Comment by nathankota** [comment]
### Sprint 1 Notes
- @nathankota sent a reminder to Tom Thompson to check in with the vendors about the three function of the app that UGRC is currently providing, and whether or not we need to continue to support them
  - area calculation
  - image display
  - zip file to graphic for fire risk map to display

**Comment by nathankota** [comment]
### Sprint 2 Tasks
- [ ] Follow up again with Tom (@nathankota)

**Comment by nathankota** [comment]
### Sprint X Task
https://github.com/agrc/porter/issues/278

**Comment by steveoh** [comment]
closing as completed in sprint 3
