### ISSUE TITLE
DEQ - Enviro rebuild Q2

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#203]
## Benefit Hypothesis
Pay down years worth of technical debt and increase the longevity of the app with a nearly-complete rebuild. 

## Acceptance Criteria
- Near-production ready version of the rebuilt app at parity or parity+ with the current app.
- Client testing and validation

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] [v2.0.0-19](https://github.com/agrc/deq-enviro/releases) testing and validation (see GitHub issues in [Validate (todo)](https://github.com/orgs/agrc/projects/10))

**Comment by nathankota** [comment]
### Sprint 2 Tasks
- [ ] https://github.com/agrc/deq-enviro/issues/577

**Comment by stdavis** [comment]
Not much was done during Sprint 2 with this objective. The portal install took the place of this.

**Comment by nathankota** [comment]
Sprint 4 & 5 Tasks
- [ ] Finish up https://github.com/agrc/deq-enviro/issues/563
- [ ] Pass to DEQ for [testing and feedback](https://docs.google.com/spreadsheets/d/1NNenq5MzxdInyWqTNMt4eCrjMOQ-exup3BqWuGiamBA/)
- [ ] https://github.com/agrc/deq-enviro/issues/577

**Comment by nathankota** [comment]
continued via #293
