### ISSUE TITLE
Q2 UGRC - GovOps website alignment

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#204]
### Benefit

Align with GovOps needs

### Acceptance Criteria

gis.utah.gov implements the utah design system and has a better navigation flow

### Docs and Resources

- [GovOps website mockups](https://docs.google.com/document/d/1OAbjtR10m8WTD70abnWiZcyk0tF-2Cc0fm_M8dNxGjo/edit#heading=h.8dmc9v7vrow)
- [UGRC G-drive Folder](https://drive.google.com/drive/folders/17okJ7Qxhtz3ts0bs-_onDcO180CVxXqW)
- [Website committee meeting artifacts](https://drive.google.com/drive/folders/1fQWNjnCnhF2Hb8Sa3fwZAbtDl9k8WnhH)
- [Content Strategy - Workflow & Process](https://docs.google.com/document/d/1yBZ5l4HtmLfByNNi3j5wB7Mp1tXI5Rnurpyy-thJp_M/edit)
- [Milestone sheet](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao/edit)
- [Lucid diagram](https://lucid.app/lucidspark/df1452f4-4a93-4073-ae2c-649473e11776/edit?viewport_loc=-2335%2C-2408%2C11486%2C8037%2C0_0&invitationId=inv_0cef03fc-8ede-45a7-9880-0d399ad75cd8)

**Comment by nathankota** [comment]
### Sprint 1 Task
- [ ] Sitemap

**Comment by steveoh** [comment]
### Sprint X Tasks

- [x] Brainstorm pillars
- [ ] Walk contractor through website themes and goals
- [ ] Next steps?

**Comment by nathankota** [comment]
Accidentally hid the notes comment above:
### Sprint 1 Notes (Steve)

**Sept, 20 7:09pm**

- Sitemap and readme document placed in DTS shared google drive.
- A meeting is setup for the 21st to discuss the project milestones since they don't all apply to UGRC
- Our first meeting with the contractor is october 2nd

**Comment by nathankota** [comment]
### Sprint X Tasks ([due 12/1](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao))
- [ ] Content consultation with content management strategy consultant
- [ ] Content Cleanup

**Comment by nathankota** [comment]
### Sprint X Tasks ([due 12/29](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao))
- [ ] Content draft review
- [ ] Sign-off on mocks

**Comment by nathankota** [comment]
### Sprint X Tasks ([due 12/1](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao))
- [ ] Content consultation with content management strategy consultant
- [ ] Content Cleanup

### Sprint X Tasks ([due 12/1](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao))
- [ ] Division mockup complete
- [ ] Custom code requirements
- [ ] 
### Sprint X Tasks ([due 12/29](https://docs.google.com/spreadsheets/d/1x37bn_nyayPj_SiHahTy7nrUCbL4FzIHJ6bZrDFzsao))
- [ ] Content draft review
- [ ] Sign-off on mocks

**Comment by steveoh** [comment]
### Sprint 4 notes

1. deleted old blog posts via https://github.com/agrc/gis.utah.gov/pull/2403
2. sorted the rest via https://docs.google.com/spreadsheets/d/12GBuHLsfshgvORHmtczdY-OqmOWVEZbM_7SqpzjblYE/edit#gid=0

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Consult with Matt about next steps and [his thoughts](https://github.com/agrc/agency-website/tree/feat/matts-thoughts)

**Comment by nathankota** [comment]
continued via #310 , #312 , #313
