### ISSUE TITLE
AGOL vector tile base map update and styling

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#205]
### Benefit
Base maps that are easier and faster to maintain and update than traditional raster base maps. Vector tiles also render better and are more portable than current raster base maps.

### Acceptance Criteria
- Finalize a process to update a production tile service in AGOL (Scott and Zach)
- Define strategy for styling tiles
  - Multiple tile packages (vtpk) with different styles vs. single tile package with multiple styles/style files
- Production ready vector tile package in service in AGOL

### Issue Reference

refs #51

**Comment by nathankota** [comment]
@ZachBeck will enter a short benefit statement before the PI meeting on Tuesday, Sept. 26

**Comment by ZachBeck** [comment]
### Sprint 1 Tasks
- [ ] Work on final cartography

**Comment by ZachBeck** [comment]
Cartography updates are ongoing as well as script to update tile services in agol.

**Comment by nathankota** [comment]
@ZachBeck do you have any specific Sprint 3 tasks for this, or maybe push to sprint 4?

**Comment by ZachBeck** [comment]
- [ ] Continue updating annotation
- [ ] Improve road symbology
- [ ] QA/QC to fix label overlaps

**Comment by nathankota** [comment]
### Sprint 4
- [ ] Annotation updates
- [ ] Improve road symbology
- [ ] QA/QC to fix label overlaps 
- [ ] Scripts for updating AGOL tile services
- [ ] Share draft tile service with the office in prep for the meeting on the 27th

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Generate questions for a discussion with Esri
- [ ] Schedule time with Esri vector tile expert!

**Comment by nathankota** [comment]
### Sprint X
- [ ] Improve road symbology
- [ ] Scripts for updating AGOL tile services

**Comment by ZachBeck** [comment]
### Q3 Sprint 1
- [ ] Determine/optimize protobuf file size
- [ ] Meet with Steve and Scott to figure out path forward.

**Comment by steveoh** [comment]
i love this idea. It'd suggest writing an arcpy script to explode the vtpk, traverse over every file and finally write the data to feature classes that we can use to track sizes and investigate what should be optimized.

**Comment by ZachBeck** [comment]
No progress has been made lately. Sprint 1 can more or less be moved to 3.

**Comment by ZachBeck** [comment]
### Q3 Sprint 3
- [ ] Determine/optimize protobuf file size.
- [ ] Meet with Steve and Scott to figure out path forward.
- [ ] Finalize cartography

**Comment by ZachBeck** [comment]
Sprint 3 tasks are ongoing. I have been exploring tile viewing apps (with limited success) to determine the cause of large file sizes in some tiles.

**Comment by ZachBeck** [comment]
moving on to Q4 tasks
