### ISSUE TITLE
Decommission GPS Network Windows server

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#207]
ref: #153

### Benefit
GPS server (grwgps4) is migrated. This objective ensures that the last remnants of the 2012 Windows server is dealt with and deprecated.

### Success
All tasks related to ServiceNow requests to remove the on prem Windows server are completed.

**Comment by nathankota** [comment]
### Sprint 1 Tasks:
- [ ] Decommission grwgps4

**Comment by seanfernandez** [comment]
### Closing Notes

This server was decommissioned successfully

**Comment by seanfernandez** [comment]
- [ ]
