### ISSUE TITLE
Install Trimble Pivot on Windows 2022 TURN development server

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#208]
### Benefit

- The current NevadaGPS Network is setup with an outdated version of Windows Server and needs to be running on the latest version of Trimble Pivot Web version 5.2 to utilize all available satellite constellations.

### Acceptance Criteria 

- Work with DTS Hosting to stand up a new server and bolster it up from the current Dev server (grwgps02gp) to make it capable of running Trimble Pivot. 
- Work with Cloud hosting team and networking to assign correct IP Addresses 
- Submit firewall requests for all necessary ports needed for operations including communication with users and database
- configure Trimble Pivot Web with public facing URL nevadagps.dev.utah.gov 
- configure internal inetpub files to alter the look and feel of the website

**Comment by seanfernandez** [comment]
Benefit -
The current NevadaGPS Network is setup with an outdated coordinate frame NAD83/94 (HARN) which is not compatible with current NGS coordinates, and by configuring a new server using NAD83 (2011) coordinates the GPS network will be compatible with todays equipment and software.
Success Criteria -
-Work with DTS Hosting to bolster up the current Dev server (grwgps02gp) to make it capable of running Trimble Pivot. 
-Work with Cloud hosting team and networking to assign correct IP Addresses 
-Submit firewall requests for all necessary ports needed for operations including communication with users and database
-configure Trimble Pivot Web with public facing URL nevadagps.dev.utah.gov 
-configure internal inetpub files to alter the look and feel of the website

**Comment by steveoh** [comment]
Was this completed @seanfernandez?

**Comment by seanfernandez** [comment]
All of these items have been completed including the firewall rules in place for grwgps02gp and it is now active. nevadagps.dev.utah.gov is also active and available to the public.
