### ISSUE TITLE
Swap Nevada GPS network prod and dev servers

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#209]
### Benefit
The current NevadaGPS Network is setup with an outdated coordinate frame NAD83/94 (HARN) which is not compatible with current NGS coordinates, and by configuring a new server using NAD83 (2011) coordinates the GPS network will be compatible with todays equipment and software.

### Acceptance Criteria

- Generate new NAD83 coordinates using OPUS projects
- Connect all existing stations to new server
- Work with DTS Hosting to bolster up the current Dev server (grwgps02gp) to make it capable of running Trimble Pivot.
- Work with Cloud hosting team and networking to assign correct IP Addresses

**Comment by seanfernandez** [comment]
Benefit -
The current NevadaGPS Network is setup with an outdated coordinate frame NAD83/94 (HARN) which is not compatible with current NGS coordinates, and by configuring a new server using NAD83 (2011) coordinates the GPS network will be compatible with todays equipment and software.
Success Criteria -
-Work with DTS Hosting to bolster up the current Dev server (grwgps02gp) to make it capable of running Trimble Pivot.
-Work with Cloud hosting team and networking to assign correct IP Addresses

**Comment by steveoh** [comment]
Was this completed also?

**Comment by seanfernandez** [comment]
All of these items have been completed and grwgps02gp is now active and being used in a NAD83 (2011) coordinate frame using IP address 165.239.144.7.
