### ISSUE TITLE
Q2 TURN GPS Station Hardware Upgrades

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#210]
## Benefit Hypothesis
UGRC administers a network of high-precision GPS ground control stations. The stations are used by agencies such as UDOT, UTA, UHP for construction, mapping, and surveying property lines. Sixty of these stations are located in Utah and some are at the end of their life cycle and need to be replaced. 

## Acceptance Criteria

Purchase new GPS stations and use the checklists and procedures to upgrade stations at the following locations:
  - Moab
  - La Sal
  - Eastland
  - Blanding
  - Montezuma Creek
  - Wasatch Blvd (Dominion Energy)
  - Rock Springs (Dominion Energy)

**Comment by seanfernandez** [comment]
### Sprint 1-3

- [ ] Moab
- [ ] La Sal
- [ ] Eastland
- [ ] Blanding
- [ ] Montezuma Creek

**Comment by seanfernandez** [comment]
### Sprint 4-6

- [ ] Wasatch Blvd (Dominion Energy)
- [ ] Rock Springs (Dominion Energy)

**Comment by seanfernandez** [comment]
### Sprint 4-6

- [ ] Wasatch Blvd (Dominion Energy)
- [ ] Rock Springs (Dominion Energy)

**Comment by seanfernandez** [comment]
Both of these stations have been updated, but codes are needed to update some of the functions on each receiver which will happen in another quarter.
