### ISSUE TITLE
Q2 TURN and Nevada GPS new station installations

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#211]
## Benefit Hypothesis
UGRC administers a network of high-precision GPS ground control stations. The stations are used by agencies such as UDOT, UTA, UHP for construction, mapping, and surveying property lines. Sixty of these stations are located in Utah and some are at the end of their life cycle and need to be replaced. Adding new stations densifies coverage and provides redundancy to make the network solution more robust ,in case of outages.

## Acceptance Criteria
Install and setup new stations using the checklists and procedures at the following locations:
  - Mexican Hat
  - ...

**Comment by seanfernandez** [comment]
### Sprint 3 Notes

Completed Install
