### ISSUE TITLE
MRRC

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#212]

**Comment by nathankota** [comment]
I'm not sure what this one is, but it ended up in FY24 Q3. Sean, will you please use [the template](https://github.com/agrc/planning-queue/issues/new/choosehttps://github.com/agrc/planning-queue/issues/new/choose) to create a new feature/objective for MRRC in Q3, so it has all the components?

**Comment by steveoh** [comment]
ping @seanfernandez

**Comment by nathankota** [comment]
> ping @seanfernandez 

oops! meant to do that and missed it...thanks!
