### ISSUE TITLE
Install ArcGIS Enterprise Portal

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#213]
### Statement of Need/Objective
ArcGIS Enterprise Portal is required to coordinate with BLM and SITLA to update and maintain the BLM PLSS fabric, within the Esri parcel fabric model.  Additionally, Enterprise will be used to improve collaboration with counties and other local governments around data aggregation workflows including, but not limited to, roads centerlines, voting-related data, and so forth. The project goal is implementation of ArcGIS Enterprise/Portal within the UGRC GCP environment for use with the PLSS (parcel) fabric and branch versioning.

## Benefit Hypothesis
Installation of Enterprise Portal in the cloud to enable the plss fabric and other use cases.

## Acceptance Criteria
- Finish last couple/few remaining tasks for setup (see Sprint 1 tasks below)
- Complete 3 day Jumpstart w/Esri to install ArcGIS Enterprise Portal installation in GCP
- Acceptance testing/validation of the complete Enterprise Portal implementation

**Comment by nathankota** [comment]
### Sprint #114 
####Follow these in preparation for the Jumpstart:
- SAML discovery INC1892877
- Antivirus disable request INC1892915

**Comment by nathankota** [comment]
### Sprint 2 
- [ ] Jumpstart w/Esri to install Enterprise Portal

**Comment by nathankota** [comment]
Installation completed. "Knowledge transfer" docs to be sent by Esri. Well done @MichaelAGRC, @steveoh, @stdavis!

**Comment by steveoh** [comment]
this seems king crab burger worthy eh mr @brigsz

**Comment by brigsz** [comment]
Ha! yah, we need to work out something!  Thanks for all the effort @MichaelAGRC @steveoh @nathankota
