### ISSUE TITLE
Vector tile base maps on Discover

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#215]
### Benefit

- Utilize the latest technology for providing base map services
- Remove the necessity to maintain both raster and vector tile versions of the base maps

### Success

- We are hoping for a seamless transition from the raster to the vector tile base maps for our users

**Comment by nathankota** [comment]
In Q1 Sprint 5 Zach:

> Sent Sanborn vector tile packages to test hosting on Discover.

**Comment by rkelson** [comment]
Received from AppGeo 10/2/2023:
`An update on this – the testing went well, and we feel that Giza can indeed be enhanced to have this additional capability.`

**Comment by nathankota** [comment]
@rkelson @ZachBeck what are the next steps/tasks?

**Comment by ZachBeck** [comment]
I'll most likely be out of town when app geo can meet, but I think the next step is to view the test tiles that I sent them in Discover.

**Comment by rkelson** [comment]
Met with appgeo today and they showed us VTs from Giza in Pro. They need to push an update to discover that will enable user account to now be associated with endpoint that can consume the VTs stored in GCP as WMTS

**Comment by rkelson** [comment]
AppGeo has a solution documented in the email below but folks seem to be leaning toward AGOL hosed basemaps:
https://mail.google.com/mail/u/0/#search/vector/KtbxLzGDXQbqjdLKJXgdgTZcPjvjWblWLB

**Comment by nathankota** [comment]
### Sprint 4
- [ ] group meeting on Nov. 27th

**Comment by rkelson** [comment]
We are leaning toward having the new VT base maps hosted in AGOL. They could also be provided through Discover.
