### ISSUE TITLE
Q2 UGRC API

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#217]
### Benefit

Migrate the self service website to the cloud and improve the experience for developers to manage their api keys

### Acceptance Criteria

Users can perform all the same actions as the existing self service website plus claim their legacy account keys

### Resources

- [UGRC API dev site](https://ut-dts-agrc-web-api-dev.web.app/)
- [2023 UGRC API Updates](https://steve-gourley.notion.site/2023-UGRC-API-Update-c6ba5bd6858f4568b03007989890ccc5)

**From Kelli**

> We have published a new service for our LRS. 
> https://roads.udot.utah.gov/server/rest/services/LrsEnabled/Read_Only_Public_LRS_Routes/MapServer/exts/LRServer/networkLayers/1

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] Regroup and come up with some next steps

**Comment by nathankota** [comment]
### Sprint 2 Tasks
- [x] update and remaining tasks documentation
- [ ] define next priorities

**Comment by nathankota** [comment]
### Sprint 3 Tasks
- [ ] Review street and zone geocoding (_It's shape will be used as a template for the other six endpoints that require documentation._

**Comment by nathankota** [comment]
### Sprint 4
- [ ] Review street and zone geocoding documentation (_It's shape will be used as a template for the other six endpoints that require documentation._

**Comment by nathankota** [comment]
### Sprint 4

- Write street and zone geocoding documentation (_It's shape will be used as a template for the other six endpoints that require documentation._
- [ ] milepost
- [ ] reverse geocode
- [ ] reverse milepost

**Comment by steveoh** [comment]
### Sprint 4 Notes

- migrated the docs astro template to starlight and wrote the remaining 3 endpoint docs
- published a production api build with the new roads and highway url

If we wanted to be more complete, I would write the metadata/info endpoints and document them as well. So far they have been skipped.

**Comment by steveoh** [comment]
### Sprint Next

- [ ] create metadata endpoints feature class names and feature class attributes
- [ ] document those endpoints
- [] brainstorm a simple playground to demo the api

**Comment by nathankota** [comment]
next quarter's objectives in #309
