### ISSUE TITLE
Complete preparation for install of ArcGIS Enterprise Portal in GCP

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#22]
### Statement of Need/Objective
ArcGIS Enterprise Portal is required to coordinate with BLM and SITLA to update and maintain the BLM PLSS fabric, within the Esri parcel fabric model.  Additionally, Enterprise will be used to improve collaboration with counties and other local governments around data aggregation workflows including, but not limited to, roads centerlines, voting-related data, and so forth. The project goal is implementation of ArcGIS Enterprise/Portal within the UGRC GCP environment for use with the PLSS (parcel) fabric and branch versioning.

## Benefit Hypothesis
Installation of Enterprise Portal in the cloud to enable the plss fabric and other use cases.

## Acceptance Criteria
- Necessary licensing obtained
- Review and complete Jumpstart docs
- Meet internally to decide on hardware/architecture (distributed is preferred/advised)
- Schedule and participate in Esri Jump Start for ArcGIS Enterprise Portal installation in GCP
- Acceptance testing/validation of the complete Enterprise Portal implementation

**Comment by nathankota** [comment]
## Future Features
- Create branch versions
- Load data 
  - Ref: #24 (PLSS) 
  - Roads
- Connect parcel fabric to SITLA and BLM's process 
- Test the successful editing of road centerlines with one of the stewards (WFRC, Moab City, Grand County)

**Comment by nathankota** [comment]
### Sprint 1 Tasks

- [ ] Meet and complete [system diagram](https://lucid.app/lucidchart/b0a70ec1-85a2-49fb-8244-1abb167db74b/edit?viewport_loc=-446%2C-106%2C2859%2C1445%2ChmwzQ.qPy8Cz&invitationId=inv_05d5f0e0-e95e-408b-806a-65975d69ad90) and submit to Esri (@MichaelAGRC, @steveoh)
- [ ] Request version 11.1 license to replace the existing 10.9.1 license we asked for initially (@nathankota)

**Comment by nathankota** [comment]
### Sprint 2 Tasks (DRAFT)
- [ ] Firewall requests
- [ ] GCP infrastructure setup
- [ ] ...

**Comment by nathankota** [comment]
### Upcoming Sprints...
- [ ] Schedule Jumpstart
- [ ] ...

**Comment by steveoh** [comment]
### Sprint 2 Updates

- I terraformed the dev portal infrastructure and asked @MichaelAGRC to test the ports and review the specs
- I recommend installing an enterprise geodatabase into the cloud sql we stood up to see how it goes (@MichaelAGRC)
- I created an incident with cloud core to join it to the utah ad that is getting assigned to the wrong groups and should sort it self out soon.

**Comment by nathankota** [comment]
### Sprint 3 Tasks
- [ ] validate ports and review specs of dev infrastructure
- [ ] license and install enterprise gdb in existing cloud sql and validate it works as expected
- [ ]  obtain cert

**Comment by steveoh** [comment]
### Sprint 3 updates

**Aug 9**

- Switching the dev project to use the shared vpc to join the utah domain is going to cause some pain
  1. We will no longer own the project with the firewall rules and will need to go through the standard dts firewall process and wait the normal amount of time for each rule to be approved and implemented.
  2. Since the firewalls are the biggest unknown and will take the most time to update, we may have issues with the kick start timeline. @MichaelAGRC is the kick start 3 consecutive days or can it be split up to allow for dts processes to run their course?
  3. The current firewall testing cannot continue since I have started to remove the rules to migrate to the shared vpc project. Installing SDE can continue but will most likely require some permission tweaking and a bit of training to gain access to the database.

I believe we can purchase a certificate or have one provisioned prior to the prod infrastructure being completed. We can also reserve the DNS for portal and server.

**Comment by nathankota** [comment]
### Sprint 4 Tasks
- [ ] Consider [ArcGIS Monitor](https://www.esri.com/en-us/arcgis/products/arcgis-monitor/overview). Do we need it?

**Comment by nathankota** [comment]
### Sprint 4 Notes
## August 23
Let's skip Monitor during the initial portal install, and I'll schedule time with Esri to learn more about it in Q2

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Obtain cert [INC1884544](https://utah.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=6b46ace24745b9d0184a874c346d43e1%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)
- [ ]  Work through firewall rejection and validate ports 
- [ ]  Enterprise GDB (SDE) installation
    - Install Pro and Sql Server Mgt Studio on data store machine
    - database credentials in bitwarden (ut-dts-agrc-portal-dev sql)

**Comment by MichaelAGRC** [comment]
### **Sprint 5 Notes:**

Database testing was successful.  Was able to connect from the datastore server using both SSMS and ArcPro.  Was able to create users and assign privileges.  Was also able to create an enterprise geodatabase and add data to it.

**Comment by steveoh** [comment]
### Steve Sprint 5 Notes

**Sept 7 4:42pm Summary**

- The terraform is 99% complete with regard to creating the 3 machines, load balancer, and database. There are a couple of labels I need to add for dts firewalls.
- All DTS firewall rules should exist in the prod and dev shared vpc to join the prod compute vm's to the domain without delay other than their work to install and configure the software.
- The portal machine firewall rules weren't great and I will review and update them with someone from the core cloud team.

### Possible Sprint 6 Tasks

- [ ] create prod project
- [ ] request vpc join
- [ ] request domain join
- [ ] submit firewall rules for portal
- [ ] install db software on datastore
- [ ] put cert on the portal machine? load balancer?
- [ ] put portal installer and licenses on machine
- [ ] put server installer and license on machine
- [ ] put data store installer and license on machine
- [ ] create prod egdb
- [ ] schedule kickoff
- [ ] schedule jumpstart

**Comment by nathankota** [comment]
### Nathan Sprint 5 Notes
#### September 8, 11:00 a.m.
- A cert has been provided via Virtru secure email for arcgisportal.gis.utah.gov, according to INC1884544.
- I see in the tasks above a question about a load balancer cert. I asked Rachel G., who provided the cert, whether we need another for the load balancer. Her response was:
> It depends. Does this load balancer require that you use their CSR? If so, then another certificate needs to be issued. If not, then the same certificate can be used as long as it is for the same "common name". 

@MichaelAGRC, @steveoh any input or guidance you can provide about cert(s) next steps is greatly appreciated.

**Comment by steveoh** [comment]
### Sprint 6 Notes (Steve)

**Sept 20 3:20pm**

Had the kick off. Waiting for the ports from esri to double check firewalls. Our action items are mainly in the following incidents.

- SAML discovery INC1892877
- Antivirus disable request INC1892915

**Comment by nathankota** [comment]
The Jumpstart meeting with Esri is scheduled for October 24-26. We are following the last couple of action items prior to the installation via #213
