### ISSUE TITLE
GISAC subcommittee - Road Centerline standards and best practices

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#224]
## Benefit Hypothesis

- GISAC is the state's GIS advisory council.  Currently, it lacks energy and direction.  Ideally, GISAC is where best practices, standards, and conversations centered around statewide data will take place.

## Acceptance Criteria

- A web-based landing page for GISAC with information on what it is, what the sub committees are, and how to join.

**Comment by gregbunce** [comment]
## Benefit Hypothesis

- GISAC is the state's GIS advisory council.  Currently, it lacks energy and direction.  Ideally, GISAC is where best practices, standards, and conversations centered around statewide data. will happen 

## Acceptance Criteria

**Comment by steveoh** [comment]
There is https://gis.utah.gov/about/gisac/ currently

**Comment by gregbunce** [comment]
Yup, I thought I could take it to the next level. Hoping to provide a more collaborative platform.

**Comment by steveoh** [comment]
What collaboration does hub provide that you need for a landing page?

**Comment by gregbunce** [comment]
Interested parties for a road centerline subcommittee focused on standards and best practices
- Davis Co
- Layton
- UDOT
- Wayne Co
- Grand Co
- UGRC
- WFRC

**Comment by gregbunce** [comment]
## Sprint 3

- [ ] Create first subcommittee meeting in Jan 2024

**Comment by gregbunce** [comment]
i'll keep this alive.  i'm not sure Jan is the right time.  i have a list of key players.  i need to refine our roads best practices doc first (maybe Q3) and our portal data governance doc.  that will give the meeting a few talking points and a starting point for the group.

**Comment by gregbunce** [comment]
progress was made on this.  i'm still refining it.

**Comment by steveoh** [comment]
Are you able to share anything?

**Comment by gregbunce** [comment]
primarily, it's been a handful of discussions to gather support for a path forward with maintaining the roads centerline layer with some of our data stewards in Davis County (Doug Pierce, Cheryl Larson), Grand County (James Murphy), Wayne County (Wanda), UDOT (Kelli), WFRC (Bert and Lilah Rosenfield).  There is interest in working from a single data source (hopefully UGRC Portal) with these stewards and establishing some standards (building upon the ones started [here](https://docs.google.com/document/d/11R2Ht0nbcbyb8t717ot3GBdw8m4DgidiIXpgnOd_y8g/edit)).  

now i need to work out the Portal collaboration piece and clean up the best practices doc.  that will be a good starting point moving forward with them.   I have a few features planned for Q3 that will allow this to move forward.

**Comment by steveoh** [comment]
Are you still planning to update the GISAC website page or build a new hub website?

**Comment by gregbunce** [comment]
that's a piece of it (the branding piece), but i feel like my time is probably better spent elsewhere, at least at the moment. 

a bit more update on the road standards and best practice stuff...
another big hurdle we face is conflating the existing datasets.  that was part of the discussions.  in davis county and utah county they have a lot of siloed datasets that folks are not ready to let go.  city vs county vs 911, then you add our data and UDOT into the mix and it gets complicated quickly.  I've had some conversations with 1Spatial that were promising.  they have a conflation tool that seems pretty good.  Grand is willing to give it a go with us (their data, blm data, and our data).  the goal would be to output one dataset that we all work from.

**Comment by gregbunce** [comment]
there's still a part of me that wonders if UGIC needs to play a larger role in GISAC
