### ISSUE TITLE
UHAF - Utah Homeowner's Assistance Fund App

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#225]
## Benefit Hypothesis
Create an interactive Dashboard for the [Utah Homeowners Assistance Fund](https://homeownersassistance.utah.gov/) to act as a resource for statewide information regarding assistance approved and paid, households assisted, average assistance amounts, etc…

## Acceptance Criteria

**Comment by gregbunce** [comment]
- [ ] tasks
- [ ] tasks

**Comment by gregbunce** [comment]
### Sprint 4 Tasks

- [ ] Plan for data integration into map

**Comment by gregbunce** [comment]
### Sprint 5 Tasks

- [ ] review and revise the beta dashboard

**Comment by DenisePeterson** [comment]
2023-12-05: Greg sent draft app to client for review.

**Comment by gregbunce** [comment]
meeting client on next steps.  for Q3 we're looking at maintenance and support of the application.
