### ISSUE TITLE
DEQ - Spills app rebuild planning

### ISSUE THREAD

**Issue by stdavis** [agrc/planning-queue#226]
### Benefit

We need to determine the requirements and plan for funding for this project.

### Acceptance Criteria

- [ ] A signed SOW.

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] Check-in with DEQ and DTS about progress on the current spills integration
- [ ] Draft SOW for the current spills widget integration into SalesForce

**Comment by nathankota** [comment]
### Sprint 2 Tasks
Continue/carryover tasks from Sprint 1 to
- [ ] Check-in with DEQ and DTS about progress on the current spills integration
- [ ] ~Draft SOW for the current spills widget integration into SalesForce~

**Comment by nathankota** [comment]
Made some progress, but there are things that need to happen before we're ready to estimate and make final plans for a rebuild of the spills app/widget, namely:
- Finalize current widget integration into SalesForce app #174 
- Get some feedback about any changes DEQ wishes to see in the production version of the current widget, in addition to their [wishlist items](https://docs.google.com/document/d/1twwQIfenv-i4MsCJYrVhd-Nk0F-uW-mNoJ5pIKaA29k/)
- Estimate the work and get an agreement going
