### ISSUE TITLE
Understand application record series requirements

### ISSUE THREAD

**Issue by steveoh** [agrc/planning-queue#229]
### Benefit

Transparency for our customers

### Acceptance Criteria

- [x] Identify the applications that do not have a record series
- [ ] Create a record series, that at least describes what we are doing with the data

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] Meeting on the 16th
- [ ] Finish [the form](https://docs.google.com/forms/d/11x0nwfUCtyf_bwdTPx8o7O0mB4QgHtV4dJxJ7gkCRJc/edit) (@brigsz)

**Comment by brigsz** [comment]
Yes, we have a listing now from folks filling out the form.  It is a good start, and maybe everything.  DTS, the Privacy officer and Archives are sorting out a series number

**Comment by nathankota** [comment]
closing, in favor of #251
