### ISSUE TITLE
DWQ - Inland Port change detection

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#25]
https://www.notion.so/DEQ-Change-Detection-a68c23c4c0334b7aab6f5a592355bb58

This potential project is still in discovery. 

Draft SOW:
https://docs.google.com/document/d/1z0AMms6eqAPL8RcfTr1BLmRcbVoWZP_gyoMrC7TgbLc/edit

Possible helpful ArcGIS tool and workflow: 
https://learn.arcgis.com/en/projects/calculate-impervious-surfaces-from-spectral-imagery/

**Comment by rkelson** [comment]
replaced with https://github.com/agrc/planning-queue/issues/278
