### ISSUE TITLE
TURN GPS Support

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#254]
### Benefit

Provide support to TURN GPS Network clients

**Comment by DenisePeterson** [comment]
Ongoing support for TURN GPS Network

**Comment by gregbunce** [comment]
it's been busy with the new bill pay system and customer support (lots of phone calls)

**Comment by steveoh** [comment]
> it's been busy with the new bill pay system and customer support (lots of phone calls)

Are these calls identifying issues with the current application that could be fixed?

**Comment by DenisePeterson** [comment]
> > it's been busy with the new bill pay system and customer support (lots of phone calls)
> 
> Are these calls identifying issues with the current application that could be fixed?

The bulk of calls are about getting help with the new bill pay system. We've had a lot of questions about how to use it to renew, register, and create new accounts. Questions about creating the UtahId, too. I suspect they'll slow down once people have gotten used to it.

**Comment by steveoh** [comment]
What about adding a video demonstrating the process?

**Comment by DenisePeterson** [comment]
Closed and opened new issue for FY24 - Q4.
