### ISSUE TITLE
Q3 Dependabot application dependency updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#255]
### Benefit

UGRC applications have dependencies that are constantly updating to add new features, improve performance, and patch security issues. Keeping applications current with dependencies improves our security posture and allows for easier future enhancements since the amount of breaking changes is smaller and more trivial.

### Acceptance Criteria

- [ ] UGRC application dependencies are current and all known CVE's are patched.

#### Carried forward from, or surfaced in, Q2

- [ ] Consider https://github.com/step-security/harden-runner this quarter or another
- [ ] Revisit the [reactfire npm conflicts](https://github.com/FirebaseExtended/reactfire/pull/594)
- [ ] Some action workflows are not completing since their required checks aren’t running
- [ ] Forklift arcpy + warehouse updates
- [ ] Push swapper to pypi and automate builds https://github.com/agrc/swapper/issues/19
- [ ] https://github.com/agrc/skid/pull/3
- [ ] Migrate to [actions/create-github-app-token](https://github.com/actions/create-github-app-token)
- [ ] Migrate to Artifact Registry
- [ ] Update all functions to nodejs 20 prior to Jan 30, 2024.

### Risks

Container Registry is deprecated. After May 15, 2024, Artifact Registry will host images for the gcr.io domain in projects without previous Container Registry usage.

### Issue Reference

refs #172

**Comment by steveoh** [comment]
This seems like a really good sprint 6 type of task.

**Comment by nathankota** [comment]
now captured in #311
