### ISSUE TITLE
Handle SITLA LandOwnership Service Breaking Changes

### ISSUE THREAD

**Issue by stdavis** [agrc/planning-queue#259]
### Benefit

SITLA switched the URL and lowercased all of the field names. We need to update [everywhere we use this service](https://github.com/search?q=org%3Aagrc+UT_SITLA_Ownership_LandOwnership_WM+NOT+is%3Aarchived+lang%3Ajs+OR+lang%3Ajson&type=code) so that the layer can be drawn on maps and the data can be used in forklift.

### Acceptance Criteria

- [x] All instances of the old service have been updated with the new URL and field names (if applicable).
- [x] Kitchen Sink
- [x] Broadband
- [x] DEQ Spills
- [x] DEQ Enviro
- [x] wfrc-wab-widgets

### Notes

Old URL:

`https://gis.trustlands.utah.gov/server/rest/services/Ownership/UT_SITLA_Ownership_LandOwnership_WM/FeatureServer/0`

New URL:

`https://gis.trustlands.utah.gov/mapping/rest/services/Land_Ownership_WM/FeatureServer/0`

Also, all of the field names have been lowercased:

Old:
![Image](https://github.com/agrc/planning-queue/assets/1326248/6eda4c8e-55fa-4a9f-80a0-2b7bd8f139bc)

New:
![Image](https://github.com/agrc/planning-queue/assets/1326248/dde270f5-5767-43cd-9f7c-9ed6a0b6e06f)

There is some talk of them or us creating a vector tile service but we are not going to wait for that to happen at this point.

### Risks

1. The service changes again
2. A vector tile service is published that we then want to migrate to
3. How long they leave their redirect in place (January 1?)

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 3 Notes
- ...
- ...
- ...
- [blog post](https://gis.utah.gov/sgid-breaking-changes-from-sitla/)

**Comment by stdavis** [comment]
This will be on hold until SITLA gets the vector tiles service published hopefully next month.

**Comment by stdavis** [comment]
SITLA has now published a [vector tile service](https://sitla.maps.arcgis.com/home/item.html?id=ae47fe62692d4761a52942421edd24f2).

**Comment by stdavis** [comment]
Nevermind. That is just another feature service. I hit them up about a vector tiles service.

**Comment by stdavis** [comment]
Here's the new vector tile service (for realzzz this time): https://gis.trustlands.utah.gov/hosting/rest/services/Hosted/Land_Ownership_WM_VectorTile/VectorTileServer

I've confirmed with them that:
- this is the final URL
- it is on the same update scheduled as the feature service (nightly)
- they have no plans to shut off the redirect

**Comment by steveoh** [comment]
@nathankota is this a sprint 2 or 3 thing do you think? Seems like we should get ahead of it?

**Comment by nathankota** [comment]
I put it in Sprint 4 since 
> * they have no plans to shut off the redirect

and we can look at it at the beginning of sprint 3 and see if it fits

**Comment by nathankota** [comment]
### Sprint 1 Notes
- see commits above for apps that have been updated
- others that may need it
  - WRI?

**Comment by nathankota** [comment]
### Sprint 2
- find other apps that need updated

**Comment by stdavis** [comment]
I believe that this is complete.
