### ISSUE TITLE
Broadband - Fall provider updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#26]
## Benefit
Updated broadband provider coverage areas including the technology of transmission and associated advertised upload and download speeds.

## Success
Updated broadband provider coverage areas reflected in the https://broadband.ugrc.utah.gov/

[Trello Board](https://trello.com/b/GrKBquSS/broadband-provider-update)

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] - [ ] provider x
- [ ] provider y

**Comment by gregbunce** [comment]
- [ ] initiate fall broadband data gathering and preparation
- [ ]

**Comment by rkelson** [comment]
There is more residential provider data to update.
Still need to start FCC data

**Comment by rkelson** [comment]
11/14/2023 TDS sent new data
