### ISSUE TITLE
Fish Spring Topo Bathy lidar

### ISSUE THREAD

**Issue by rkelson** [agrc/planning-queue#264]
### Benefit

Take a look at possibly making the topo bathymetric lidar for Fish Springs available for download or simply discoverable. 

C:\_Lidar\FishSprings2022

### Acceptance Criteria

- [ ] 

### Notes

_would this be a new raster app category?_ No

### Issue Reference

refs #

**Comment by steveoh** [comment]
Does make available mean viewable from discover and downloadable from the raster app?

**Comment by rkelson** [comment]
Downloaded project deliverables. The downloads associated with this project total less than 1GB. Planning to add this project to the lidar collections on https://gis.utah.gov/data/elevation-and-terrain/#LiDAR

**Comment by rkelson** [comment]
- [x] review project deliverables
- [ ] zip deliverables and copy to GCS
- [ ] create zip files of reports, shapefiles, and metadata and and copy to GCS
- [ ] get @stdavis to add tile indices to raster app .mxd
- [ ] add extent polygons to lidar extents layer in SDE with show = N
- [ ] change lidar extents value to show = Y when downloads are available
- [ ] create webpage and images
- [ ] test webpage downloads and links
- [ ] test webpage Raster link
- [ ] publish webpage
- [ ] change project status in SDE Lidar Extents and check that [Utah Lidar Coverage App](https://arcg.is/18SWjy) shows project as _Existing_
- [ ] copy project deliverables to LaCie drive

**Comment by rkelson** [comment]
This is all complete
