### ISSUE TITLE
Rewrite WMRC ETL updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#269]
### Benefit

Improve the ETL processes for the WMRC recycling map/app data from google sheets and salesforce, and to calculate the precision rates more efficiently than Arcade expressions in the app.

### Acceptance Criteria

- [x] google sheet ETL (used oil collection data)
- [x] salesforce ETL (solid waste data)
- [x] precision rates calculations

### Notes

Another possible task is to open a GitHub repo for the WMRC project overall, mostly to capture and track issues.

### Issue Reference

refs #221

**Comment by jacobdadams** [comment]
### Sprint 1

- [ ] Get connected to DEQ salesforce sandbox
- [ ] Write Salesforce ETL
    - [ ] Create feature service for summary stats
    - [ ] Calc summary stats
 - [ ] Update skid w/Salesforce ETL

**Comment by jacobdadams** [comment]
Still waiting on Barry Blackington & Tom to get access to their salesforce org

**Comment by steveoh** [comment]
> Still waiting on Barry Blackington & Tom to get access to their salesforce org

Do you know when the last reminder was given to Barry?

**Comment by nathankota** [comment]
### Sprint 4
- ding Barry & Tom

**Comment by nathankota** [comment]
### Sprint 2
- got the app connected
- need to update palletjack to account for REST limitations
- still waiting for access to proper data

**Comment by nathankota** [comment]
### Sprint next
- validate report/queries by comparing extracted data with Stevie's report

**Comment by nathankota** [comment]
### Sprint 5
- [ ] Finalize ETL component
