### ISSUE TITLE
Podcast development

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#273]
### Benefit

UGRC's podcast is an excellent way to communicate the value of geospatial technology in a variety of applications. 

### Acceptance Criteria

Develop comprehensive podcast plan and schedule.

### Notes

This will be an ongoing project.

### Issue Reference

refs #

**Comment by DenisePeterson** [comment]
- [ ] Create podcast episode schedule
- [ ] Explore incorporating video into podcasts (YouTube channel?)
- [ ] Develop and maintain potential guest list

**Comment by gregbunce** [comment]
denise and greg will touch bases (all four) in mid-april to put together the wildlife migration podcast contingent on the website rebuild status.

**Comment by gregbunce** [comment]
we didn't make as much progress on this as we would have liked. we have a potential guest list, and denise and i recorded an episode with Blair from DNR, but a lot of what we wanted to do got back seated due to the website rebuild. we'll attempt to make some progress in Q4. this is the fun stuff!
