### ISSUE TITLE
WMRC Dashboard

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#276]
WMRC = Division of Waste Management and Radiation Control

### Benefit

A dashboard for WMRC staff, legislators, and the general public to get an at-a-glance look at how recycling efforts are going per material and over time.

### Acceptance Criteria

- [x] Functioning dashboard meeting their needs
- [x] Data automation to keep source feature services updated (may be done via the WMRC ETL task #269 )

### Notes

Currently waiting on example data

### Risks

- Limitations of dashboard tools
- Delays in getting data

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- Begin building dashboard

**Comment by nathankota** [comment]
### Sprint 4
- address Stevie's comments

**Comment by nathankota** [comment]
### Sprint Next

> For the pie chart on the Composting panel, can you please change "Other CM" to "Other Compostable Material"?  We don't have the acronym defined anywhere so that change will make it more understandable.

> Oh, same for the materials over time plot below the pie chart.

**Comment by jacobdadams** [comment]
### 25.1.1/2

- [ ] Validation numbers: for each facility, a year over year percent different for each RCDL category, taking into account everything but landfill has the msw modifier.	Each validation run, get statewide y/y, countywide y/y, facilitywide y/y
- [ ] Go live with state numbers
- [ ] dashboard later priority

**Comment by nathankota** [comment]
carried-forward to FY25 Q1

**Comment by jacobdadams** [comment]
### 25.2.2
- [ ] move to common UGRC user in DEQ AGOL org.

**Comment by jacobdadams** [comment]
### 25.1.3

Email 30 July 2024:
- [ ] Add hazardous waste facilities category
- [ ] Change names

**Comment by jacobdadams** [comment]
### 25.1.4

Working on the state metrics back-and-forth with Stevie, also working on wiring up dashboard to new feature services coming from skid.

**Comment by jacobdadams** [comment]
Current draft dashboard: https://utahdeq.maps.arcgis.com/apps/dashboards/f104f8b8120b4234b9ccc36769221e95

**Comment by jacobdadams** [comment]
### 25.1.6

Making last minute changes, pretty close to going live.

**Comment by jacobdadams** [comment]
### 25.2.3

- [x] Update materials recycled logic to ensure totals match what's on the map
