### ISSUE TITLE
DHHS - Newborn Safe Haven Map  

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#277]
### Benefit

A replacement map for the current google-based maps on https://utahsafehaven.org/hospitals/ to direct the public where newborns can be safely surrendered. 

### Acceptance Criteria

- [x] A functioning map that matches or exceeds google's capabilities (directions, pop-up info, searching)
- [x] A possible replacement for the list view as well.
- [x] A ServiceNow UGRC Business Applications record.

### Notes

Most work will probably be done in Q2, but finalizing may be difficult with the holidays.

Current drafts are a whole app that replaces both the list and map along with the search functionality, but it may make more sense to just do a standalone map/list.

Due to the preference for anonymity as a state government program, the Safe Havens app will not be a candidate for a shortened, custom utah.gov url path.

### Risks

- ExB adds a lot more UI fluff than google
- Connecting search, map, and directions is limited; currently requires searching in three different places

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- obtain feedback

**Comment by nathankota** [comment]
### Sprint 3
- Feedback meeting w/Luisa and Josie

**Comment by nathankota** [comment]
### Sprint 3
- put a few hours into this

**Comment by jacobdadams** [comment]
### Sprint 6

- [x] Create new draft with full re-imagining of the process (both mobile and desktop)

**Comment by nathankota** [comment]
@jacobdadams, do you think the new draft is ready to share with the DHHS team?

**Comment by jacobdadams** [comment]
Yes, I shared it in an email to Louisa Hansen on Wed June 19th

**Comment by nathankota** [comment]
### FY25 Q1 Sprint 1 Notes

#### Latest feedback is:

> I mostly used my phone since that’s what I assume most people will use. Often when I plugged in the city/town name, a few options came up on a drop-down menu, but it did not let me click on the actual town. That being said, it still worked. When I clicked on Directions, it gave me directions from my home to the hospital, instead of directions from the city/town I searched to the hospital. I did not get the closest hospital to some of the rural locations I checked, such as Wendover and Boulder. Torrey worked.

**Comment by jacobdadams** [comment]
### 25.1.2

Responded to their feedback with all possible options. We've exhausted the limits of ExB. Waiting on them to respond and integrate into their website.

**Comment by jacobdadams** [comment]
### 25.1.3

Sent email with both iframe example and shortened arcgis link. Our work here is pretty much done.

@nathankota, will you add the ServiceNow Business application thingee?

**Comment by steveoh** [comment]
Should we go the [porter](https://github.com/agrc/porter/issues/new?assignees=%40nathankota&labels=introduction%2C+porter&projects=&template=5-introduce-application.md&title=Introduce+%3Capplication%3E) route?

**Comment by nathankota** [comment]
https://github.com/agrc/porter/issues/338

**Comment by jacobdadams** [comment]
### 25.1.5

They've got it integrated on their site. They had some questions about scrolling, but haven't responded to my emails yet, so I'm gonna close this. It's substantially complete, and any future questions should be quick.
