### ISSUE TITLE
Fleet - Fuel and EV sites app rebuild

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#28]
### Benefit
- Update data flow from source to AGOL
- Migrate from AGOL Web AppBuilder app, which will no longer be supported by Esri after July 1, 2024

### Acceptance Criteria
- Instant App, ExB or similar to replace the features and functionality of the [State Gas Card Fuel Sites](https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=ea4add98d64e4cfaa702a243f1ac6efd)
~- Include EV charging station data, if possible~
- Mobile layout
~- MAYBE: A [Palletjack](https://github.com/agrc/palletjack) [skid](https://github.com/agrc/skid) to automate ongoing updates~

### To Do
- [x] Edit splash screen on old app to provide link to new app and deprecation notice
- [x] Deprecate Society.StateFuelSites with [Porter Issue 325](https://github.com/agrc/porter/issues/325)

**Comment by nathankota** [comment]
### FY24 - Q3 NOTES
- App maintenance and some data updates occurred

**Comment by rkelson** [comment]
Provided Karen with a draft desktop ExB application. She is going to show it to her group 5/28 and get me some feedback. After all necessary changes are made to the desktop version a mobile version of the app will be created.

**Comment by steveoh** [comment]
> After all necessary changes are made to the desktop version a mobile version of the app will be created.

Are there specific reasons the desktop version cannot also cover the mobile needs? I ask because less is more and being able to do this is one of the key features of their marketing on https://developers.arcgis.com/experience-builder/guide/

**Comment by rkelson** [comment]
The desktop version will be used but some elements need to be adjusted for the mobile display. I should have said _mobile display_ vs. _mobile version_. I am aware that this is a key feature of ExB.

**Comment by steveoh** [comment]
Ok yeah version made me think two separate apps which we don't want to be doing. Thanks for clarifying.

**Comment by rkelson** [comment]
6/3 - Worked on the mobile display and requested that Karen take a look at the app on a desktop and a mobile device and to let me know if she sees any problems

**Comment by rkelson** [comment]
Karen is pleased with the new app. I provided her the URL to use for the new app on their website. When their website has been updated to point to the new app I will edit the splash screen on the old app to direct folks to the new app.

**Comment by rkelson** [comment]
new application URL has been added to their website. Old app now has a splash screen stating this is the old app and provides a link to the new app.

I will submit the porter issue to remove  Society.StateFuelSites from the Internal database while maintaining it in AGOL in the near future.

**Comment by rkelson** [comment]
Submitted a Porter issue to deprecate State Fuel Sites from Internal while maintaining it in AGOL. I have a feeling this will take some time to sort out.

Sounds like we also need to come up with a strategy to backup AGOL only layers.

**Comment by rkelson** [comment]
App migration is complete, customer is happy, and the layer has been removed from the Internal SGID
