### ISSUE TITLE
Build test collaboration database/datastore for Portal

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#283]
### Benefit

This will allow UGRC to better collaborate with the data stewards as well as our data contributors - allowing for more efficient, timely data updates. 

There are still some unknowns as to how this will work so we need to build a test DB and begin testing with a willing party (WFRC) to work out the details and kinks.

### Acceptance Criteria

- [x] create test db
- [x] create appropriate collaboration group
~- [ ] load utrans roads~
- [x] load utrans trails and pathways

### Notes

Let's begin testing with WFRC on 'roads' and 'trails and pathways'

#### Greg

- none: we're testing

#### Steve

- tests can turn into production, so let's be careful here.
- the governance hasn't been solidified yet

### Issue Reference

refs #

**Comment by gregbunce** [comment]
we made progress on the governance doc today. it's a living doc so we will continue to refine it as we venture forward and learn.  currently, we are at a point where we can begin some initial testing.  we're scheduled to do so on 1/16/2024.

**Comment by MichaelAGRC** [comment]
**Q3 Sprint 2**

- [ ] Created transportation database 
- [ ] Created transadmin user
- [ ] Loaded Trails data
- [ ] Registered Trails datastore with server
- [ ] Created Trails Workgroup group

Data should be ready to test editing using Pro.  Will require users to be members of the Trails Workgroup.

**Comment by MichaelAGRC** [comment]
**Q3 Sprint 2**

I've been testing setting up a feature service for branch editing in Portal.  I've been having mixed success.  Currently I have a service called trails that uses a registered dataservice called trailsdataservice to access a feature service in the enterprise-geodatabase called trail_paths.  The dataservice uses a database connection as transadmin to the transportation database to access the trail_paths feature service.  The feature service is owned by me.  Even if I create a group and add the trails feature service to the group, I get a vague error about not being the owner, or not having permission.  I've added myself to the database and explicitly granted myself edit access, and it didn't seem to matter.
I'm totally open to having others log into our portal environment and giving it a go.  Everyone should be able to log into portal using their UMD login.  Passwords are all stored in bitwarden.  We have a meeting tomorrow at 11am to take a look at it.  Feel free to log in ahead of time and look around.  Kick the tires a bit and see what errors you can come up with.

**Comment by gregbunce** [comment]
I'm logged in but I'm very limited in what I can do with my user role.  
![image](https://github.com/agrc/planning-queue/assets/16906316/871fd083-1e16-405c-8076-8f56fc47db4e)

**Comment by nathankota** [comment]
### Sprint 3
- [ ] Connect with Esri about branch versioning set up and editing challenges

**Comment by MichaelAGRC** [comment]
**Sprint 4 Notes**

Have meeting scheduled with Esri (Will and Dave) on Tuesday, February 20th at 11am.  Greg has been invited as well to cover some collaboration questions in tandem with the branch versioning assistance.

**Comment by gregbunce** [comment]
we have the test data in place and collaborative editing working between our Portal and AGOL organization.  Now, working on collaboration between our Portal and an outside AGOL Org.
