### ISSUE TITLE
Roadkill app production release

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#287]
### Benefit

The Expo upgrade and other enhancements were completed in Q2. Deploying them to production will improve the app functionality and pay down some technical debt.

### Acceptance Criteria

- [x] Finalize client testing
- [x] Address any issues from testing
- [x] Production build and release to app stores

### Risks

- Reliance on client for timely testing and feedback
- Unforeseen production build or app store issues 

### Issue Reference

refs #168

**Comment by nathankota** [comment]
### Sprint 1
- Determine what to do with https://github.com/agrc/roadkill-mobile/issues/295
- Get feedback from Jessica
- ...

**Comment by nathankota** [comment]
### Sprint 1 Notes
- Sounds like DWR Outreach Section will use their professional translation service to verify [Spanish translations](https://github.com/agrc/roadkill-mobile/blob/staging/src/front/services/translations.json)

**Comment by stdavis** [comment]
I believe that this item is complete.
