### ISSUE TITLE
PLSS Monument Preservation Tie Sheet app

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#289]
### Benefit

[PLSS app](https://utah.maps.arcgis.com/apps/Minimalist/index.html?appid=16b3f737cc024606a3fb0de815bd08fb) needs to be upgraded to one of ESRI's newer map applications/templates.

**Comment by steveoh** [comment]
This is tracked already in #223. I think it should be closed.

**Comment by DenisePeterson** [comment]
Assigned myself to #223 and closed this issue.
