### ISSUE TITLE
Monthly Road Updates (2024-Q3)

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#290]
### Benefit

The statewide road centerline dataset supports decision-making and is critical in business systems such as 911 and the address locators. 

### Acceptance Criteria

- [ ] A current statewide road centerline dataset in the SGID that adheres, to the best of our ability, to our update schedule. 

### Notes

- [x] January 2024
   - Date: 01/11/2024
   - Counties updated
       - Box Elder
       - Carbon
       - Davis
       - Iron
       - Salt Lake
       - Sevier
       - Utah
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       - 13607 S SENTINEL RIDGE BLVD, Salt Lake City, 84065
       - 14923 MINNIE MAUD RD, Price, 84539
       - 1005 S 2580 E, St George, 84790

- [x] February 2024
   - Date: 02/08/2024
   - Counties updated:
       - Salt Lake
       - Utah
       - Weber
       - Washington
       - Wasatch
   - Three new addresses from this road update (for locator testing)
       - 1960 N LAVA COVE DR, Santa Clara 84765
       - 1250 W 400 N, Mapleton 84664
       - 160 E LAMOTTE PEAK LN, Heber City 84032
  
- [x] March 2024
   - Date: 03/07/2024
   - Counties updated:
       - Cache
       - Carbon
       - Davis
       - Kane
       - Salt Lake
       - Utah
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       -  1345 S LONE SPUR CIR, Kanab 84741
       - 3075 N 2825 W, Ogden 84404
       - 525	S SUNSET DR, Santaquin 84655

**Comment by steveoh** [comment]
@gregbunce, What do you think of updating the template to include the test addresses?

**Comment by gregbunce** [comment]
@MichaelAGRC (@ZachBeck) - what do you think about a road update on the 1/11/2024?

**Comment by MichaelAGRC** [comment]
@gregbunce - The 11th is good for me.

**Comment by ZachBeck** [comment]
That should work for me. I'll let Blue Stakes know that I'll be sending them an update on the 11th.

**Comment by gregbunce** [comment]
@MichaelAGRC how is Feb 8th looking for a road update?

**Comment by MichaelAGRC** [comment]
@gregbunce February 8th sounds good.

**Comment by gregbunce** [comment]
and road grinder was updated?

**Comment by MichaelAGRC** [comment]
**Sprint 4 Notes**

Road updates are progressing as data comes in.  Still having issues with Grand county's data.  Sent Tooele county (Bret and Dylan) a request for data in file-geodatabase format.  Shapefile results in truncating field names resulting in the script failing.

**Comment by steveoh** [comment]
> is the locator updated with the most recent road grinder data? i show those segments in the most recent data.

AddressPoints_AddressSystem, Roads_AddressSystem_STREET were deployed on the 13th

**Comment by gregbunce** [comment]
further looking into it

**Comment by gregbunce** [comment]
I verified that the zipcode and address quadrant polygon layers are correct as well.

**Comment by steveoh** [comment]
> I verified that the zipcode and address quadrant polygon layers are correct as well.

I'll look into the locators directly next week.

/remind me to ook into the locators directly next week

**Comment by gregbunce** [comment]
@MichaelAGRC what are your thoughts on us dong a road update 3/7/2024?

**Comment by MichaelAGRC** [comment]
@gregbunce - 3/7/24 is great for an update.

**Comment by gregbunce** [comment]
road updates have been completed for this quarter.

**Comment by steveoh** [comment]
/validate addresses

- 1960 N LAVA COVE DR, 84765
- 1960 N LAVA COVE DR, Santa Clara
- 1250 W 400 N, 84664
- 1250 W 400 N, Mapleton
- 160 E LAMOTTE PEAK LN, 84032
- 160 E LAMOTTE PEAK LN, Heber City
- 1345 S LONE SPUR CIR, 84741
- 1345 S LONE SPUR CIR, Kanab
- 3075 N 2825 W, 84404
- 3075 N 2825 W, Ogden
- 525 S SUNSET DR, 84655
- 525 S SUNSET DR, Santaquin

**Comment by steveoh** [comment]
/validate addresses

- 1960 N LAVA COVE DR, 84765
- 1960 N LAVA COVE DR, Santa Clara
- 1250 W 400 N, 84664
- 1250 W 400 N, Mapleton
- 160 E LAMOTTE PEAK LN, 84032
- 160 E LAMOTTE PEAK LN, Heber City
- 1345 S LONE SPUR CIR, 84741
- 1345 S LONE SPUR CIR, Kanab
- 3075 N 2825 W, 84404
- 3075 N 2825 W, Ogden
- 525 S SUNSET DR, 84655
- 525 S SUNSET DR, Santaquin

**Comment by steveoh** [comment]
/validate addresses

- 1960 N LAVA COVE DR, 84765
- 1960 N LAVA COVE DR, Santa Clara
- 1250 W 400 N, 84664
- 1250 W 400 N, Mapleton
- 160 E LAMOTTE PEAK LN, 84032
- 160 E LAMOTTE PEAK LN, Heber City
- 1345 S LONE SPUR CIR, 84741
- 1345 S LONE SPUR CIR, Kanab
- 3075 N 2825 W, 84404
- 3075 N 2825 W, Ogden
- 525 S SUNSET DR, 84655
- 525 S SUNSET DR, Santaquin

**Comment by steveoh** [comment]
@gregbunce have you processed these roads with road grinder so they should geocode properly?

**Comment by gregbunce** [comment]
i believe i did, but i can double-check.
