### ISSUE TITLE
Deprecate Fleet Vehicle Filter App

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#291]
### Benefit

- Addresses dependency on Esri Web AppBuilder, which is set for mature support on July 1, 2024
- Reduces technical debt and UGRC resources

### Acceptance Criteria

- [x] Complete a [Porter issue](https://github.com/agrc/porter/issues/new/choose) and related tasks to remove an application, and all AGOL and other data and resources.

#### App url:
https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=a9c121751583400caeff41e0209ae163

#### Lucid board
https://lucid.app/lucidchart/73073b2f-02bb-4495-9790-b21d9e649e24/edit?page=0_0&invitationId=inv_b4c7887c-d4b8-498b-8ff4-058aeff71a80#

Permission granted by Karen at Fleet Ops to deprecate the app on or after July 1, 2024, after responses to/from the following messages.
#### Dec. 7, 2023

> We discussed it with the DFO management group yesterday and the map isn't being utilized, so they don't want us to continue to maintain it or to spend the time/money to move it to the new framework. 

#### Dec. 11, 2023
> ...With that said, they did instruct me to take some "screenshots" of the map.  Do you have a deadline of when you'd decommission the map?

### Risks

None, unless Fleet decides to keep the app at the last minute, and we need to renew the maintenance contract and schedule to rebuild.

### Issue Reference

refs #63

**Comment by jacobdadams** [comment]
I have a task in my calendar for Friday June 28th to start the deprecation process.

**Comment by jacobdadams** [comment]
### 24.4.6 
- Opened https://github.com/agrc/porter/issues/326 for removal
- Also opened https://github.com/agrc/porter/issues/327 to remove the associated Facility Explorer app
