### ISSUE TITLE
DEQ Enviro v2 production ready

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#293]
### Benefit

Pay down years worth of technical debt and increase the longevity of the app with a complete rebuild using latest technology and updated infrastructure and architecture, some requested enhancements, and a paradigm shift to AGOL source layers, where possible. 

## Acceptance Criteria
- Near-production ready version of the rebuilt app at parity or parity+ with the current app.
- Client testing and validation

### Acceptance Criteria

Completion of the following tasks, along with client testing, feedback, and validation.

- https://github.com/agrc/deq-enviro/issues/401 (there are still a few things like filters)
- https://github.com/agrc/deq-enviro/issues/412 (this is the download stuff)
- https://github.com/agrc/deq-enviro/issues/400
- https://github.com/agrc/deq-enviro/issues/574
- https://github.com/agrc/deq-enviro/issues/576
- https://github.com/agrc/deq-enviro/issues/563
- https://github.com/agrc/deq-enviro/issues/560
- https://github.com/agrc/deq-enviro/issues/557
- https://github.com/agrc/deq-enviro/issues/555
- https://github.com/agrc/deq-enviro/issues/572
- https://github.com/agrc/deq-enviro/issues/573
- https://github.com/agrc/deq-enviro/issues/577

#### Left out
- https://github.com/agrc/deq-enviro/issues/406

### Risks

Resolve: budget
Own: time
Accept: client testing/feedback

### Issue Reference

refs #203

**Comment by stdavis** [comment]
## Q3 Sprint 1 Tasks
- [ ] https://github.com/agrc/deq-enviro/issues/581
- [ ] https://github.com/agrc/deq-enviro/issues/630
- [ ] https://github.com/agrc/deq-enviro/issues/580
- [ ] https://github.com/agrc/deq-enviro/issues/560
- [ ] https://github.com/agrc/deq-enviro/issues/557
- [ ] https://github.com/agrc/deq-enviro/issues/576

**Comment by stdavis** [comment]
## Q3 Sprint 2 Tasks
- [ ] https://github.com/agrc/deq-enviro/issues/573
- [ ] https://github.com/agrc/deq-enviro/issues/572
- [ ] https://github.com/agrc/deq-enviro/issues/555

**Comment by stdavis** [comment]
## Q3 Sprint 3 Tasks
- [ ] https://github.com/agrc/deq-enviro/issues/573
- [ ] https://github.com/agrc/deq-enviro/issues/572
- [ ] https://github.com/agrc/deq-enviro/issues/560
- [ ] https://github.com/agrc/deq-enviro/issues/634

Nathan test:
- [ ] https://github.com/agrc/deq-enviro/issues/555

**Comment by nathankota** [comment]
#### Q3 Sprint 4
- [ ] DEQ feedback and possible bug fixes

**Comment by stdavis** [comment]
## Q3 Sprint 5
- [ ] Complete feedback issues

**Comment by nathankota** [comment]
https://docs.google.com/spreadsheets/d/1NNenq5MzxdInyWqTNMt4eCrjMOQ-exup3BqWuGiamBA/edit#gid=223359186

**Comment by nathankota** [comment]
closing for Q3, and in favor of the next steps https://github.com/agrc/planning-queue/issues/337
