### ISSUE TITLE
Release of the new NAD83 (2011) coordinate frame for NevadaGPS on a second server

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#295]
### Benefit

The GPS Network Software Trimble Pivot does not offer a datum option for NAD 83/94 (HARN), but Washoe County and other surveyors in the area insisted that we continue using  NAD 83/94 (HARN) coordinates, so the issue is the GPS network is on NAD83 (2011) and uses NAD 83/94 (HARN) coordinates, which is an ad hoc solution. 
The new development server is set up with the correct datum and coordinates and we need to announce that it is available and educate customers on how to get connected and how to use it.

### Acceptance Criteria

- Confirm server is ready for production.
- Verify server is working properly with the production database.
- Initial email announcement to customers.
- Initial email announcement to partners and vendors.
- Conference Presentation - Monsen/Trimble Users Group.
- Conference Presentation - Utah Council of Land Surveyors.
- Follow up email announcement to customers.
- Follow up email announcements to partners and vendors.
- 

### Notes

https://turngps.dev.utah.gov/

### Risks

accept: Some customers may not be willing to move to the new coordinate system

### Issue Reference

refs #

**Comment by steveoh** [comment]
Is this waiting for Casey's work to finish? What do you envision the migration plan to be from prod to development?

**Comment by seanfernandez** [comment]
All of the items listed in the Acceptance Criteria have been completed and this server is active and available to the public.
