### ISSUE TITLE
WFRC Active Transport ("bike") Interactive Map Prototype

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#299]
### Benefit

> - Provide the most up-to-date, mapped inventory of the multi-use pathway and on-street bike facilities, and proximate amenities/destinations (i.e. rec centers, school, grocery stores etc) and other context (AADT traffic volume and approximate speed limit -- or Level of Traffic Stress LoTS)
> - Allow users to explore areas of interest to view bike-friendly transportation links, with full detail about the type of facility: class/subclass for on street bike facilities (e.g. buffered bike lane, sharrow route, etc), paved/non-paved for multi-use trails
> - Allow users to use the interactive map to contribute geographic-specific edit suggestions to the map -- specifically new, updated, or missing links

### Acceptance Criteria

- Boostrap new web app (*Hosted by WFRC) 
- Mobile first layout
- Point and click to see attributes
- Data access from app
- Layer legend/filter (customized for easy filtering such as level of traffic stress, 9-line, etc.)
- Zoom to and show current gps location on map
- Sherlock/zoom to city, etc.
- Report a problem button with form that sends feedback to WFRC (maybe link to google form?)

### Notes

From WFRC:

> ...(UGRC provides) an earl(y) hand-over of a basic first build with all of the foundational components and my team does the polishing/tuning. Get the architecture right, including thinking through the best way to act on user edit suggestions in as timely as possible (in the webapp but perhaps also in SGID?), but also use our growing esri javascript sdk skillset (Bill Hereth and Josh Reynolds) and Sarah and my ability to configure the organization and display of layers and attributes.

### Risks

Mitigate: Scope creep, by sticking to the original plan as much as possible
Accept: WFRC technical capacity to polish/tune, as expressed above in the Notes

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint First
- refer to [these notes](https://www.notion.so/Meeting-Notes-c9cfe8c762e044409cc779da6d4068a5?pvs=4)

**Comment by stdavis** [comment]
## Sprint 2 Tasks
- [ ] Create repo and add requirements as issues.
- [ ] Create system design diagram

**Comment by nathankota** [comment]
### Sprint 3
- Received feedback, mockups, and met with Bert - see `Notes` section of initial PI objective above for links to architecture diagram and mockups

**Comment by stdavis** [comment]
## Sprint 4 Tasks

- [ ] Initial mobile app layout

**Comment by stdavis** [comment]
## Sprint 5 Tasks
- [ ] finish up inital app layout

**Comment by stdavis** [comment]
Sent an email outlining the basics of the app today and requested feedback.

**Comment by nathankota** [comment]
prototype delivered
