### ISSUE TITLE
DHHS - Cooling towers map

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#3]
repo: https://github.com/agrc/dhhs-cooling-towers

## Benefit Hypothesis
Cooling towers point feature class and web map to assist DHHS HAI team during legionellaires disease outbreak investigations.

## Acceptance Criteria
- Geoenrich the cooling towers point data set
- Obtain a Creator license in DHHS's AGOL org
- Create a spatial data set in the DHHS AGOL org
- Configure an AGOL app

## Risks
Mitigate: AGOL org in which to store the data and apps. If DHHS HAI is unwilling/unable to purchase a Creator or Viewer license, UGRC can provide one. Or if they decide the data are not restricted, we may be able to use the DHHS org.

**Comment by nathankota** [comment]
### Sprint 3 Notes
## August 9
- The grant funding request for AGOL licenses was not approved, so Jeff will discuss with their finance team. The cost would be $660/year for one Creator and one Viewer license.

**Comment by nathankota** [comment]
Zach provided the data to them, and they are not requiring any of our assistance with this anymore.

**Comment by steveoh** [comment]
> Zach provided the data to them, and they are not requiring any of our assistance with this anymore.

Are they going to create a map? I'm interested to see/know what they are planning to do with the results.

**Comment by nathankota** [comment]
> > Zach provided the data to them, and they are not requiring any of our assistance with this anymore.
> 
> Are they going to create a map? I'm interested to see/know what they are planning to do with the results.

They are not planning to pay for an AGOL license and, last I heard, they were interested in exploring QGIS. They were not forthcoming with their next steps for the data, and the person that commissioned the project on the DHHS side has left the agency.

**Comment by nathankota** [comment]
Follow-up from Sarah Rigby at DHHS:

> I have been able to get the data working in QGIS. I have both the cooling tower data you provided and several years of Legionella case data imported and ready for analysis.
