### ISSUE TITLE
New and improved GPS Network online bill pay system

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#301]
### Benefit

The current GPS Network bill pay system is unreliable and often out of commission. Creating a new online bill pay system will make it possible for our customers to create a new account or renew an existing account seamlessly and it will be built following DTS security and website requirements. 

### Acceptance Criteria

- The website will require all users to create a utah ID
- Users will need instructions and be educated on how to create a Utah ID and understand why it is required.
- Initial email announcement to customers.
- Initial email announcement to partners and vendors.
- Conference Presentation - Monsen/Trimble Users Group.
- Conference Presentation - Utah Council of Land Surveyors.
- Follow up email announcement to customers.
- Follow up email announcements to partners and vendors.

### Issue Reference

refs #

**Comment by steveoh** [comment]
Can we add the product name to the dns?
