### ISSUE TITLE
PLSS Submission Backlog

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#303]
### Benefit

Several PLSS monument records have been acquired from Counties and need to be added to the PLSS data that is behind the PLSS web application which will provide customers with the most recent data available when doing survey work from section corners and determining where to focus efforts on future MRRC contracts.

### Acceptance Criteria

- [ ] 

### Issue Reference

refs #

**Comment by steveoh** [comment]
I'm happy to help figure out ways to work through the plss app submissions.

**Comment by seanfernandez** [comment]
This is an ongoing project that was started in FY24-Q3 where progress will be made each quarter. In FY24-Q3 the county PLSS data that has been collected through the MRRC program in FY23 was organized into individual county folders located here.
https://drive.google.com/drive/folders/1VMOsInSg4wQ7NEduHoq52pQECYti6hk0?usp=drive_link
