### ISSUE TITLE
UGRC API near production ready

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#309]
### Benefit

New and improved UGRC API website experience and backend and infrastructure of the geocoding and search APIs.

### Acceptance Criteria

- [x] plan for production
- [x] get analytic needs from Matt
- [x] Make the ServiceNow tasks for API work more general  (@nathankota) 
- [ ] work through the [production milestone](https://github.com/agrc/api.mapserv.utah.gov/milestone/2)

### Notes

[Some documentation](https://steve-gourley.notion.site/2023-UGRC-API-Update-c6ba5bd6858f4568b03007989890ccc5)

### Issue Reference

refs #217

**Comment by steveoh** [comment]
We should have a short meeting or two to create and organize the remaining tasks to launch the system into production. It seems we are dragging our feet with releasing.

**Comment by nathankota** [comment]
### Q4 Sprint 2
- Closed three ServiceNow tasks and created a single, new, general one to capture the remaining time put towards the API in FY24.
  - **Closed:** [PRJTASK0569559](https://utah.service-now.com/pm_project_task.do?sys_id=611619884767ad50184a874c346d431a&sysparm_record_target=pm_project_task&sysparm_record_row=1&sysparm_record_rows=4&sysparm_record_list=parent%3D34a2154c4727ad50184a874c346d436c%5EORDERBYshort_description), [PRJTASK0569551](https://utah.service-now.com/pm_project_task.do?sys_id=3a35dd084767ad50184a874c346d43d2&sysparm_record_target=pm_project_task&sysparm_record_row=2&sysparm_record_rows=4&sysparm_record_list=parent%3D34a2154c4727ad50184a874c346d436c%5EORDERBYshort_description), [PRJTASK0569564](https://utah.service-now.com/pm_project_task.do?sys_id=9a66910c4767ad50184a874c346d43cd&sysparm_record_target=pm_project_task&sysparm_record_row=3&sysparm_record_rows=4&sysparm_record_list=parent%3D34a2154c4727ad50184a874c346d436c%5EORDERBYshort_description)
  - **New:** [PRJTASK0603357](https://utah.service-now.com/pm_project_task.do?sys_id=8a7b5da287e1825835e611783cbb35fd&sysparm_record_target=pm_project_task&sysparm_record_row=4&sysparm_record_rows=4&sysparm_record_list=parent%3D34a2154c4727ad50184a874c346d436c%5EORDERBYshort_description)

**Comment by steveoh** [comment]
### Q$ Sprint 3

- Scott and I have decided to use the project board to organize, consolidate, and identify a production deployment plan
- We are working through those issues which most of the acceptance criteria for this quarter is a subset of
- I've updated the acceptance criteria to match our plan

**Comment by nathankota** [comment]
### Sprints 4 - 6
- https://github.com/agrc/api.mapserv.utah.gov/milestone/2

**Comment by steveoh** [comment]
Is there a reference to the new tracking issue?

**Comment by nathankota** [comment]
> Is there a reference to the new tracking issue?

ref: #414
