### ISSUE TITLE
Create pain point - solution statements  for solutions pillar level 1

### ISSUE THREAD

**Issue by brigsz** [agrc/planning-queue#310]
### Benefit

These pain point - solutions statements are the hooks on each solutions level 1 page.  An example would be "You cannot visualize your data?" UGRC can help an agency map their information.

### Acceptance Criteria

- [Do they follow the pattern, pain point - solution ] 
- [Create two calls to action (buttons) one is the path we want people to follow and one is to read more.]
- [Are they compelling]
- [Each Solutions level 1 should have 3-4 pain point - solutions

### Notes

I need to look closer to make sure I have the correct terminology for Pillar level 1 items

### Risks

Staff may not all agree on what the best pain point - solution is

### Issue Reference

refs #

**Comment by nathankota** [comment]
no longer relevant
