### ISSUE TITLE
Q3 Innovation and Planning - Dev Team

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#311]
### Benefit

The final sprint of the quarter is meant to be an [Innovation and Planning (IP) Iteration](https://scaledagileframework.com/innovation-and-planning-iteration/). Benefits include:
> - Allow time for Innovation
> - Dedicate time to PI Events (I&A and PI planning)
> - Integrate the Complete Solution (presentation of work of all teams on the train)
> - Advance Development Infrastructure
> - Enable Continuous Learning

Possible tasks include:
- Pay down technical debt
  - app and data dependencies and updates
  - updating CIs
- Other modernization tasks
- Cloud migration
- "Work on whatever with whomever"
- Alignment of best practices

### Acceptance Criteria

Dependabot and other modernization possible tasks

- [ ] Consider https://github.com/step-security/harden-runner this quarter or another
- [ ] Revisit the [reactfire npm conflicts](https://github.com/FirebaseExtended/reactfire/pull/594)
- [ ] Some action workflows are not completing since their required checks aren’t running
- [x] Forklift arcpy + warehouse updates
- [x] Push swapper to pypi and automate builds https://github.com/agrc/swapper/issues/19
- [x] https://github.com/agrc/skid/pull/8
- [x] Migrate to [actions/create-github-app-token](https://github.com/actions/create-github-app-token)
- [ ] Migrate to Artifact Registry
   - [ ] geocode-job
   - [ ] unclaimed property
   - [ ] roadkill
   - [x] masquerade
   - [x] parole
   - ~[ ] cambiador~
- [x] Update all functions to nodejs 20 prior to Jan 30, 2024.
- [ ] Palletjack? https://github.com/agrc/planning-queue/issues/274
- [ ] Masquerade?
  - https://github.com/agrc/planning-queue/issues/91
  - https://github.com/agrc/planning-queue/issues/281
- [x] Upgrade Pro version on Forklift machine
- Skid readme's
  - [ ] https://github.com/agrc/uorg-skid/issues/3
  - [ ] https://github.com/agrc/dabs-skid/issues/4
  - [ ] https://github.com/agrc/wmrc-skid/issues/33
  - [ ] https://github.com/agrc/broadband-speedtest-skid/issues/5

#### Dependabot

UGRC applications have dependencies that are constantly updating to add new features, improve performance, and patch security issues. Keeping applications current with dependencies improves our security posture and allows for easier future enhancements since the amount of breaking changes is smaller and more trivial.

### Risks

Insecure applications using deprecated services

### Issue Reference

refs #

**Comment by stdavis** [comment]
I took care of the forklift + arcpy upgrades a few weeks ago.

**Comment by nathankota** [comment]
Some of the tasks were carried forward to Q4, #376
