### ISSUE TITLE
Monthly Big 5 Data Requests (2024 Q3)

### ISSUE THREAD

**Issue by MichaelAGRC** [agrc/planning-queue#314]
### Benefit

By requesting data monthly from the big 5 counties (Weber, Davis, Salt Lake, Utah and Washington), we endeavor to keep our public facing data as up to date as possible. 

### Acceptance Criteria

Receiving data from the above listed counties will be counted as accepted criteria. 

### Notes
[UGRC's SGID Data Update Schedule (address points, parcels, roads)](https://docs.google.com/spreadsheets/d/1Gmt9oYMNjsIhyyMOWU6O9GnGZuSKxXs-zuHR7ADEBTs/edit?usp=sharing)
Data requests typically happen the first week of the month.
Some counties or datasets are available for download and do not need to be requested. Some counties also send updates when needed (e.g. Salt Lake parcels):
- [Utah](https://utah-county-data-sharing-hub-utahcounty.hub.arcgis.com/)
- Washington - [Distributed Geodatabase](https://agisprodvm.washco.utah.gov/arcgis/rest/services)

### Data Requested from county/Received and Available From L:\agrc\data\county_obtained
**January**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Weber | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Davis | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Salt Lake |  |  |  |  | <li>- [x] </li> | <li>- [x] </li> |
| Utah | <li>- [x] </li> | <li>- [x] </li> |  |  | <li>- [x] </li> | <li>- [x] </li> |
| Washington | <li>- [x] </li> | <li>- [x] </li> |  |  | <li>- [x] </li> | <li>- [x] </li> |

**February**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Weber | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Davis | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Salt Lake |  |  |  |  | <li>- [x] </li> | <li>- [x] </li> |
| Utah | <li>- [x] </li> | <li>- [x] </li> |  |  | <li>- [x] </li> | <li>- [x] </li> |
| Washington | <li>- [x] </li> | <li>- [x] </li> |  |  | <li>- [x] </li> | <li>- [x] </li> |

**March**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Weber | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> |
| Davis | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> |
| Salt Lake |  |  |  |  | <li>- [x] </li> | <li>- [x] </li> |
| Utah | <li>- [x] </li> | <li>- [x] </li> | |  | <li>- [x] </li> | <li>- [x] </li> |
| Washington | <li>- [x] </li> | <li>- [x] </li> |  |  | <li>- [x] </li> | <li>- [x] </li> |

### Risks

Not receiving the data is a risk, but not one that we can easily mitigate.

### Issue Reference

refs #

**Comment by rkelson** [comment]
I added a table with check boxes to help track what was or was not provided by the county. I omitted a check box for SLCo parcels as they send them directly to me when necessary and do not need to be requested.
This also seems like a good place to document where we can grab the data and forgo making the requests.

**Comment by MichaelAGRC** [comment]
I like the improvements @rkelson has made and I'd be happy to keep the ball rolling.

**Comment by ZachBeck** [comment]
I don't think SL County needs to be in there for address points, I download them each month from sftp.

**Comment by rkelson** [comment]
I was not sure how to deal with what we can each individually acquire and what Michael should pull down and que up for the group. I actually pull down the Washington and Utah Co parcels when I need them. I can edit the table to reflect that.

**Comment by rkelson** [comment]
I am not sure where the white dots are coming from above the check boxes. Feel free to hack at it if you like

**Comment by rkelson** [comment]
I removed the Parcels Received/Requested check boxes from Utah and Washington county. I pull these down when needed. Just trying to clean up some clutter

**Comment by MichaelAGRC** [comment]
This is closed
