### ISSUE TITLE
Monthly Rural Data Requests (2024 Q3)

### ISSUE THREAD

**Issue by MichaelAGRC** [agrc/planning-queue#315]
### Benefit

By requesting data monthly from select rural counties of Utah, we endeavor to keep our public facing data as up to date as possible. 

### Acceptance Criteria

Receiving data from the rural counties will be counted as accepted criteria. 

### Notes
[UGRC's SGID Data Update Schedule (address points, parcels, roads)](https://docs.google.com/spreadsheets/d/1Gmt9oYMNjsIhyyMOWU6O9GnGZuSKxXs-zuHR7ADEBTs/edit?usp=sharing)
Data requests typically happen the first week of the month.
Some counties or datasets are available for download and do not need to be requested. Some counties also send updates when needed (e.g. Kane parcels).
We could document here counties available from AGOL or the like:

### Data Requested from county/Received and Available From L:\agrc\data\county_obtained
**January**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Duchesne | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> |
| Grand | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Summit | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> |
| Wasatch| <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |

Parcels processed: Grand, Wasatch,

**February**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Cache | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Carbon | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Juab |<li>- [x] </li>| <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | 
| Morgan | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> |
| Tooele | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |

Parcels processed: Tooele, Carbon

**March**
| County | Addresses Requested | Addresses Received | Parcels Requested | Parcels Received | Roads Requested | Roads Received |
| -------- | :----------: | :------: | :-------: | :----------: | :------: | :-------: | 
| Box Elder | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Garfield | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Iron | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> |
| Uintah | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> | <li>- [x] </li> | <li>- [ ] </li> |

Parcels processed: Garfield, Iron

### Risks

Not receiving the data is a risk, but not one that we can easily mitigate.

- [x] how 
- [x] these 
- [x] are 
- [ ] intended to be
- [ ] used

### Issue Reference

refs #

**Comment by MichaelAGRC** [comment]
Thanks to @rkelson for suggestions on improving the usefulness of this feature.  I have taken it a step further and added the request itself into the matrix.  Hopefully this will allow a bit more transparency to the process.

**Comment by rkelson** [comment]
Looking good. You can probably cross the bridge when you get there but my guess is there needs to be a spot to track the miscellaneous county data that rolls in, off schedule, from the rural counties.

**Comment by MichaelAGRC** [comment]
All rural data for January requested 1/5/2024.  -Michael

**Comment by MichaelAGRC** [comment]
**Sprint 4 Notes**

All rural data for February requested 2/5/2024.

**Comment by ZachBeck** [comment]
@MichaelAGRC, no need to request address points from Garfield for March, Les sent me an update on 2/15.

**Comment by rkelson** [comment]
Considering a the data received might come well after the data is requested, I've added a comment for the parcels i've processed so I don't keep going crazy.

**Comment by MichaelAGRC** [comment]
This is closed.
