### ISSUE TITLE
Monthly Roads Processing (2024 Q3)

### ISSUE THREAD

**Issue by MichaelAGRC** [agrc/planning-queue#316]
### Benefit

Processing raw data received from the counties allows UGRC to use and distribute the data.

### Acceptance Criteria

Data received from the counties will be processed using the established scripts to result in updated county data being added to the UTRANS roads data.

### Notes

**Data processing due dates:**

- [x] December 2023 - Due date: 01/11/2024
- [x] January - Due date: 02/08/2024
- [x] February - Due date: 03/07/2024
- [ ] March - Due date: 04/04/2024

### Issue Reference

refs #

**Comment by gregbunce** [comment]
@Michael do we have a due date for this month (January)?

**Comment by MichaelAGRC** [comment]
@gregbunce do you mean December?  Wouldn't that be the 11th as we discussed?  The date for January is above:  January - Tentative date: 02/08/2024

**Comment by gregbunce** [comment]
okay, i guess it's taking a minute to see how it's laid out. I see.

**Comment by MichaelAGRC** [comment]
To Do: Enter a list of counties processed for each month.  - @MichaelAGRC

**Comment by MichaelAGRC** [comment]
@gregbunce I have a few ideas for the current iteration of the road editing software:

It would be really handy to have a button that accepts the changes from the county and saves all in one step.  There is no reason to have to click 7 or 8 different fields for each updated road segment.  This change alone would allow processing of the roads in a much more streamlined and faster way.
Same for an Ignore button that registers as IGNORE for dfccurnotes, and saves in one step.
Just those two changes would make a world of difference in the ongoing processing of county updates.  Maybe just replace the dropdown, as we never revisit anything.  It may be worth bringing the tools up to the current release of desktop as well, but I'll leave that to your discretion.

**Comment by gregbunce** [comment]
michael, thanks for the ideas, and thanks for thinking of ways to make the process smoother and more efficient.  kudos.

so, for your first suggestion, are you saying it would be a button on the arcmap form that says, 'yup.. everything they supplied looks good, import it'?

**Comment by MichaelAGRC** [comment]
I guess I'm thinking of three buttons.  

1 -  Save All.  Does just that - takes the county updates of the currently selected line and applies them to UTRANS and saves.

2 - Ignore.  Ignores the current selection.  Would be nice if it could act on multiple lines at the same time.  

3- Save.  This would still allow us to selectively choose which fields to update.

I don't think we need the dropdown anymore.  Could just line the buttons up where it is now.

**Comment by MichaelAGRC** [comment]
**Counties Updated in Sprint 1**

Box Elder
Carbon
Davis
Iron
Sevier
Utah
VECC/Salt Lake
Washington
Weber

**Comment by MichaelAGRC** [comment]
I think the Ignore button just needs to write IGNORE in the current notes field and save.  Just a quick way to skip an update that is not needed.

**Comment by MichaelAGRC** [comment]
**Counties updated in Sprint #3**

Salt Lake
Utah
Weber
Washington

**Comment by gregbunce** [comment]
thanks, michael.  let me know if the "save/transfer all" functionality is working.

**Comment by gregbunce** [comment]
as far as the other enhancement ("ignore" more than one segment at a time), i believe you can select the segments you want to ignore in the map by using the arcmap selection tool and calc values to "IGNORE" for the notes field.

**Comment by gregbunce** [comment]
you're welcome.  it sounds like we're good to go and the enhancements are working as expected.

**Comment by MichaelAGRC** [comment]
Counties updated in Sprint 5:

Kane
Weber
Carbon
Utah
Davis
VECC - Salt Lake
Washington
Cache
