### ISSUE TITLE
Portal Administration and Utilization Training

### ISSUE THREAD

**Issue by MichaelAGRC** [agrc/planning-queue#318]
### Benefit

Having the knowledge to use the software correctly to solve problems and add value to the agency requires training to use the latest innovations.  As we move forward with portal, knowledge gaps will present themselves and training will be required as issues arise.

### Acceptance Criteria

Completing the training resource to gain the skills needed at the time.

### Issue Reference

refs #283 and #284

**Comment by steveoh** [comment]
should this be in fy25 @nathankota?

**Comment by nathankota** [comment]
> should this be in fy25 @nathankota?

We're working this out via UPM and it should resurface in a more specific goal in future FY25 quarter(s).
