### ISSUE TITLE
Esri (desktop) license utilization

### ISSUE THREAD

**Issue by MichaelAGRC** [agrc/planning-queue#319]
### Benefit

Properly utilizing GIS desktop licenses is important for getting the value from our software investment.  This investigation will include meeting with UGRC stake holders to establish what data is required to make informed decisions on license quantity needed moving forward.  This would allow the agency to save a considerable amount of money depending on the number of licenses may be underutilized.

### Acceptance Criteria

- [ ] Identify data required to make decisions on license quantity per software feature.

### Notes

Most of the required information is available using OpenLM.  This investigation will include looking at using OpenLM to build the knowledge base for making informed decisions.

### Issue Reference

refs #

**Comment by nathankota** [comment]
Tentatively assigned this feature to Sprint 3 based on:
> The first task we've identified is to review the current ARCGIS.opt file, contact someone from each group to ensure that our list is as up to date as possible. Possibly Q3 Sprint 3.

**Comment by nathankota** [comment]
### Sprint 2
 - aiming for a meeting on Thursday, April 18th

**Comment by nathankota** [comment]
Closing notes:

OpenLM was run for a month and provided enough data for us to decide to trim our concurrent licenses. We decided to purchase a year-long subscription for OpenLM and will continue to monitor license usage via #437. We will also be learning about the new Esri licensing model to complement OpenLM data and possibly forge a new strategy for the license manager in the year ahead.
