### ISSUE TITLE
ETL County AGOL Address Points

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#320]
### Benefit

Where possible, access county address points in ArcGIS Online for use in ongoing address point updates. This will streamline the address point update process so that address point requests will no longer need to be sent out for participating counties.

### Acceptance Criteria

- [x] Update process in place for Morgan county.

### Notes

So far Morgan and Summit are the only known counties with address points available in ArcGIS Online. This feature is intended to develop code to pull address points from a county's AGOL into local ETL processes for monthly address point updates.

### Risks

County update process isn't mature and address point updates aren't being published to AGOL in a timely manner.

### Issue Reference

refs #

**Comment by ZachBeck** [comment]
### Q3 Sprint 1 Tasks
- [ ] Complete generic function to bring AGOL points to local fgdb for ETL scripts.

**Comment by steveoh** [comment]
FYI [export features](https://pro.arcgis.com/en/pro-app/latest/tool-reference/conversion/export-features.htm) replaced the Feature Class To Feature Class deprecated tool.

**Comment by ZachBeck** [comment]
Ahh, thanks. I was doing it the hard way with arcpy.conversion.JSONToFeatures

**Comment by ZachBeck** [comment]
done
