### ISSUE TITLE
Address point monthly update

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#321]
### Benefit

Current address points for Utah.

### Acceptance Criteria

"Big 5" counties updated monthly along with rural counties who have submitted address points.

### Risks

Success depends on county participation, especially from rural counties. If county address points aren't received by the UGRC in a timely manner our update process suffers.

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 1 Tasks

**Comment by ZachBeck** [comment]
### Sprint 3 Tasks
Counties to ETL (rural counties to be added)
- [ ] Davis
- [ ] Salt Lake
- [ ] Utah
- [ ] Washington
- [ ] Weber

**Comment by ZachBeck** [comment]
Q3 tasks completed, moving on to Q4.
