### ISSUE TITLE
PSAP support with regular updates

### ISSUE THREAD

**Issue by mhchou** [agrc/planning-queue#323]
### Benefit

Ensure PSAP centers have a low dispatch error rate; fulfill the contract responsibilities where applicable; and maintain the 911 fund income for UGRC.

### Acceptance Criteria

- [ ] Successfully updated all GIS data for each scheduled entity.
- [x] Begin editing on St. George and Beaver.
- [ ] Establish a relationship with Logan, Tooele, and Summit Counties.

### Sprint 1

- [x] Weber

### Sprint 2

- [x] Weber

### Sprint 3

- [x] Weber

### Sprint 4

- Focused on geovalidation upgrades

### Sprint 5

- [ ] Beaver
- [x] Weber
- [ ] St George

### Issue Reference

refs #202

**Comment by gregbunce** [comment]
hey, hank.  i can't remember, what psaps are getting updates for q3 sprint 1?  

what do you think about creating a tentative list for each sprint with checkboxes?  it could probably be done in the main section above.

**Comment by gregbunce** [comment]
@mhchou i'll let you make the needed comments and close this feature out when it's time.
