### ISSUE TITLE
Spillman Upgrades

### ISSUE THREAD

**Issue by mhchou** [agrc/planning-queue#324]
### Benefit

The involved PSAPs will enjoy a new state-of-the-art dispatch system, from Classic to Geovalidation, with the coveted type-ahead feature using ArcGIS Pro setup.

### Acceptance Criteria

- [ ] Successfully upgrade the scheduled 3 PSAPs: Uintah Basin, Box Elder, and Price

### Sprint 1

- [x] Price (geovalidation is live now)

### Sprint 2

- [x] Uintah Basin

### Sprint 4

- [x] Salt Lake

### Sprint 5

- [x] Price (turnover)
- [ ] Box Elder (WIP)

### Issue Reference

refs #

**Comment by gregbunce** [comment]
Price is going live on 2/9/2024

**Comment by gregbunce** [comment]
TOC upgraded to Pro (will work on Pro process after Price upgrade)

**Comment by mhchou** [comment]
Developed state-wide road routing network straight from SGID.
Published Pro GIS services for Uintah, Box Elder, and Price.
