### ISSUE TITLE
Dev Summit Prep

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#326]
### Benefit

A well-prepared and well-rehearsed presentation will reflect good on the office

### Acceptance Criteria

- [ ] Presentation slides
- [ ] Practice

### Notes

Still waiting on Esri for slides due date

### Issue Reference

refs #

**Comment by steveoh** [comment]
What is your presentation?

**Comment by nathankota** [comment]
> What is your presentation?

Not to speak out of place or for Jake but, IIRC, it's a palletjack presentation.
