### ISSUE TITLE
VISTA Ballot Area Precinct Updates

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#327]
### Benefit

Update County precincts as they are received.

### Acceptance Criteria

- [ ] 

### Issue Reference

refs #

**Comment by gregbunce** [comment]
2024-01-15 updated Weber

**Comment by gregbunce** [comment]
3 counties on the docket for March 20th.

- Box Elder
- Sevier
- Cache

**Comment by DenisePeterson** [comment]
Closed. Ongoing project. Created new issue for FY24 - Q4.
