### ISSUE TITLE
Update Open Source Places SGID layer, monthly (FY24 Q3)

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#328]
### Benefit

The [Open Source Places](https://gis.utah.gov/data/society/open-source-places/) layer is a new-ish SGID layer with various uses, including the  911 community. We need a UGRC champion/steward and a monthly update schedule to ensure this layer gets timely updates. 

### Acceptance Criteria

- [x] Monthly updates

### Notes

The update process has been scripted out and more or less runs with little human intervention.  The process is as follows:

- Use the scripts in the Github repo: https://github.com/agrc/OpenSourcePlaces
- Clone repo and create credentials.py with connection file info and base directory
- Run [OS_Places_ETL_to_SGID.py](https://github.com/agrc/OpenSourcePlaces/blob/main/OS_Places_ETL_to_SGID.py)
- Verify the data was updated in SGID and metadata has today's date
- Update the [Open Source Places webpage](https://gis.utah.gov/data/society/open-source-places/) with refresh date and number of features added

### Issue Reference

refs #

**Comment by gregbunce** [comment]
sidenote: erik created [a fork](https://github.com/eneemann/OpenSourcePlaces) of this repo to pull from AGOL data instead of the internal SGID.  This version of the script no longer updates internal SGID and the metadata though, so you’ll have to take care of that (and the date on the website page)

**Comment by mhchou** [comment]
@gregbunce showed @mhchou the update process. @mhchou will take over this layer and update it monthly going forward.
