### ISSUE TITLE
Refactor Basic parcel processing python code

### ISSUE THREAD

**Issue by rkelson** [agrc/planning-queue#330]
### Benefit

This will provide faster processing of parcel data and avoid some of the recent 'hang time' experienced when processing over VPN by removing the requirement to directly hit various SDE layers used for Identity overlay operations. This will also read and write locally instead of utilizing L:\ (\\itwfpcap2).

### Acceptance Criteria

- [x] Removed requirement to directly hit SDE over VPN 
- [x] Parcel processing runs faster
- [x] Processing output is the same as before refactoring

### Notes

This refactoring of the Basic parcel code happens ever new year but this year has a new twist using local copies of SDE layers.

- [x] Write code to pull various layers locally from SDE periodically
- [x] Rewrite code to utilize local copies of SDE layers
- [x] Alter individual county scripts to utilize local SDE layers
- [x] add function to script to automate download of Utah Co parcels
- [x] document in code comments per county if their data can be downloaded as a zip, exported from AGOL, or the like.

### Risks

Land Ownership, municipal and zip code boundaries could change (very rare) or address points get added to SDE outdating local layers. This is easily mitigated by pulling down the SDE layers routinely before processing the parcel data.

### Issue Reference

refs # [INC1924013](https://utah.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3D61bd06abc3e63d1089d31d4ce001315c%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue)

**Comment by steveoh** [comment]
Is this code in GitHub?
