### ISSUE TITLE
Utah Broadband Office Technical Support (FY24 Q3)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#332]
### Benefit

As the GOEO Broadband Office navigates the processes for distributing federal funds for expanding broadband service in Utah, they require and request technical analysis and mapping of a variety of data to ensure the process is adhered to, and that the funds are distributed properly. UGRC provides these technical analytical services. 

### Acceptance Criteria

To provide results within timelines sought by the GOEO Broadband Office. Specific tasks will be determined and described within sprint-level comments.

### Risks

- lack of clarity of requirements
- short deadlines/turnaround times
- interruption of other PI objectives

### Issue Reference

refs #

**Comment by jacobdadams** [comment]
### Sprint 2 Tasks

- [ ] Initial hex-based area analysis
- [ ] Redo area analysis using census block groups, work with UBC on language for their report

**Comment by jacobdadams** [comment]
### Sprint 3 Tasks

- [ ] Figure out and run the analysis for the CBG/ISP pairs for the pre-challenge modification
- [ ] Document analysis procedure for submissions
- [ ] Send spatial data to Horrocks

**Comment by jacobdadams** [comment]
### Future Tasks

- [ ] Identify BEAD Eligible Blocks:
  - At least one underserved/unserved BSL in block
  - All copper/unlicensed fixed wireless/satellite count as underserved
- [ ] Get average size of parcels containing residential BSLs per county/CBG/Block for Clint

**Comment by nathankota** [comment]
### Sprint 6 (final week)
- Run pre-challenge analysis again, this time removing any census blocks that  have at least one other ISP that does provide service at the "served" level

**Comment by nathankota** [comment]
all tasks completed for this quarter
