### ISSUE TITLE
Update base maps with new milepost and freeway exits

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#333]
### Benefit

Current base map milepost and freeway exit layers have been deprecated and replaced by UDOT. Base map layers need to be migrated to new data to remain current.

### Acceptance Criteria

- [x] Milepost symbology and label expressions needs to updated in Lite, Terrain, Overlay and vector tile draft.
- [ ] Exit symbology and label expressions needs to updated in Lite, Terrain, Overlay and vector tile draft.

### Issue Reference

refs #

**Comment by ZachBeck** [comment]
Mileposts updated in base maps, waiting to hear back on exits.

**Comment by nathankota** [comment]
one of two completed. Will continue in next quarter via #441
