### ISSUE TITLE
DHHS OPCRH map updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#334]
### Benefit

Annual updates to the AGOL data and maps for the DHHS Office of Primary Care and Rural Health.
https://ruralhealth.health.utah.gov/maps/

### Acceptance Criteria

- [x] Work with OPCRH team to determine the data that needs to be updated, and any effects they may have on the associated maps.

### Risks

- OPCRH team engagement
- Timing/scheduling of updates

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Q3 Sprint 3 NOTES
- Marc Watterson replaced Ashley Moretz as the OPCRH Director. 
- The contract expires end of March, and they'd like to do some updates before then. We will then work on a longer-term agreement for annual updates and other work.
- Rachel and other PCRH staff are currently identifying the updates for the data and maps.

**Comment by ZachBeck** [comment]
Updated J-1 Visa, Primary Care Grants, and Load Repayment apps, waiting for feedback and response about HPSA data.

**Comment by nathankota** [comment]
### Sprint 2
- Complete updates related to latest feedback

**Comment by ZachBeck** [comment]
HPSA app sent out for review.
https://experience.arcgis.com/experience/9d6b6e7d9e504344a2d5959331136639/

**Comment by ZachBeck** [comment]
Health folks happy with updates no more changes requested.

**Comment by ZachBeck** [comment]
Option to download map layer tables added to a test app and sent for review.  Fixed broken app link in app gallery page. 6/24/2024

**Comment by ZachBeck** [comment]
More data sent to update Loan Repayment Site map. Still waiting to hear back about the table download option.

**Comment by nathankota** [comment]
Carried-forward to FY25 Q1

**Comment by ZachBeck** [comment]
Rachel has requested the update of 3 the 3 layers in the loan repayment [map](https://experience.arcgis.com/experience/6b3a6c48466448cbbb18603523057108/). This will involve geocoding these [tables](https://docs.google.com/spreadsheets/d/1xZ2BerbubqSWKCDLzPTpbVMWJ6ZydLK1NRVUEj-HlRk/edit?gid=0#gid=0) and replacing the existing map layers and updating pop ups.

**Comment by ZachBeck** [comment]
Rachel has requested the update of the Health Care Facilities [map](https://experience.arcgis.com/experience/312b434844694830b643548566ddd8fa/#data_s=id%3AdataSource_3-18826ba6b7e-layer-5%3A59316) with the following:

- Remove the list of Federally qualified health centers (FQHCs) and Community Health Centers (CHCs)
- Update the RHCs with the list that is attached.
- Keep rural veterans as is. 
- Change title of map and update splash page (text is below)

Splash page title change:
Rural Health Clinics and Veteran Affairs Health Centers
This is an interactive map of Rural Health Clinics and Veteran Affairs Health Centers. 
Updated 2024

**Comment by ZachBeck** [comment]
Loan repayment and facilities app requests are complete and sent to Rachel for review.

**Comment by nathankota** [comment]
> Loan repayment and facilities app requests are complete and sent to Rachel for review.

Rachel validated the updates
