### ISSUE TITLE
Monthly Road Updates (FY24 Q4)

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#335]
### Benefit

The statewide road centerline dataset supports decision-making and is critical in business systems such as 911 and the address locators. 

### Acceptance Criteria

- [x] A current statewide road centerline dataset in the SGID that adheres, to the best of our ability, to our update schedule. 

### Notes

- [x] April 2024
   - Date: 04/12/2024
   - Counties updated
       - Box Elder
       - Iron
       - Juab
       - Salt Lake
       - Utah
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       - 5245 W CANAL BLVD, American Fork 84003
       - 784	SANCTUARY PL, Ivins 84738
       - 425	S 1150 W, Brigham City 84302

- [x] May 2024
   - Date: 05/9/2024
   - Counties updated
       - Piute
       - Salt Lake
       - Sevier
       - Utah
       - Wasatch
       - Washington
       - Wayne 
   - Three new addresses from this road update (for locator testing)
       - 1603 S LAMAR LN, HEBER CITY 84032
       - 1110 S 1810 E, TEASDALE, 84773
       - 3836 W 2530 S, HURRICANE, 84737
  
- [x] June 2024
   - Date: 06/13/2024
   - Counties updated
      - Cache
      - Davis
      - Iron
      - Salt Lake
      - Tooele
      - Utah
      - Washington
      - Wayne
   - Three new addresses from this road update (for locator testing)
       - 3255 E FARMSTEAD RD, St George 84790
       - 80 N 300 E, Hyrum 84319
       - 8740 N DENTON AVE, Tooele 84074

**Comment by gregbunce** [comment]
after the April road grinder update, let's check these addresses again. 
https://github.com/agrc/planning-queue/issues/290#issuecomment-2029799396

**Comment by steveoh** [comment]
i created an action to test addresses in github comments 🎉

```
/validate addresses
- 5245 W CANAL BLVD, 84003
- 5245 W CANAL BLVD, American Fork
- 784 SANCTUARY PL, 84738
- 784 SANCTUARY PL, Ivins
- 425 S 1150 W, Brigham City
- 425 S 1150 W, 84302
```

feel free to run this adhoc.

**Comment by steveoh** [comment]
/validate addresses
- 5245 W CANAL BLVD, 84003
- 5245 W CANAL BLVD, American Fork
- 784 SANCTUARY PL, 84738
- 784 SANCTUARY PL, Ivins
- 425 S 1150 W, Brigham City
- 425 S 1150 W, 84302

**Comment by gregbunce** [comment]
was this run after the most recent road grinder update (from yesterday)?

**Comment by steveoh** [comment]
It was just run 10 minutes ago.

**Comment by gregbunce** [comment]
hmm. okay, seems odd it didn't find it. i'll check the road grinder data again.

**Comment by steveoh** [comment]
I just checked the forklift logs and they got lifted this morning so they will ship tonight. You may want to replace the canal address since it's already matching?

**Comment by gregbunce** [comment]
/validate addresses
- 2465 N LA CASA CIR, St George
- 2465 N LA CASA CIR, 84770
- 784 SANCTUARY PL, 84738
- 784 SANCTUARY PL, Ivins
- 425 S 1150 W, Brigham City
- 425 S 1150 W, 84302

**Comment by gregbunce** [comment]
/validate addresses
- 1603 S LAMAR LN, HEBER CITY 84032
- 1110 S 1810 E, TEASDALE, 84773
- 3836 W 2530 S, HURRICANE, 84737
- 1603 S LAMAR LN, 84032
- 1110 S 1810 E, 84773
- 3836 W 2530 S, 84737

**Comment by gregbunce** [comment]
/validate addresses
- 3255 E FARMSTEAD RD, St George 84790
- 80 N 300 E, Hyrum 84319
- 8740 N DENTON AVE, Tooele 84074

**Comment by steveoh** [comment]
you need to pick the city or the zip for these. the api is not expecting both. I'm a little surprised it worked at all.

**Comment by gregbunce** [comment]
ahh, thanks for the tip.

**Comment by gregbunce** [comment]
/validate addresses
- 8740 N DENTON AVE Tooele
- 8740 N DENTON AVE 84074

**Comment by steveoh** [comment]
You still need the comma...

**Comment by gregbunce** [comment]
ahh, i knew that.  jeez

**Comment by gregbunce** [comment]
/validate addresses

- 8740 N DENTON AVE, Tooele
- 8740 N DENTON AVE, 84074

**Comment by gregbunce** [comment]
let me see...

**Comment by gregbunce** [comment]
/validate addresses

8730 N DENTON AVE Tooele
8730 N DENTON AVE 84074

**Comment by gregbunce** [comment]
/validate addresses

- 8730 N DENTON AVE, Tooele
- 8730 N DENTON AVE, 84074

**Comment by gregbunce** [comment]
/validate addresses

- 8715 N DENTON AVE, Tooele
- 8715 N DENTON AVE, 84074

**Comment by gregbunce** [comment]
@steveoh, let me know if i'm missing something. here's a screenshot of the most recent road grinder roads fc. 


![Image](https://github.com/agrc/planning-queue/assets/16906316/c2264854-52d7-48ba-9ae5-d4df55316255)

**Comment by gregbunce** [comment]
i spoke with steve, we'll try to validate again this friday after the road grinder data gets a refresh.

**Comment by gregbunce** [comment]
/validate addresses
- 8740 N DENTON AVE, Tooele
- 8740 N DENTON AVE, 84074
