### ISSUE TITLE
Portal - Collaboration setup

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#338]
### Benefit

UGRC will benefit immensely from a mechanism that allows us to collaborate on datasets with our authoritative stewards. For now, this mechanism is our Enterprise/Portal.

We made some progress in [FY24 Q3](https://github.com/agrc/planning-queue/issues/284), however, there are some pieces that still need to be worked out.

For this quarter, we need to get the data synching across the orgs. In other words, when one org makes an edit, the other org can see it. Currently, we are having an issue with this and Will from ESRI thinks it's a bug. WFRC has been a willing tester with us and they willing to continue working with us to get this resolved and working. 

### Acceptance Criteria

- [x] determine the cause of the Portal publishing error. We have a ticket in with DTS to see if it's a firewall issue. If not, then it's time to put in an Esri ticket.

### Risks

Issues with collaboration environment - Esri ticket submitted?

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- Consultation b/t @gregbunce & @MichaelAGRC to define the Portal ticket to be submitted to Esri

**Comment by nathankota** [comment]
### Sprint 4
- Reload collaboration data set(s) into the data store (@MichaelAGRC, @ZachBeck )
- Continue investigating issues related to synchronization of data from host AGOL to UGRC Portal

**Comment by gregbunce** [comment]
Michael is putting in a ticket with Esri to resolve the issue of not being able to publsih a service.

**Comment by MichaelAGRC** [comment]
**Sprint 5 Notes:**

After further review of the logs on the hosting server, it looks like one of the requested firewall rules was not implemented - leading the hosting machine unable to copy data to the datastore database.  

Algosec Firewall Rule Request: [RITM0271896](https://utah.service-now.com/nav_to.do?uri=sc_req_item.do%3Fsys_id=656db10997a2069052a6bdb8c253af14%26sysparm_stack=sc_req_item_list.do%3Fsysparm_query=active=true)

**Comment by gregbunce** [comment]
Michael worked with ESRI via a ticket and was able to workout the issue. We are now able to publish services.
