### ISSUE TITLE
Ensure all SGID layers have a ugrc steward

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#339]
### Benefit

It's critical that we have the 'story' behind all the layers that UGRC serves in the SGID. At the most basic level, we must have a UGRC steward defined for each layer in the [SGID Index sheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148). 

This internal steward is our in-house person who either might know the background on the data or is someone who can reach out to the agency steward to learn more. This UGRC steward should also be the point of contact in UGRC and ensure that the data pages, stewardship sheet, etc. are up to date and current. 

With this feature/objective, I am proposing that we (the data team) go through the [SGID Index sheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) and ensure that all rows have an appropriate SGID steward.

### Acceptance Criteria

- [x] Each row in the [SGID Index sheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) has a defined UGRC steward in the `ugrcSteward` field 

### Risks

none

### Issue Reference

refs #

**Comment by gregbunce** [comment]
getting closer on this one. we'll talk about it again on June 4, in the data team meeting.

**Comment by steveoh** [comment]
It's now July, how is this going? Are you bringing it into FY25?

**Comment by gregbunce** [comment]
the data team went through and assigned as many records that individuals in the office knew about. the remaining ones we marked as ugrc-employees@utah.gov. we'll look at the list again soon and see if we can't assign some of those to specific folks.
