### ISSUE TITLE
AGOL Vector Tiles

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#346]
### Benefit

Base maps that are easier and faster to maintain and update than traditional raster base maps. Vector tiles also render better and are more portable than current raster base maps.

### Acceptance Criteria

- [x] Resolve larger tile sizes
- [ ] Clean up cartography and labels
- [ ] Publish to AGOL

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- Continue making changes related to tile sizes and cleaning up cartography and labels, and republish

**Comment by ZachBeck** [comment]
Updated tiles will be exported and loaded into AGOL on the 25th.

**Comment by ZachBeck** [comment]
Vector hillshade tile sizes are now an acceptable size though not perfect. 2 tiles are 265kb and 207kb which should be ok to start with.

**Comment by ZachBeck** [comment]
Label clean up continues. Closing for FY25 Q1
