### ISSUE TITLE
Address Point Monthly Update (FY24 Q4)

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#350]
### Benefit

Current address points for Utah.

### Acceptance Criteria

"Big 5" counties updated monthly along with rural counties who have submitted address points.

### Risks

Success depends on county participation, especially from rural counties. If county address points aren't received by the UGRC in a timely manner our update process suffers.

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- Monthly address point updates are not correct on the website (#377), which needs some attention

**Comment by steveoh** [comment]
> * Monthly address point updates are not correct on the website ([UGRC website phase 2 #377](https://github.com/agrc/planning-queue/issues/377)), which needs some attention

What is wrong with the address point updates? Fixing those would be a pull request. How does it relate to #377?

**Comment by ZachBeck** [comment]
@steveoh it's just updating the update history list, I noticed February and March were missing. I'll get it fixed.

**Comment by ZachBeck** [comment]
Address point updates for April are ongoing. Waiting for some counties to send points, Summit has changed their schema which means a rewrite of their ETL script.

**Comment by nathankota** [comment]
### Sprint 3
- Investigate Summit County incoming data and attempt to resolve some associated issues
  - affects Sweeper, Address Parser, and likely other processes
- Ultimately need to rewrite the ETL script

**Comment by steveoh** [comment]
>   * affects Sweeper, Address Parser, and likely other processes - submit GitHub issues in respective repositories, as needed

How does this affect sweeper? 
What is the address parser?
Do we have a decent understanding of the other processes?

**Comment by ZachBeck** [comment]
`from sweeper.address_parser import Address` is returning incorrect prefix directions when parsing an address like 2504 E South Fork Canyon Rd (returns S for the prefix). I've noticed some other issues as well that I'll put in a PR.

**Comment by steveoh** [comment]
hmm, that's a model trained on Utah data. We might need to update the training as we don't own the logic to fix issues like that. @stdavis what do you think?

**Comment by ZachBeck** [comment]
May address point updates are complete.

**Comment by ZachBeck** [comment]
June address points are complete 4/1

**Comment by ZachBeck** [comment]
done
