### ISSUE TITLE
UHAF - App and data updates (FY24 Q4)

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#351]
### Benefit

Maintain interactive [Dashboard](https://utah.maps.arcgis.com/apps/dashboards/2af128402650481eb1c18b025cd752d6) for the [Utah Homeowners Assistance Fund](https://homeownersassistance.utah.gov/) which acts as a resource for statewide information regarding assistance approved and paid, households assisted, average assistance amounts, etc…

### Acceptance Criteria

- Update with data provided monthly by client 
- Maintain app

### Issue Reference

refs #

**Comment by DenisePeterson** [comment]
Closed and added new issue for FY25 - Q1.

**Comment by steveoh** [comment]
Was there progress on this in q4?

**Comment by DenisePeterson** [comment]
Yes, the app was created and then I did monthly updates as they provided data. Going forward, I'll be updating the app as they submit updated data.
