### ISSUE TITLE
Blue Stakes Monthly Update (FY24 Q4)

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#352]
### Benefit

ETL process so that Blue Stakes has up to date data for their locate requests.

### Acceptance Criteria

Monthly updates sent to Blue Stakes and their feedback and fixes incorporated into UGRC data where possible or forwarded on to the county responsible.

### Issue Reference

refs #

**Comment by ZachBeck** [comment]
Blue Stakes April update sent on 4/15/2024

**Comment by nathankota** [comment]
### Sprint 3
- Send an update

**Comment by ZachBeck** [comment]
May updates sent on 5/13/2024

**Comment by ZachBeck** [comment]
June update sent 6/13/2024

**Comment by ZachBeck** [comment]
done
