### ISSUE TITLE
Voting Districts app rebuild

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/planning-queue#356]
### Benefit

- Migrate from AGOL Web AppBuilder app, which will no longer be supported by Esri after July 1, 2024

### Acceptance Criteria

- Instant App, ExB or similar to replace the features and functionality of the [Utah Voting Districts 2022-2032](https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=2ea0582adb374e8b86420b222ccd5f7a)
- [Link to new Voting Districts app](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=533ba1d728ad40d4bc189216c329766d)

### Issue Reference

refs #

**Comment by DenisePeterson** [comment]
Created new voting districts app in AGOL. New app is not yet public but is finished.

**Comment by steveoh** [comment]
can you provide a link to the new app?

**Comment by DenisePeterson** [comment]
Yes, here is a link to the new [voting districts app](https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=533ba1d728ad40d4bc189216c329766d).

**Comment by nathankota** [comment]
@steveoh who do we contact about the state url shortener?

**Comment by steveoh** [comment]
> @steveoh who do we contact about the state url shortener?

Joe Jackson or Ben Meibos

**Comment by nathankota** [comment]
### FY25 Q1 Sprint 1 Notes
- Reviewed and made some final changes to the app (Denise and Nathan)
- Obtained a shortened url with a custom path from Ben Meibos
- Contacted Hayden Loftus in the Elections Office for his review and validation, and requested to change the link on the vote site to the new app when he's ready

Shortened/custom url is:
https://s.utah.gov/utah-voting-districts

**Comment by nathankota** [comment]
### Sprint Next
- [ ] Retire Web AppBuilder app https://www.arcgis.com/apps/webappviewer/index.html?id=2ea0582adb374e8b86420b222ccd5f7a
- [ ] Change the app url on the [ServiceNow Business Application record](https://utah.service-now.com/now/nav/ui/classic/params/target/cmdb_ci_business_app.do%3Fsys_id%3D3a544a431be115d049656358b04bcb36%26sysparm_view%3Dbusiness_applications%26sysparm_record_target%3Dcmdb_ci_business_app%26sysparm_record_row%3D60%26sysparm_record_rows%3D63%26sysparm_record_list%3Ddepartment.idCONTAINS6010%255EORdepartment.idCONTAINS6012%255EORDERBYname)

**Comment by DenisePeterson** [comment]
This app has been created and the old app has been retired.
