### ISSUE TITLE
WFRC app support and tech assistance

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#36]
## [Wasatch Choice app](https://github.com/agrc/wfrc-wasatch-choice)
Improvements:
- Switch to [kitchen sink components](https://github.com/agrc/wfrc-wasatch-choice/issues/123) 
- Other possible tasks [here](https://github.com/agrc/wfrc-wasatch-choice/issues)

## [RTP app](https://github.com/agrc/wfrc-rtp-projects)
Improvements:
- Switch to [kitchen sink components](https://github.com/agrc/wfrc-rtp-projects/issues/50)
- Other possible tasks [here](https://github.com/agrc/wfrc-rtp-projects/issues)

**Comment by nathankota** [comment]
### Sprint 3 Tasks:
- Maybe one of the following?
  - [#123](https://github.com/agrc/wfrc-wasatch-choice/issues/123)
  - Bert:
     > The layer/legend control's checkbox/toggle state persists as the user moves between tabs (yay!) but it is not persisted in the URL (copy and paste into a new incognito window, for example). Not sure if that can be addressed quickly or not but if it's possible but needs more time, we can wait and go with what you've got so far.

     Scott:
     > Persisting the checkbox states via the URL will take more work than I have time for this morning. We haven't done that before in this app. We do persist other application state in the URL so the plumbing is there. I'm guessing that I could get this done in a day when I get back.

- > One thing that may be easier to fix (maybe through css?) is providing more obvious toggle state differentiation....I am sure there are limits but could the non-active color be, say grayed out?

**Comment by stdavis** [comment]
I'm planning on helping with config changes and deployment issues over the next few days. Then I _think_ that this project will slow down.

**Comment by stdavis** [comment]
Bert seems to be happy with the latest release.

**Comment by nathankota** [comment]
No additional tasks or requests have been made for this quarter.

**Comment by nathankota** [comment]
### Sprint 6 Possible Task:
- [ ] https://github.com/agrc/wfrc-wasatch-choice/issues/256

**Comment by nathankota** [comment]
closed by Sprint 6 task
