### ISSUE TITLE
Explore GPS Station Inspections Mobile App

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#364]
### Benefit

Investigate out-of-box products similar to Google Table, Airtable, Survey123 and other Mobile Apps that can be configured to help track on-site GPS Network Station Inspections.

### Acceptance Criteria

- [x] Investigate cost and functionality.
- [x] Demo apps using a sample of our GPS Stations data.
- [x] Confirm the suggested product has all of the functionality available. 
-Import a table of all GPS stations
-Allows for checklists 
-Allows for  data fields to be modified Mobily
-Allows for photos to be incorporated into the data

### Issue Reference

refs #

**Comment by seanfernandez** [comment]
All items listed under the Acceptance Criteria are completed as outlined.
The web app I chose to investigate was Airtable for managing TURN GPS Site Inspections.
There are different fees associated with the business needs ranging from Free, to Team, to Business and Enterprise Scale and the cost are attached.
I believe the Free version would work for our needs base on the demo.
This product has the ability to do the following as shown in the attachments

![Image](https://github.com/agrc/planning-queue/assets/9937422/741d1cc4-e0d1-4dd8-88ba-5d742d7a4858)
![Image](https://github.com/agrc/planning-queue/assets/9937422/2c6d753e-469c-4fa5-b396-43b239a25986)
![Image](https://github.com/agrc/planning-queue/assets/9937422/cb68ea04-42ec-4e2b-99d8-b5052966b4da)
![Image](https://github.com/agrc/planning-queue/assets/9937422/66b17f4d-85af-4261-804c-aedfd4e13886)

:
-Import a table of all GPS stations
-Allows for checklists
-Allows for data fields to be modified Mobily
-Allows for photos to be incorporated into the data

**Comment by steveoh** [comment]
Just as an FYI from Joe Jackson, 

> Airtable is not approved and the few groups using it have been asked to migrate to one of the approved platforms. Salesforce, ServiceNow, and Power Platform are the ones people are supposed to be migrating to. Jared Jensen can connect you with his teams and help determine which would be the best fit.

**Comment by seanfernandez** [comment]
Thanks for the info. At the time I was investigating I was unaware of these restrictions, so it sounds like I will need to test some new products from the list you've provided. 
Thanks

**Comment by steveoh** [comment]
Yeah it is best to start with Joe Jackson on solution requests like this to know what is already available and what to stay away from.
