### ISSUE TITLE
DEQ Enviro v2 production release

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#365]
### Benefit

Realize all Scott's hard work and the improvements he enacted by launching the new Enviro app; thereby replacing the existing app. 

### Acceptance Criteria

- Complete necessary tasks to release v2 Enviro to production 

### Issue Reference

- [ ] https://github.com/agrc/deq-enviro/issues/664

**Comment by stdavis** [comment]
Other than waiting on a ticket to clean up the old load balancer and some future forklift cleanup once we get the last few services off of mapserv, I think that we can mark this as complete.
