### ISSUE TITLE
 New GPS Installs

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#367]
### Benefit

New installs are often needed to improve the reliability, accuracy and quality of the GPS Network as users begin to expand into additional coverage areas. A new station is needed at the Green River Udot maintenance facility and the following tasks must be completed for the new install.

### Acceptance Criteria

- [x] Schedule and Organize a new install at the Green River Udot Maintenance Shed.
- [x] Request and acquire the IT networking clearance and Static IP to be assigned.
- [x] Physically install the antenna mast on the building.
- [x] Physically install the GPS receiver.
- [x] Setup configuration and connect the station to the network.
- [x] Process new coordinates and add the station to the Real-time solution. 

### Issue Reference

refs #

**Comment by seanfernandez** [comment]
All items listed under the Acceptance Criteria are completed as outlined.
A brand new install at the new Green River Udot maintenance building has been completed along with all the setup, configuration and updates needed to connect to the Real-time network.
The site is now included as part of the Real-time network and covers a large area near the town of Green River Utah.

**Comment by steveoh** [comment]
Have the network gis data, maps ,and apps been updated to include these new points? cc @DenisePeterson

**Comment by DenisePeterson** [comment]
@steveoh @seanfernandez - they have not. Sean, if you can provide the new points, then I can update these.

**Comment by seanfernandez** [comment]
@steveoh @DenisePeterson The new Green River station is on the sensor map. Select the pin then select the info tab to see the coordinates.
https://turngps.utah.gov/Map/SensorMap.aspx
Thanks for adding it to the GIS map and the site logs site.

**Comment by steveoh** [comment]
should [these](https://github.com/agrc/planning-queue/issues/366#issuecomment-2214841637) be included also?
