### ISSUE TITLE
Enviro data improvements

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#368]
### Benefit

- Updated Point Source Emissions data source
- Limit Oil and Gas wells to only those of interest to the DAQ audience

### Acceptance Criteria

- [x] https://github.com/agrc/deq-enviro/issues/662
- ~https://github.com/agrc/deq-enviro/issues/637~

### Issue Reference

refs #

**Comment by stdavis** [comment]
I haven't heard anyone complain about https://github.com/agrc/deq-enviro/issues/637. @nathankota Should we just ignore it for now and close this as completed?

**Comment by nathankota** [comment]
I added https://github.com/agrc/deq-enviro/issues/637 as a possible task for #420
