### ISSUE TITLE
Roadkill - publish new version

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#369]
### Benefit

Latest version with recent changes and any bug fixes.

### Acceptance Criteria

Investigate these:
- [x] https://github.com/agrc/roadkill-mobile/issues/311
- [x] https://github.com/agrc/roadkill-mobile/issues/312

And these:

- > It's one button click to publish on google play since it's already passed the review process. But I'm still a little worried.
- > There also is an issue with the apple review. When they tried to login with facebook it came up in some asian looking language.

 Publish to app stores

### Risks

Can of worms

### Issue Reference

refs #

**Comment by stdavis** [comment]
v3.0.10 (644) has been published to both app stores.
