### ISSUE TITLE
TURN GPS Bill Pay Support 

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#372]
### Benefit

Additional support is needed to help all TURN GPS subscribers migrate from the old Bill pay system to the new, and follow security protocol by helping them create a UtahID account with an email address that corresponds with their existing TURN GPS subscription.
Presentations have been made at UCLS conference and the Monsen User Group Conference explaining this process, and a video was created from the presentation slides and a link for this was added to the new online bill pay system.

### Acceptance Criteria

The following additional support is needed.
- [x] Schedule to give a presentation at the UAC County Surveyors conference April 30th to help explain the process.
- [x] Continue to take support calls from subscribers that need assistance with bill payment.
- [x] Continue to take support calls from users with questions about the service. 
- [x] Send out an email blast to all TURN GPS subscribers with renewal instructions.

### Issue Reference

refs #

**Comment by seanfernandez** [comment]
All items listed under the Acceptance Criteria are completed as outlined. The presentation to the UAC surveyors went well explaining the new bill pay system to the county surveyor's and all those in attendance as well as the surveyors taking the MRRC training.
There has been a surge in support calls recently as users are learning how to use the new bill pay system. We have created an online instructional video and the link has been emailed out to customers from our local vendors.

**Comment by steveoh** [comment]
Can you group the support calls into categories easily? If you can do that and share it with us, we can explore more ways to improve the website to decrease the number of phone calls you get. For instance we could create a frequently asked questions page and add items after the they are asked more than n times.
