### ISSUE TITLE
TURN GPS and NevadaGPS Website Updates

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#374]
### Benefit

The GPS Network websites for https://turngps.utah.gov/ and https://nevadagps.utah.gov/ need to be updated with relevant content and the text and links need to be fixed, along with color scheme and overall look.

### Acceptance Criteria

- [x] Create links to the new UGRC TURN GPS products  page https://gis.utah.gov/products/turn/.
- [x] Update the website home page main body text.
- [x] Create links to the new online bill pay system.
- [x] Create new links for Support, Resources, Solutions and About.
- [x] Create instructions for all website changes from the out of box Trimble Pivot website

### Issue Reference

refs #

**Comment by steveoh** [comment]
Should we include the accessibility and other issues I brought up from the email today?

**Comment by seanfernandez** [comment]
All items listed under the Acceptance Criteria are completed as outlined.
