### ISSUE TITLE
Dependabot - app dependency updates (FY24 Q4)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#375]
### Benefit

UGRC applications have dependencies that are constantly updating to add new features, improve performance, and patch security issues. Keeping applications current with dependencies improves our security posture and allows for easier future enhancements since the amount of breaking changes is smaller and more trivial.

### Acceptance Criteria

[Close out the org-wide dependency PRs](https://github.com/search?q=org%3Aagrc+author%3Adependabot%5Bbot%5D+is%3Apull-request+is%3Aopen&type=pullrequests)

### Risks

Insecure applications using deprecated services

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
 - 49 tasks remaining as of Sprint 2, day 1 (some won't or don't need to be done)

**Comment by stdavis** [comment]
I think that this is done. There are a few PRs that are still open but we are waiting on them for various reasons.
