### ISSUE TITLE
DWR - Electrofishing

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#38]

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] Follow up on outage
July 4, 2023
> I noticed an issue with the NSX Load Balancer blocking requests that electrofishing makes to edit data in the database. This means that currently, users cannot add stations or new collection events via [electrofishing.ugrc.utah.gov](http://electrofishing.ugrc.utah.gov/). You should still be able to read data via the query app as well as edit and read data directly via tools that connect directly to the database such as ArcGIS Pro. I've submitted a new ticket (INC1853817) asking them to take a look at it. I will keep you posted.

July 28, 2023

> We just had another meeting with Google and VMWare tech support with no real progress. VMWare is escalating the ticket to their engineering department.

**Comment by steveoh** [comment]
Has DWR been made aware of this outage?

**Comment by nathankota** [comment]
> Has DWR been made aware of this outage?

Yes

**Comment by stdavis** [comment]
This has been resolved.
