### ISSUE TITLE
PSAP support with regular updates (FY24 Q4)

### ISSUE THREAD

**Issue by mhchou** [agrc/planning-queue#380]
### Benefit

Ensure PSAP centers have a low dispatch error rate; fulfill the contract responsibilities where applicable; and maintain the 911 fund income for UGRC.

### Acceptance Criteria

- [x] Successfully updated all GIS data for each scheduled entity.
- [ ] Establish a relationship with Logan, Tooele, and Summit Counties.

### Sprint 1

- [x] Price
- [x] Weber
- [x] St George

### Sprint 2

- [x] Weber
- [ ] Beaver

### Sprint 3

- [x] Weber

### Sprint 4
- [x] Salt Lake
- [x] Weber
- [x] St. George

### Sprint 5

- [x] Weber

### Issue Reference

refs #323

**Comment by gregbunce** [comment]
Hank worked with the mobile map package with Duchesne County during sprint 1. That took a decent amount of his time.
