### ISSUE TITLE
Spillman Data Storage, Data Exchange, and Data Source Process Upgrade

### ISSUE THREAD

**Issue by mhchou** [agrc/planning-queue#381]
### Benefit

The routine updates will be less tedious and smoother, which will enable UGRC to provide more frequent updates without signing contracts with specific PSAPs. 

With the help of Portal, we will no longer provide updates through a Dropbox link, instead, PSAP can grab the newest dataset from SGID anytime they desire.

### Acceptance Criteria
For St. George, Weber, Layton PSAPs:
- [x] To start the discussion with all major PSAPs on adopting the new workflows and start implementing them. 
- [ ] Migrate data to Portal, either hosted by UGRC, or PSAP themselves.
- [ ] To adopt data sources from SGID directly. 

### Notes

There is a bottleneck in providing speedy quality customization to all the PSAPs while being the only 911 data coordinator from the State. The solution going forward is for the State/UGRC to initiate the utilization of the statewide dataset - SGID. It has the standardization that all PSAPs in the State will adopt, which also follows the federal NG911 standard from NENA. This initiative will kill 2 birds with 1 stone.
UGRC is holding back from creating data ourselves (customization) locally, which includes creating fake addresses/roads and giving data stewardship back to the local authorities (city/county/state like UDOT).

### Issue Reference

refs #324

**Comment by mhchou** [comment]
Motorola conducted a hybrid ArcGIS Pro demo on 5/22 with all the Utah agencies which also proposed the partnership with UGRC for the Pro upgrade projects. With my involvement in these projects, I will be able to integrate the processes necessary and achieve these goals.

The tentative list of agencies that will be involved with the Pro upgrade projects is shown below:
* means we are not 100% sure if they are on board with the upgrade

**ArcGIS Pro Migration** (in order)
A full ArcGIS Pro Migration would be needed.  The first two agencies we would go through as part of a traditional 5 week process.  The remaining efforts could be streamlined to less time.    
1. Logan PD, UT
2. Tooele County Sheriff, UT
3. Wasatch County Sheriff, UT
4. Layton PD, UT
5. Weber 911, UT
6. Utah County Sheriff, UT
7. Washington County Sheriff, UT
8. Iron County ITS, UT
9. Kane County Sheriff, UT

**GeoValidation Upgrade & ArcGIS Pro Migration**
Motorola Solutions GIS Analyst would be more involved with these efforts to support the GeoValidaiton activation. The build of the ArcPro setup would be the same process as the above category. 
_*agencies that we are still confirming their current Address Validation platform (classic, sentryx, geovalidation)_
1. Millard County Sheriff, UT
2. University of Utah PD, UT
3. Beaver County Sheriff, UT*
4. Emery County Sheriff, UT*
5. Summit County Sheriff, UT*
6. Sevier County Sheriff, UT*
7. Granite School District, UT*

**Completed or Nearing Completion**
1. Salt Lake Communications, UT
2. Price DPS Communications, UT
3. Uintah Basin, UT
4. Box Elder County, UT
5. Grand County, UT

**Comment by steveoh** [comment]
Is this related to these other planning items?

- https://github.com/agrc/planning-queue/issues/80 
- https://github.com/agrc/planning-queue/issues/79
- https://github.com/agrc/planning-queue/issues/83
- https://github.com/agrc/planning-queue/issues/82

**Comment by mhchou** [comment]
@steveoh It is not related to any of those planning times. Nathan and I have made comments under those items accordingly. Thank you!

**Comment by mhchou** [comment]
This issue has grown into the Motorola ArcPro Migration initiative for FY25.
