### ISSUE TITLE
Migrate Masquerade test app from WAB to Instant

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#384]
### Benefit

Esri AGOL Web AppBuilder is headed for mature support. Migrate this app to an Instant app template (but _not_ the Minimalist template, if it still exists, b/c it's also in [mature support](https://www.esri.com/arcgis-blog/products/instant-apps/announcements/instant-apps-announcement-minimalist-moving-to-mature-support-in-the-arcgis-online-october-2022-update/)).

### Acceptance Criteria

- [x] https://github.com/agrc/masquerade/issues/183

### Issue Reference

refs #223

**Comment by stdavis** [comment]
Done.
