### ISSUE TITLE
SGID Index reference

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#386]
### Benefit

To increase awareness and understanding of UGRC staff about the purpose and use of the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) sheet.

### Acceptance Criteria

- [ ] https://github.com/agrc/gis.utah.gov/issues/2685

### Issue Reference

refs #

**Comment by steveoh** [comment]
https://stackoverflowteams.com/c/ugrc/questions/162
