### ISSUE TITLE
Website internal and external link validation

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#387]
### Benefit

Find broken urls in website content

### Acceptance Criteria

- [ ] https://github.com/agrc/gis.utah.gov/issues/2711

### Issue Reference

refs #377

**Comment by steveoh** [comment]
## Sprint 5 notes

I believe that before we can complete this task we must complete some house keeping tasks.

https://github.com/agrc/gis.utah.gov/issues/2769 and https://github.com/agrc/gis.utah.gov/issues/2770

I propose we triage these issues and when we have a clean slate, we can implement lychee into the build process.

**Comment by nathankota** [comment]
A tool was found to carry forward with link validation, but there are some preparatory tasks in #377 to be completed in FY25 before implementing the tool.
