### ISSUE TITLE
Sweeper/forklift - Removing duplicate records

### ISSUE THREAD

**Issue by rkelson** [agrc/planning-queue#388]
We need the ability to exclude various layers from having the duplicate records removed, during the scheduled task, once loaded to SDE. The main issue is with the LIR Parcel layers. 

https://agrc.slack.com/archives/C018YQ6J14N/p1703707887603919

**Comment by stdavis** [comment]
Additional tasks:
- [ ] deploy new sweeper version to forklift machine
- [ ] deploy new forklift version to forklift machine

**Comment by stdavis** [comment]
I asked Rick to reload the LIR data and we verified that neither sweeper nor forklift messed with the duplicate features. I believe that this is done. ✅
