### ISSUE TITLE
Imagery Discussions

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#389]
Tasks associated with discussions for future imagery products.

**Comment by jacobdadams** [comment]
### Sprint 2

- [ ] Analyze current discover usage

**Comment by nathankota** [comment]
@brigsz , @gregbunce , @jacobdadams please provide any relevant closing notes/comments and close this FY24 Q4 objective.

**Comment by gregbunce** [comment]
this feature has been migrated to FY25/Q1 https://github.com/agrc/planning-queue/issues/425
