### ISSUE TITLE
Pre-2016 Backlog of Historic Tie Sheets

### ISSUE THREAD

**Issue by seanfernandez** [agrc/planning-queue#390]
### Benefit

 **Background**
In 2018, years of section corner data was lost during the transition from K Drive to Google Drive. (Historic Data Location - K:\AGRC Projects\PLSS\Utah_PLSS_Fabric\Data\)
There was no backup, and the data could not be recovered. This data included historic tie sheets, coordinate spreadsheets, and survey plats.
Many rural counties did not maintain a current copy, and they did not keep a backup copy of this data because at the time they did not manage their ownership parcels in a GIS system that was tied to accurate ground monuments (section corners).
The purpose of this task is to generally identify how much historic data has been retrieved since the data loss determine how much work it will take to clean it up and suitable for inclusion into the statewide control layer.  

### Acceptance Criteria

- [x] determine the number of tie sheets we have and get it ready for an intern to begin determining if it already exists in the PLSS app
- [x] determine the number of section corners with coordinates we have and get it ready for an intern to begin determining if it already exists in the PLSS app

### Issue Reference

refs #

**Comment by steveoh** [comment]
Sorry about that

**Comment by seanfernandez** [comment]
A number of section corners was determined, but many of the tie sheets for these section corner are all included in the same pdf and need to be broken out into their individual tie sheet to get exact count. Also there are some tie sheets that are lumped together into one image file and will require manually screen shots and broken into individual pdf and renamed to the proper BLM point ID.
Many of the tables that provide the coordinates are in tables that are in a pdf image of the survey plat and work needs to be done to pull these coordinates out manually and add them to a google sheet in the proper schema.
The results of these finding are located here:
https://drive.google.com/drive/folders/1v5HghBTGYkbGp9Rh7Q8AF2KVGMaCzziB?usp=drive_link

https://drive.google.com/drive/folders/1uaqw0uC98O3oIqFbZY_5bUiX2YOqohDv?usp=drive_link
