### ISSUE TITLE
Electrofishing query app upgrade

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#395]
### Benefit

- Rewrite the app to use the [ArcGIS Maps SDK for JavaScript](https://developers.arcgis.com/javascript/latest/)
- Address technical debt and make improvements, where possible

### Acceptance Criteria

Based on the [estimate](https://docs.google.com/spreadsheets/d/1UGBV3UgTeCWJH1ftZpz56hZ_e8m2S1OPyh_TgWSbV1U/edit#gid=0):

- [x] Bootstrap new app and layout
- [x] Build filters UI
- [x] Wire filters
- [x] Results grids
- [x] Data download
- [x] Sherlock for streams and lake names
- [x] Authentication
- [x] Interactive select, deselect on map or grid

### Notes

We have **131** hours ([PRJTASK0614985](https://utah.service-now.com/pm_project_task.do?sys_id=1f879cdd97f2c61452a6bdb8c253af35&sysparm_record_target=pm_project_task&sysparm_record_row=7&sysparm_record_rows=15&sysparm_record_list=parent%3Db2db1bc5973e861452a6bdb8c253af55%5EORDERBYnumber)) in project hours and **41** hours ([PRJTASK0614059](https://utah.service-now.com/pm_project_task.do?sys_id=989aee34c3f6ca547de0b1fc050131a7&sysparm_record_target=pm_project_task&sysparm_record_row=7&sysparm_record_rows=25&sysparm_record_list=parent%3D189aee34c3f6ca547de0b1fc050131a7%5EORDERBYnumber)) in general DWR maintenance left for this project.

### Risks

- client expectations
- scope creep
- timeliness of client feedback and validation
- budget

### Issue Reference

refs #

**Comment by steveoh** [comment]
## Sprint 3 notes

- A lot of time went into designing the layout for this application. We iterated on layout types and functionality and have something we like.
- We've built some modern reusable design system components that are required by this app.

**Comment by steveoh** [comment]
## Sprint 4 Notes
 
- Basic implementation of purpose filter
- Working on date range and other filters
- Working on Utahid login

**Comment by stdavis** [comment]
## Q1 Sprint 5 Notes
* Implement date and species/length filters
* Implement utah id login
* Related design system updates including new Select, Avatar, Firebase* components.
* Enhancements to Sherlock to allow for searching feature services

**Comment by stdavis** [comment]
## Sprint 2

Progress was made with wiring up the filters and getting data into a crude results grid.

**Comment by steveoh** [comment]
### FY25 Q2 Sprint 3

- Updated the color theme and logo for DNR
- Created a busy bar for map loading
- Started a table component
- Created a tab component
- Updated the footer to allow customization
- Added 4 button sizes

**Comment by stdavis** [comment]
I deployed a feature-complete staging release and sent to DWR for review today.

**Comment by stdavis** [comment]
Still waiting for confirmation from Craig that we can push to production. He has been out of the office and gets back today.
