### ISSUE TITLE
Monthly Road Updates (FY25 Q1)

### ISSUE THREAD

**Issue by gregbunce** [agrc/planning-queue#421]
### Benefit

The statewide road centerline dataset supports decision-making and is critical in business systems such as 911 and the address locators. 

### Acceptance Criteria

- [x] A current statewide road centerline dataset in the SGID that adheres, to the best of our ability, to our update schedule. 

### Notes

- [x] July 2024
   - Date: 07/18/2024
   - Counties updated
       - Beaver
       - Box Elder
       - Emery
       - Iron
       - Salt Lake
       - Utah
       - Wasatch
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       - 12630 S CARRAWAY LN, Salt Lake City	84020
       - 132	N 500 W,	Santaquin 84655
       - 150	E MAJESTIC MOUNTAIN RD, Leeds 84746

- [x] August 2024
   - Date: 08/8/2024
   - Counties updated
       - Davis
       - Salt Lake
       - Utah
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       - 918	S REGIONAL PARK RD Hurricane, 84737
       - 550	N 200 W Bountiful, 84010
       - 13035 S BROAD STEM CIR Salt Lake City, 84096
  
- [ ] September 2024
   - Date: 08/29/2024
   - Counties updated
       - Davis
       - Grand
       - Kane
       - Salt Lake
       - Tooele
       - Utah
       - Washington
       - Weber
   - Three new addresses from this road update (for locator testing)
       - 2237 N HILL FIELD RD, Layton 84041
       - 1325 E 1400 N, Payson 84651
       - 518	W DIMAGGIO DR, Tooele 84074

### Issue Reference

refs 
#433 
#431 
#432

**Comment by gregbunce** [comment]
@MichaelAGRC are still on track for me to do a road update on July 18?

**Comment by MichaelAGRC** [comment]
Yes sir.  July 18 is a go.

**Comment by gregbunce** [comment]
waiting for roadgrinder to update to validate the new addresses

**Comment by gregbunce** [comment]
@MichaelAGRC what do you think about Aug 8 for the next road update?

**Comment by gregbunce** [comment]
/validate addresses
- 12630 S CARRAWAY LN, 84020
- 12630 S CARRAWAY LN, Salt Lake City 
- 132 N 500 W, 84655
- 132 N 500 W, Santaquin
- 150 E MAJESTIC MOUNTAIN RD, 84746
- 150 E MAJESTIC MOUNTAIN RD, Leeds

**Comment by MichaelAGRC** [comment]
@gregbunce We're good for August 8th for the update.

**Comment by gregbunce** [comment]
@MichaelAGRC what do you think about a road update on 09/05/2024?

**Comment by gregbunce** [comment]
/validate addresses
- 918 S REGIONAL PARK RD 84737
- 550 N 200 W 84010
- 13035 S BROAD STEM CIR 84096
- 918 S REGIONAL PARK RD Hurricane
- 550 N 200 W Bountiful
- 13035 S BROAD STEM CIR Salt Lake City

**Comment by gregbunce** [comment]
/validate addresses
- 918 S REGIONAL PARK RD, 84737
- 550 N 200 W, 84010
- 13035 S BROAD STEM CIR, 84096
- 918 S REGIONAL PARK RD, Hurricane
- 550 N 200 W, Bountiful
- 13035 S BROAD STEM CIR, Salt Lake City

**Comment by gregbunce** [comment]
hey, @steveoh did something change with the validate addresses github action? see above for what it returned for these addresses:

/validate addresses
- 918 S REGIONAL PARK RD, 84737
- 550 N 200 W, 84010
- 13035 S BROAD STEM CIR, 84096
- 918 S REGIONAL PARK RD, Hurricane
- 550 N 200 W, Bountiful
- 13035 S BROAD STEM CIR, Salt Lake City

**Comment by steveoh** [comment]
Yep it did. One second and I'll get it fixed.

**Comment by steveoh** [comment]
/validate addresses

918 S REGIONAL PARK RD, 84737
550 N 200 W, 84010
13035 S BROAD STEM CIR, 84096
918 S REGIONAL PARK RD, Hurricane
550 N 200 W, Bountiful
13035 S BROAD STEM CIR, Salt Lake City

**Comment by steveoh** [comment]
/validate addresses

918 S REGIONAL PARK RD, 84737
550 N 200 W, 84010
13035 S BROAD STEM CIR, 84096
918 S REGIONAL PARK RD, Hurricane
550 N 200 W, Bountiful
13035 S BROAD STEM CIR, Salt Lake City

**Comment by steveoh** [comment]
/validate addresses

- 918 S REGIONAL PARK RD, 84737
- 550 N 200 W, 84010
- 13035 S BROAD STEM CIR, 84096
- 918 S REGIONAL PARK RD, Hurricane
- 550 N 200 W, Bountiful
- 13035 S BROAD STEM CIR, Salt Lake City

**Comment by gregbunce** [comment]
/validate addresses

- 2237 N HILL FIELD RD, Layton
- 1325 E 1400 N, Payson
- 518 W DIMAGGIO DR, Tooele
- 2237 N HILL FIELD RD, 84041
- 1325 E 1400 N, 84651
- 518 W DIMAGGIO DR, 84074

**Comment by gregbunce** [comment]
@steveoh what am i doing wrong? (see my last comment)

**Comment by gregbunce** [comment]
/validate addresses

- 2237 N HILL FIELD RD, 84041
- 1325 E 1400 N, 84651
- 518 W DIMAGGIO DR, 84074
- 2237 N HILL FIELD RD, Layton
- 1325 E 1400 N, Payson
- 518 W DIMAGGIO DR, Tooele

**Comment by gregbunce** [comment]
@steveoh you can ignore my questions above. it's working. thanks for creating this function.
