### ISSUE TITLE
Camp Williams data and web map creation

### ISSUE THREAD

**Issue by ZachBeck** [agrc/planning-queue#423]
### Benefit

Updated facilities and range boundary web maps for Camp Williams

### Acceptance Criteria

- [x] Buildings on base
- [x] Small arms impact areas ("ranges") 
- [x] Camp Williams boundary
- [x] Some roads showing access to ranges, and among the buildings(?)
- [x] Web maps created

### Notes

At this time it is uncertain the level of efforted needed to create the range boundary map. 

### Issue Reference

refs #

**Comment by gregbunce** [comment]
looks like [OSM](https://www.openstreetmap.org/search?query=camp%20williams#map=18/40.43582/-111.92457) has building footprints and address numbers. 


![Image](https://github.com/agrc/planning-queue/assets/16906316/0a4d815f-e03a-4264-871a-c6af34a62257)

**Comment by gregbunce** [comment]
you can use the [Overpass API](https://overpass-turbo.eu/) to download data from OSM

**Comment by ZachBeck** [comment]
[Camp Williams viewer](https://experience.arcgis.com/experience/dc840a39e4e947cf813bb78af20f4f18/?draft=true) sent for review

**Comment by steveoh** [comment]
Can some of the checkboxes above be clicked?

**Comment by ZachBeck** [comment]
### Sprint 4
Add roads attend and deal feedback.

**Comment by ZachBeck** [comment]
Requested changes to popups, legend, and AOI's made and sent back for review.

https://experience.arcgis.com/experience/dc840a39e4e947cf813bb78af20f4f18
https://experience.arcgis.com/experience/d93e54c0e4984720acb66a63e69105df

**Comment by ZachBeck** [comment]
Apps are working as DTS needs, no other requests at this time.
