### ISSUE TITLE
Porter issues (FY25 Q1)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#426]
### Benefit

Close out pending issues to get data added to and removed from SGID. Doesn't look like there are any pending app additions or deprecations.

### Acceptance Criteria

- [x] https://github.com/agrc/porter/issues/336
- [x] https://github.com/agrc/porter/issues/335
- [x] https://github.com/agrc/porter/issues/334
- [x] https://github.com/agrc/porter/issues/333
- [x] https://github.com/agrc/porter/issues/332
- [x] https://github.com/agrc/porter/issues/331
- [x] https://github.com/agrc/porter/issues/337
- [x] https://github.com/agrc/porter/issues/256
- [x] https://github.com/agrc/porter/issues/325
- [x] https://github.com/agrc/porter/issues/257
- [x] https://github.com/agrc/porter/issues/297
- [x] https://github.com/agrc/porter/issues/330
- [x] https://github.com/agrc/porter/issues/327
- [x] https://github.com/agrc/porter/issues/326
- [x] https://github.com/agrc/porter/issues/304
- [x] https://github.com/agrc/porter/issues/305
- [x] https://github.com/agrc/porter/issues/316
- [x] https://github.com/agrc/porter/issues/320
- [x] https://github.com/agrc/porter/issues/321

### Notes

- Assignees are those that have unchecked boxes/tasks on the issues in the Acceptance Criteria.
- If #181 is completed in FY24 Q4, then 256 and 257 can be struck through for FY25 Q1

### Risks

**Own and resolve:** UGRC staff time and memory to follow through. Conductor's nag bot is the attempted resolution.
**Accept:** blocked tasks when waiting on external partners to provide data or input, complete a task, and so forth.

### Issue Reference

refs #

**Comment by nathankota** [comment]
added speed test dashboard deprecation to issue list in Acceptance Criteria

**Comment by gregbunce** [comment]
closing out this issue for the quarter. We'll get a new one for next quarter. thanks everyone!
