### ISSUE TITLE
Utah Broadband Center Support (FY25 Q1)

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#427]
### Benefit

As the GOEO Broadband Center navigates the processes for distributing federal funds for expanding broadband service in Utah, they require and request technical analysis and mapping of a variety of data to adhere to defined federal and state processes, and that the funds are distributed properly. UGRC provides these technical analytical services.

### Acceptance Criteria

Provide results within timelines sought by the GOEO Broadband Center. Specific tasks will be determined and described within sprint-level comments.

### Risks

- lack of clarity of requirements
- short deadlines/turnaround times
- interruption of other PI objectives

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 2
- Transform and map challenged locations (pending data from Steve Greene)
- Statewide comparison of fabric v3 vs. v4
  - new BSLs
  - dropped BSLs
  -  higher service in v4 vs v3
  - lowe service in  v4 vs v3

**Comment by jacobdadams** [comment]
### 25.1.3

- [x] Get speeds and classifications for CAIs for Claire

**Comment by jacobdadams** [comment]
### 25.1.4

- [ ] Two lists: challenged points and statewide unchallenged points
- [ ] challenged points:
  - Service status: 0/1/2 unserved/underserved/served
  - Number of providers claiming served status
  - Technology type for challenge point based on BSL/provider ID
- [ ] Statewide unchallenged points
  - Remove challenged points, CAIs from statewide fabric
  - service status 0/1/2

**Comment by jacobdadams** [comment]
### 25.1.5

- [x] Non-BSL CAI service

**Comment by jacobdadams** [comment]
### 25.1.6

- [x] Deduplication of challenge points for Claire/Steve

**Comment by jacobdadams** [comment]
Closing for Q1 as completed, no open requests/tasks. New issue opened for Q2
