### ISSUE TITLE
Web API Endpoint Feature and Response Parity

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#43]
### Statement of Need/Objective
UGRC is tasked by Utah state code to create and maintain the State Geographic Information Datasource (SGID). The SGID contains statewide, authoritative roads and address point data, along with many other layers of geospatial information that help decision makers. UGRC has developed a web API for to provide access SGID data sets. A common use of the web API is geocoding to produce a real world set of location coordinates from an address that can then be used to search overlapping spatial data such as voting precincts, tax districts, and other types of boundaries.  UGRC needs to upgrade this web API and associated services to keep it relevant, innovative, and functioning smoothly for end users. At the most basic level, replace the current system with a cloud system. 

## Benefit Hypothesis
The new geocoding and search endpoints need to generate expected responses and results and be comprised of the same features as the current endpoints.

## Acceptance Criteria
- **Geocoding Endpoints:** Complete remaining feature and response parity among all geocoding endpoints
- **Search Endpoints:** Complete feature and response parity for search endpoints

**Comment by nathankota** [comment]
### Sprint 1 Tasks

- Get some external testers lined up. Possibilities include:
  - [ ] Nick Kenczka (Tax)
  - [ ] Bryce Wright (DHHS)
  - [ ] Trent Packer (Legislature)
  - [ ] Justin Miller (DWS)
  - [ ] Clancy Black (UDOT), along with Kelli Bacon
  - [ ] Alex Gilvarry (UDOT), plus Cory Unger

Notes/pointers to communicate to them:
- Will need their API keys
- Situational after that, but should be a url change in the dev apps, blue/green prod, or the like.
- Set up meetings if necessary to help/talk them through 
- They'll need to validate that the expected application- or project-specific properties are being returned from the new API
- (might be able to set up a host record for some of the testers?)

**Comment by nathankota** [comment]
### Sprint 2 and beyond tasks 
- [ ] Switch some of our own apps (e.g. Atlas as a first test)
- [ ] Phase II: Use the mailing list and set up a form to see who is willing to test it, beyond the initial group
    - Send the dev API url
    - Update keys
    - Tell them to post issues to github or send us emails by a specific date

**Comment by nathankota** [comment]
### Future Sprints
- Phase II: Use the mailing list and set up a form to see who is willing to test it, beyond the initial group
  - Send the dev API url
  - Update keys
  - Tell them to post issues to github or send us emails by a specific date

**Comment by nathankota** [comment]
### Sprint 3 Notes

**Comment by nathankota** [comment]
### Future Sprints
- [ ] Switch some of our own apps (e.g. Atlas as a first test)
- Phase II: Use the mailing list and set up a form to see who is willing to test it, beyond the initial group
  - Send the dev API url
  - Update keys
  - Tell them to post issues to github or send us emails by a specific date

**Comment by nathankota** [comment]
### Sprint 4 Tasks
- [ ] Get Alex Gilvarry set up to test
- [ ] Trent Packer to test (confirmation of testing Steve already did?)
- [ ] One more tester?

**Comment by nathankota** [comment]
### Sprint 5 Tasks
- @brigsz will nudge the testers

**Comment by nathankota** [comment]
@brigsz and/or @steveoh please provide a comment about the progress made on, and status of, this objective to close it out for Q1. If there are additional tasks to follow, we can create a Q2 uncommitted "feature".

**Comment by nathankota** [comment]
Some testing occurred, but maybe not as much as expected or hoped(?).

**Comment by steveoh** [comment]
sorry i was giving matt a chance to comment
