### ISSUE TITLE
WRI map rewrite preparation

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#430]
WRI stands for [Watershed Restoration Initiative](https://wri.utah.gov/wri/), a landscape-level ecological restoration program managed by the Department of Natural Resources, and through the Division of Wildlife Resources. More about WRI [here](https://watershed.utah.gov/).

### Benefit

- Do some of the groundwork to be prepared for the major development work to rewrite the WRI mapping app

### Acceptance Criteria

- [x] Download code from GitLab (if our licenses are expired, then submit a ticket to get DTS to do it)
  - [x] Contact dtssam@utah.gov to remove GitLab subscriptions and billing
- [x] Move map app code to Drive
- [x] Create GitHub repository
- [x] Create GitHub issues for [major tasks](https://docs.google.com/spreadsheets/d/1nOjp4uwaB5SSZ0ANCFjEQzcwyv3YZ1Qy_LRVI5XxX10/), and break them down as needed
- [ ] CI integration (e.g. modify CI to checkout github repo for deployments, etc.)
- [ ] Other required coordination with DTS to integrate with the DTS app

### Risks

- DTS's time for coordination
- The GCVE migration may affect the DTS WRI servers and the DNR spatial servers.

### Issue Reference

refs #

**Comment by steveoh** [comment]
## Sprint 5 notes

- The code has been downloaded from GitLab
- I emailed DTS SAM and removed my access along with Scott
  - This [dashboard](https://workspaces.dts.utah.gov/now/nav/ui/classic/params/target/%24pa_dashboard.do%3Fsysparm_dashboard%3D7027dbb347020a10f908bd51026d4311) was shared with me and I updated a few more random services

**Comment by steveoh** [comment]
### Sprint 6 notes

- terraform modules were created to create an ideal GitHub repository
- The wri repository has been created. Issues can now be created for major tasks

**Comment by stdavis** [comment]
Closing this as the last two items are more related to actual development work. Nice work, @steveoh !
