### ISSUE TITLE
Migrate Surface Water Quality to ExB

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#439]
Full app name is the Department of Environmental Quality's Beneficial Uses and Water Quality Assessment Map

### Benefit

- Migrate data and app from UGRC infrastructure to DEQ's AGOL
- Deprecate another [UGRC-managed app](https://wq.deq.utah.gov/)
- Simplify data management, or at least data transfer from source to AGOL and app

### Acceptance Criteria

- [x] Migrate/transfer data to DEQ AGOL
- [ ] Configure web map and application in DEQ AGOL

### Notes

[PRJTASK0627469](https://utah.service-now.com/pm_project_task.do?sys_id=8ca32ec287a70a108f0711773cbb359a&sysparm_record_target=pm_project_task&sysparm_record_row=8&sysparm_record_rows=14&sysparm_record_list=parent%3Db2db1bc5973e861452a6bdb8c253af55%5EORDERBYshort_description)
DPR-1094

### Risks

- Data cannot be easily managed or migrated to AGOL
- DEQ/DWQ staff time for feedback and validation
- Experience Builder configuration limitation

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Q5 Sprint 1 Notes 
- SBA sent for approval July 23
- Meeting scheduled for August 6 to discuss data migration, hosting, and maintenance in DEQ AGOL

**Comment by stdavis** [comment]
Julian Carroll sent an email this morning with a link to a [new experience builder app](https://experience.arcgis.com/experience/c58b8c44b7a8482cb9dd20e2cf8c263c) that they have developed in-house that seems to be the replacement for this. They are asking about how to get wq.deq.utah.gov pointed at their new app so I assume that this is the end of the road for this task unless @ZachBeck has some additional information.
