### ISSUE TITLE
Google analytics 360

### ISSUE THREAD

**Issue by steveoh** [agrc/planning-queue#459]
### Benefit

The UX team has an enterprise license for Google Analytics 360. This would allow us to roll up all of our properties to get a wholistic view of our web presence. It is free to us and if the license goes away, our properties are not affected.

### Acceptance Criteria

- [ ] UGRC GA are rolled up into the enterprise 360 account

### Issue Reference

refs #

**Comment by stdavis** [comment]
# Sprint 6
We met with Rachel Stone and upgrade properties to 360 and created an internal rollup.

At some point she may ask us to migrate our properties to the state account so that they can be rolled up into other groups.
