### ISSUE TITLE
Dependabot Updates (FY25 Q2)

### ISSUE THREAD

**Issue by stdavis** [agrc/planning-queue#479]
### Benefit

UGRC applications have dependencies that are constantly updating to add new features, improve performance, and patch security issues. Keeping applications current with dependencies improves our security posture and allows for easier future enhancements since the amount of breaking changes is smaller and more trivial.

### Acceptance Criteria

Close out the [org-wide dependency PRs](https://github.com/search?q=org%3Aagrc+author%3Adependabot%5Bbot%5D+is%3Apull-request+is%3Aopen+archived%3Afalse&type=pullrequests) and merge the [pending release pr's](https://github.com/search?q=org%3Aagrc+label%3A%22autorelease%3A+pending%22+is%3Aopen+type%3Apr+&type=pullrequests&ref=advsearch)

- [ ] #460
- [ ] Separate out deploys into release workflows
- [ ] Implement https://github.com/agrc/release-issue-notifications-action

### Notes

Insecure applications using deprecated services

### Risks

The deployment breaks the application

### Issue Reference

**Comment by stdavis** [comment]
All of my projects are done. I tried to focus on the three checkboxes in the description of this issue. I ended up doing a fairly significant upgrade to the roadkill skid (function -> cloudrun job and updates).

**Comment by steveoh** [comment]
we put a major dent in this and will do it again next quarter. Scott and I will clean up any loose ends that we can.
