### ISSUE TITLE
2024 HxGN TIFF Tiles

### ISSUE THREAD

**Issue by rkelson** [agrc/planning-queue#509]
### Benefit

Provide the actual flight dates of imagery in the Hexagon services via OpenData. Also facilitate requests for the original imagery tiles

### Acceptance Criteria

- [x] Inventory what Hexagon provided
- [x] Create layer and update [Utah Hexagon Service Dates](https://opendata.gis.utah.gov/datasets/7df5278c3e1a46389693c957a75b2b99_0/explore) OpenData layer
- [x] Create tile index with attributes for the folder and drive

### Notes

- 

### Risks

- None

### Issue Reference

- #

**Comment by steveoh** [comment]
Atlas shows the flight data. Will we need to repoint to this data when it's available?

**Comment by rkelson** [comment]
I doubt it but I really don't know what you are using. I simply added the
new tiles to
https://opendata.gis.utah.gov/datasets/7df5278c3e1a46389693c957a75b2b99_0/explore
then deleted the old tiles. This task is complete.

Rick Kelson
Utah Geospatial Resource Center (UGRC)
801.433.7891
gis.utah.gov

**Comment by rkelson** [comment]
this is complete

**Comment by steveoh** [comment]
Atlas uses `indices.hexagon_service_dates` in the open sgid.

https://github.com/agrc/atlas/blob/ce562f16bceda3fe54de6c90da7e9437a1370fec/src/components/Identify.jsx#L10-L19
