### ISSUE TITLE
Vector Tile Base Map Hosting and Caching Planning

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#51]
### Statement of Need/Objective
UGRC base maps are heavily used and with growing usage they are in need of an update not only visually, but also technologically in the way they are consumed. They need to be updated to, and available via, the latest technology to allow for more efficient loading and rendering, for both raster and vector products; and as widely available and easy to use as possible. 

## Benefit Hypothesis
UGRC needs to determine where the vector tile base maps should be hosted for end user access and to plan the base map update process and schedule. 

## Acceptance Criteria
Three main things:
1. Hosting (AGOL v Giza)
2. Maintenance and creation
3. Deprecation plan for raster
  - discuss when; plan to switch apps that are currently using them

- Compare hosting and serving vector tile base maps on Discover vs ArcGIS Online
  - Obtain information from AppGeo/Sanborn about if and how they can make vector tile base maps available via Discover for seamless transition for end users. (they cannot server vector tiles via wmts and, therefore, there is no possibility for a seamless transition)
- Determine how and where to build vector tile caches
  - Define and implement update process, whether Honeycomb or other
- Create an update process for the existing parcel and plss vector base maps 
  - New server doesn't have access and they haven't been updated by Honeycomb

**Comment by nathankota** [comment]
Meeting Notes:
https://docs.google.com/document/d/1lFPssGZSq72FmGz4LnGM7h_xdMhP7G6FxhSS4ldJ1HM/edit#

Matt summary (April 19, 2023):

> We should be moving towards producing and serving vector basemaps
We should deprecate the raster ones
We are still deciding where they should live
How can we push other basemap creators to ingest our updated data quicker than current.

**Comment by nathankota** [comment]
## Future Features/Tasks
- Transfer other UGRC base maps as possible to vector format?
- ...

## Reference
Meeting Notes:
https://docs.google.com/document/d/1lFPssGZSq72FmGz4LnGM7h_xdMhP7G6FxhSS4ldJ1HM/edit#

Matt summary (April 19, 2023):
- We should be moving towards producing and serving vector basemaps
- We should deprecate the raster ones
- We are still deciding where they should live
- How can we push other basemap creators to ingest our updated data quicker than current.

**Comment by nathankota** [comment]
### Sprint 1 Tasks
- [ ] See what you can learn from the base map team at the Esri UC about best practices for managing multiple base maps that share underlying data; costs/benefits of one style file per base map vs. multiple styles all referencing the same vector tiles, merged for styling ( @ZachBeck)

**Comment by nathankota** [comment]
### Sprint 2 Tasks
- [ ] Engage AppGeo one more time to try to finalize yay or nay on vector tiles on Giza (@rkelson)

**Comment by nathankota** [comment]
### Sprint 2 Notes

**Comment by nathankota** [comment]
### Sprint 3 Tasks
 - [ ] Engage AppGeo one more time to try to finalize yay or nay on vector tiles on Giza (@rkelson)
 - [ ] Research editing tiles through AGOL vector tile editor for creating new style file (@ZachBeck)

**Comment by nathankota** [comment]
- [ ] research how to apply certain color/symbology/style across all scale levels of a specific map category/group (e.g. water) in AGOL style editor

**Comment by nathankota** [comment]
### Sprint 4 Notes
#### August 24
Emailed Pete and Amber to connect with an Esri vector tile editing expert

**Comment by ZachBeck** [comment]
Sent Sanborn vector tile packages to test hosting on Discover.

**Comment by nathankota** [comment]
A new Q2 objective hosts new tasks as logical next steps.
