### ISSUE TITLE
Metadata database (and app?)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#60]
To promote vertical integration of the data, their sources, and processes around getting data sets in, out, and around the distributed SGID. For example, Porter as a tool is reflective of the perceived lack of integration, in that it is difficult to know who needs to do what, and when, in the introduction and deprecation processes, and the status of those processes.

**Comment by jacobdadams** [comment]
How is this different from the MATT?

**Comment by nathankota** [comment]
> How is this different from the MATT?

Good question. It's not different, and just one part of the MATT. This particular issue is one of the original ones created in the planning repo and board. I'm sure it will come back around as a task for the MATT, and it may evolve by that point, so I'll go ahead and close this.
