### ISSUE TITLE
SGID Data Lifecycle

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#61]
From the March 7, 2023 Combined Data/Dev Team meeting, a conversation that arose around how to deal with FEMA floodplain data that used to be aggregated and organized by UGS and sent to UGRC for inclusion in the SGID; but the strategy should change to direct users to the authoritative FEMA souce:

_How do we proceed with making this data discoverable via the open sgid and open data?  Where is the line in the sand on what we make available in our ‘hosted’ data and to what we point folks to? 
We need to define that line in the sand. 
Is used in the API?
Is it used in basemaps?
Idea: use the api to suggest what should be hosted in the sgid.  The data pages analytics?
How does the sgid index play into this
Making sure it remains a curated list
Maybe this becomes a part of the PI Planning. The bigger picture of how we proceed with the next version of the data lifecycle… sgid rating system, sgid index db, etc…_

**Comment by gregbunce** [comment]
- stewardship database
- sgid index
- new website
- sgid rating system
