### ISSUE TITLE
ArcGIS API for JS 3x Migration Phase 1

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#63]
### Statement of Need/Objective
UGRC has many applications running on the [ArcGIS API 3.x for JavaScript](https://developers.arcgis.com/javascript/3/), which will be retired on July 1, 2024. _Once version 3.x is retired, there will be no further bug fixes or enhancements to the API and hence no further 3.x API deployments to js.arcgis.com. In addition, technical support will no longer be available._ The AGOL Web AppBuilder will also cease to be supported. 
([Refer to Esri blogpost for more detail](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/))

## Benefit Hypothesis
To stay well ahead of the 3x API retirement, UGRC will migrate some of the "easier" apps from Web AppBuilder, and will plan for larger apps and projects that use the API.

## Acceptance Criteria
- [ ] Confirm completeness of the [application inventory](https://lucid.app/lucidchart/73073b2f-02bb-4495-9790-b21d9e649e24/edit?viewport_loc=-367%2C-1606%2C6083%2C4005%2C0_0&invitationId=inv_b4c7887c-d4b8-498b-8ff4-058aeff71a80)
- [ ] Deprecate unused Web AppBuilder and other apps
     - [x] ERAP - Jake (This was approved for deprecation via [Porter #253](https://github.com/agrc/porter/issues/253))
     - [x]  **Health Facilities:** June 26, 2023 - Angela Anderson, DHHS Business Analyst, said that "The higher powers have determined they no longer want to continue with the map". Deprecated via [Porter #241](https://github.com/agrc/porter/issues/241).
- Make a plan for the following:
   - [x] DEQ Enviro (rebuilt at 4x in the new/upgraded app)
   - [ ] [Fire Business](https://github.com/agrc/fire-business) (Nathan & Steve)
   - [x] [DEQ Spills](https://github.com/agrc/deq-spills) (Nathan & Scott): The app it is integrated with is being converted to SalesForce. 
   - [ ] [Surface Water Quality](https://wq.deq.utah.gov/) (Nathan & Scott)
   - [x] Newborn Hearing - they are not going to have us rebuild the app this year. We will try again with them next year, using [this draft contract](https://docs.google.com/document/d/1u40nlgUEgynKBTfOE-VxadKJhlLz39bU6-A7GtizUuA/edit) as a template. Calendar reminder created for April 1, 2024.
   - [x] Fleet Fuel Sites (new contract initiated to rebuild app) - Rick
   - [x] DPU (contract in place, plan for Q2 rebuild) - Zach
   - [x] SBI Locate https://sbilocate.ugrc.utah.gov/ (contract in place, plan for Q2 AGOL app rebuild)
- Migrate the following apps to Experience Builder or another supported AGOL app
   - [ ] Voting Districts - Rick

**Comment by nathankota** [comment]
## Future Features/Tasks
- Start migrating the "plan for" apps above
- Plan for:
  - Fleet Vehicle Filter
  - Locate
  - Biobase
  - Address Point Editor
  - Electro Query
  - Raster
  - Broadband Resi
  - Coronavirus Testing (English and Spanish)
  - WRI  
  - Facility Explorer
  - Voting Districts
  - Coronavirus Testing (English and Spanish)

**Comment by nathankota** [comment]
Sprint 2 Tasks
- [ ] See if anything has kicked loose for Karen's fuel sites data table, to help us determine how to start planning

**Comment by nathankota** [comment]
### Sprint 3 Tasks
@nathankota - do this

**Comment by nathankota** [comment]
### Sprint 3 Notes
08/21/2023
- dinged Chris Parker (DPU) again about the public utilities draft agreement

**Comment by nathankota** [comment]
### Sprint 4 Tasks
- [ ] Investigate SalesForce for DEQ Spills (@steveoh @stdavis)
- [ ] Meet with DHHS about SBI Locate ( @nathankota)
- [ ] Finalize DPU agreement

**Comment by nathankota** [comment]
from this objective we were able to generate Q2 objectives to upgrade or replace several apps

**Comment by stdavis** [comment]
@nathankota Did Electrofishing-query (https://github.com/agrc/electrofishing-query) slip through the cracks for this issue?

**Comment by stdavis** [comment]
@nathankota Did raster.utah.gov slip through the cracks on this one as well? I don't see any PI planning issues for it. It needs some short-term work (see [current issues](https://github.com/agrc/raster/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)) and it also needs to be migrated to the 4.x Esri api.
