### ISSUE TITLE
Public Utilities app and data rebuild

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#65]
https://utah.maps.arcgis.com/apps/Viewer/index.html?appid=573dfdb6220d4fada6d833def633b866

**Contact:** Ronald Slusher (Commerce Dept., Public Utilities, Utility Technical Consultant)

**Comment by ZachBeck** [comment]
Old Public Utilities app has been replaced with an ExB version https://experience.arcgis.com/experience/e9c56c0135084f47920317704b0d3d2c
