### ISSUE TITLE
UGRC MATT - DB Schema and Data links

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#76]
### Statement of Need/Objective
Over time, the existing sheet used by UGRC staff to inform our SGID data update process has become outdated and no longer suits the intricacies of the actual data update lifecycle. We need a more advanced and robust system to manage all aspects of the lifecycle of SGID data sets. Ultimately, we seek to create a centralized, single source of truth place and associated processes for SGID metadata (both UGRC and data layer) to be captured, managed, and distributed to all necessary SGID access points, whether the UGRC website, AGOL/open data, Open SGID, internal database, and so forth. A more fully integrated data stewardship process to merge all the existing disparate parts of SGID and data management. Having a single source of truth is an ideal goal so that all facets of the SGID (agol, open sgid, etc.) are updated and operating from the same data.

## Benefit Hypothesis
Begin building the data foundation for the MATT system.

## Acceptance Criteria
- ID apps (APM) that will use the database
- Start to define schema for:
    - Update schedule, contacts, inventory/SGID index, metadata

**Comment by gregbunce** [comment]
is @ZachBeck out of town that day?

**Comment by nathankota** [comment]
> is @ZachBeck out of town that day?

he said it should work

**Comment by ZachBeck** [comment]
I always have time for MATT

**Comment by jacobdadams** [comment]
Couple of links from the FOSS4G conference videos that have been trickling out the last week or so:

- https://www.youtube.com/watch?v=v7GGRS_uUyU - Swiss online data catalog
- https://www.youtube.com/watch?v=ifURAYn-JBw - Open Metadata integration with OGC
- https://open-metadata.org/
- https://geonetwork-opensource.org/
- https://geonode.org/
- https://www.atlas.alpconv.org/ - a good example GeoNode site

**Comment by steveoh** [comment]
Those links are confusing to me. They seem related to software that competes with arcgis online and open data. We aren't looking to replace those right?

**Comment by nathankota** [comment]
https://docs.google.com/spreadsheets/d/15klUwf3IGEi-1HvPeviFtnjfVO_HClVU7Qw9DSzp470/edit#gid=0

**Comment by nathankota** [comment]
Not as much time was spent on this as hoped, but we were able to do a first pass of the stewardship sheet and app list in service now.
