### ISSUE TITLE
Broadband - BEAD Challenge Portal - Planning

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#78]
### [Process diagram](https://lucid.app/lucidchart/8abe2ba6-9ea4-429c-bdf8-ff42cff8b547/edit?viewport_loc=-308%2C16%2C2530%2C1186%2C0_0&invitationId=inv_ab822103-31be-4e20-b6ac-13b2191b7b32)

**Comment by jacobdadams** [comment]
Benefit: Fulfilling our SOW/agreement with GOEO/UBC. Help Utahns get the best broadband service possible.

Acceptance Criteria: Use all available GOEO hours???

**Comment by nathankota** [comment]
### Sprint 1 Task

- [ ] Work with Rebecca Brown at GOEO to investigate triggering a SalesForce survey within in AGOL map/app

**Comment by nathankota** [comment]
### For Later
- [ ] - [ ] Acquiring map requirements from GOEO Broadband
- [ ] Creating base map (fabric data as a raster tile?)

**Comment by jacobdadams** [comment]
slightly unrelated, from 24 Aug meeting: 
- take award_points layer (https://utah.maps.arcgis.com/home/item.html?id=70cd423227fd42b9938098b2a44406af) (minus the west mountain points) and find BSLs corresponding to the address points
- Due by end of September

**Comment by nathankota** [comment]
Continues via #245 
@jacobdadams was the Sprint 6 task completed?

**Comment by jacobdadams** [comment]
Ah, yes. I sent points along to Claire and am waiting to hear back about any questions or anything.
