### ISSUE TITLE
Spillman Recurring Data Updates (911)

### ISSUE THREAD

**Issue by eneemann** [agrc/planning-queue#79]
Supported PSAPs and rough update frequency:

- Weber Area 911 (weekly)
- St George/Washington County (quarterly)
- Box Elder DPS (biannual)
- Uintah Basin DPS (biannual)
- Richfield DPS (biannual)
- Salt Lake DPS (biannual)
- Central Utah - Juab (biannual)
- Davis County/Layton (quarterly)
- Beaver County (biannual)
- Millard County (annual)

**Comment by nathankota** [comment]
taken over by @mhchou

**Comment by mhchou** [comment]
superseded by #380
