### ISSUE TITLE
Spillman Geovalidation Upgrade Projects (911)

### ISSUE THREAD

**Issue by eneemann** [agrc/planning-queue#80]
PSAPs with plans to upgrade:

- Salt Lake DPS (late stages)
- Davis County/Layton (middle stages)
- Uintah Basin DPS (early stages)
- Box Elder DPS (early stages)
- Richfield DPS (not started)

PSAP with unknown plans:

- Beaver County
- Millard County

**Comment by nathankota** [comment]
superseded by #381
