### ISSUE TITLE
NG911 Core Services Data Updates 

### ISSUE THREAD

**Issue by eneemann** [agrc/planning-queue#81]
Data updates on a roughly monthly schedule plus out-of-cycle updates:

- PSAP Boundaries
- Address Points
- Road Centerlines
- Response Polygons (near future)
  - Law
  - Fire
  - EMS

**Comment by gregbunce** [comment]
This data was updated on 8/8/2023

**Comment by nathankota** [comment]
### Sprint 5
- Next update

**Comment by gregbunce** [comment]
scheduled for 9/7/2023

**Comment by nathankota** [comment]
@gregbunce did this happen and can we close this down?

**Comment by nathankota** [comment]
@gregbunce please provide a comment and close this issue/task

**Comment by gregbunce** [comment]
This has been successfully completed.
