### ISSUE TITLE
Masquerade Enhancements

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#91]
### Benefit

Reverse geocoding functionality as an enhancement to Masquerade as requested by a few folks. I'm also included some other enhancements while I'm working don't the project that will allow it to satisfy more use cases.

### Acceptance Criteria

- [x] https://github.com/agrc/masquerade/issues/169
- [x] https://github.com/agrc/masquerade/issues/182
~- [ ] https://github.com/agrc/masquerade/issues/173~

#### Statements of Need:
From: Sumerset Ellis (UDOT GIS Asset Administrator)

> Date: Tue, Apr 18, 2023 at 1:19 PM
> Subject: Using+the+UGRC+Web+API+to+geocode+addresses
> To: [ugrc@utah.gov](mailto:ugrc@utah.gov) <[ugrc@utah.gov](mailto:ugrc@utah.gov)>
> 
> Hi all, I was wondering if you had a Pro toolbox for reverse geocoding. I have 1000s of XYs that need addresses. Thanks so much!

Also:

> South Jordan is attempting to use Masquerade within their CityWorks instance and this came up again. Just another data point for motivation to get it done.

### Issue Reference

refs #

**Comment by stdavis** [comment]
## FY25 Q2 Notes
I picked up this task with some extra time in this sprint. Two out of the three issues in this task where completed. The third issue is likely a "won't fix" for the time being. Check out the [release notes](https://github.com/agrc/masquerade/releases/tag/v1.5.5) for the full list of improvements.
